### ISSUE TITLE
[FEATURE REQUEST] --insecure flag by default

### ISSUE THREAD

**Issue by hvprvtr** [epi052/feroxbuster#1003]
Please, make --insecure falg enabled by default. Every time i adding more one param in template cmd for hosts with self-signed cert. But in every case SSL trouble is not important and not worthy of attention.

As i see, ignoring this certs it is de-facto standart in same tools like dirb, ffuf or other. Very unusual specify this param after fail with standart brute cmd.

**Comment by epi052** [comment]
thanks for taking the time to put in this request! i'm not a fan of making `--insecure` the default at this point. I understand other tools may behave that way, but ferox hasn't and to change at this point would almost certainly dork with other users assumptions. 

As a solution for you, I'd recommend either a user or system level [ferox-config.toml](https://epi052.github.io/feroxbuster-docs/docs/configuration/ferox-config-toml/) with the following contents. Then that setting is always on for you.

```
insecure = true
```
