### ISSUE TITLE
[BUG] Using `--parallel` flag prints equal number of empty lines

### ISSUE THREAD

**Issue by rew1nter** [epi052/feroxbuster#1008]
**Describe the bug**
`--parallel 50` prints 50 newline at the beginning of the scan

**Environment (please complete the following information):**
 - feroxbuster version: 2.10.0
 - OS Arch

**Comment by epi052** [comment]
i'll give this a look, thanks for reporting!

**Comment by epi052** [comment]
morning! checked this out today and i don't see this behavior. my results start directly after the command

```
└─(feroxbuster)─> echo -e 'https://bitdiscovery.com\nhttps://tesla.com' | ./target/debug/feroxbuster --stdin --parallel 50
https://bitdiscovery.com/login
https://bitdiscovery.com/homepage/assets/img/tn_asm_logo_white.svg                                                                                                                   https://bitdiscovery.com/About
...
```

**Comment by epi052** [comment]
i fixed a few things with --parallel, and havent seen this happen yet. closing for now. feel free to reopen if necessary
