### ISSUE TITLE
[BUG] feroxbuster arbitrary paths despite specifying `--dont-extract-links`

### ISSUE THREAD

**Issue by rew1nter** [epi052/feroxbuster#1009]
**Describe the bug**
I have seen arbitrary paths being requested at least 8 times today when I had this path specified. 

**To Reproduce**
1. Have a small wordlist
2. run across a large number of urls with a proxy and observe

**Expected behavior**
Only request wordlist paths

**Environment (please complete the following information):**
 - feroxbuster version: [e.g. v1.0.1]
 - OS Arch linux

**Comment by epi052** [comment]
howdy! if you're referencing the paths from your other issue #1007, those are the requests used to determine what the site uses as its 404 (whether it's a 404 or not). 

the related code is [here](https://github.com/epi052/feroxbuster/blob/main/src/heuristics.rs#L257C31-L257C31) and the comments explain what's going on as well as some of the reasoning/decisions

**Comment by rew1nter** [comment]
Hey. No this is not related to the other issue.
I just fired off another scan before commenting here. I'm seeing paths like:
```
/account
/oauth
/e
/s/
/5acab48dfbaf49b5bcf77d77a5edfae5
```
I assume the last one is also from feroxbuster intentionally along with the other like `.admin` and `.htaccess`. None of these are present in my wordlist.

**Comment by epi052** [comment]
correct, the last one is part of the heuristic check for determining 404s.

Could you take a look at the `/robots.txt` for your target? Those paths may be coming from there.

**Comment by rew1nter** [comment]
You're right. `/account` and `/oauth`  is in the robotx.txt of my target. I ran it across a large list so I can't confirm the other two

**Comment by epi052** [comment]
morning! i just wrote a test to see whether or not `--dont-extract-links` controls requests to `/robots.txt`.

both in the code and in my test, `/robots.txt` is not requested when `--dont-extract-links` is used. Can you confirm that's the behavior you're seeing? The relevant code is below and requests for `/robots.txt` is gated behind the check for `extract_links`.

```rust
        if self.handles.config.extract_links && matches!(self.order, ScanOrder::Initial) {
            // check for robots.txt (cannot be in sub-directories, so limited to Initial)
            let mut extractor = ExtractorBuilder::default()
                .target(ExtractionTarget::RobotsTxt)
                .url(&self.target_url)
                .handles(self.handles.clone())
                .build()?;

            let result = extractor.extract().await?;
            extraction_tasks.push(extractor.request_links(result).await?)
        }
```

**Comment by epi052** [comment]
doing some housekeeping, feel free to reopen if this is still an issue.
