### ISSUE TITLE
[BUG] Results generated from the --collect-backups flag do not get filtered

### ISSUE THREAD

**Issue by devx00** [epi052/feroxbuster#1012]
**Describe the bug**
When scanning with the `--collect-backups` flag, or any other flag that implicitly sets that flag i.e. `--smart`, the results for the potential backup files do not get filtered. Is this intentional behavior?

**To Reproduce**
1. Initiate a scan with `--collect-backups`
2. Wait for a path to match your search.
3. See the results for the potential backup files appear in results even if they match a filter.

**Expected behavior**
I expected them to not appear in results if they matched a filter.

**Additional context**
I believe I tracked down the behavior to this section of the code below. Shouldn't there be a call to `should_filter_response` before calling `process_response`? 

https://github.com/epi052/feroxbuster/blob/bc486ac8d3538bb4a7efcd1c90ce9c44deca8148/src/event_handlers/outputs.rs#L323-L336

This is my first time looking at the codebase so I may be completely wrong but thats what I think I was able to determine after about 15 minutes looking around for how the filtering works elsewhere.

**Comment by epi052** [comment]
howdy and thanks for submitting this! it looks like we should probably add that call to the function. likely the omission just stems from this function growing in scope over time from its original purpose. 

We should be able to access the `FeroxFilters` struct from `self.handles.filters...`

nice catch!

**Comment by epi052** [comment]
if you feel like building from source, you should be able to add the following and see if it fixes the behavior (disclaimer: i wrote it without much thought for consequences)

```rust
                    if self
                        .handles
                        .as_ref()
                        .unwrap()
                        .filters
                        .data
                        .should_filter_response(&ferox_response, tx_stats.clone())
                    {
                        // response was filtered, don't process it
                        continue;
                    }
```

**Comment by devx00** [comment]
Sweet thanks. I might end up doing that tomorrow. Thanks for the quick response!

**Comment by epi052** [comment]
ill push a bugfix soon, but in the meantime, feel free to give it a try (if you do, lmk how it goes)

**Comment by epi052** [comment]
@all-contributors add @devx00 for bug
