### ISSUE TITLE
Filtered extensions specified, but still displayed

### ISSUE THREAD

**Issue by wkend** [epi052/feroxbuster#1018]
**Describe the bug**
Filtered extensions specified, but still displayed

**To Reproduce**
![image](https://github.com/epi052/feroxbuster/assets/37563697/1b7a51a0-c5e1-4f55-8dfc-13985420ac2b)

**Comment by epi052** [comment]
morning!

`-I` only filters the extensions that are "collected" when seen by ferox. If you want to never see those extensions come through at all, you'd want to use something like `--filter-regex .(png|jpg|mp3|mp4)$`. 

Judging by the path to those files (.../assets/...png), i'm guessing that they're getting extracted from the html/javascript and requested that way. You could confirm this by passing `--dont-extract-links`. 

Let me know if all this makes sense. Happy to explain further if needed or if there are still problems! 

as an aside, the extensions you provided are already ignored by default. Here is the list of what's ignored without `-I`:
```
[
    "tif", "tiff", "ico", "cur", "bmp", "webp", "svg", "png", "jpg", "jpeg", "jfif", "gif", "avif",
    "apng", "pjpeg", "pjp", "mov", "wav", "mpg", "mpeg", "mp3", "mp4", "m4a", "m4p", "m4v", "ogg",
    "webm", "ogv", "oga", "flac", "aac", "3gp", "css", "zip", "xls", "xml", "gz", "tgz",
];```

**Comment by PanagiotisDrakatos** [comment]
I am still having the same problem that @DaddyBigFish mentioned above. @epi052 Do we have any solution for this? i use this` --filter-regex .(min|gif|js|css|png|jpg|mp3|mp4)$` but still show file with those extensions
