### ISSUE TITLE
Filter suffixes such as css js and so on

### ISSUE THREAD

**Issue by sdfdfasd12** [epi052/feroxbuster#1028]
![image](https://github.com/epi052/feroxbuster/assets/144324900/6b14b574-6f59-47b9-9507-27e306dc9ecf)

**Comment by epi052** [comment]
https://epi052.github.io/feroxbuster-docs/docs/examples/deny-list/

**Comment by epi052** [comment]
assuming the link was helpful; please reopen if needed
