### ISSUE TITLE
[FEATURE REQUEST] add new backup extensions

### ISSUE THREAD

**Issue by Mister7F** [epi052/feroxbuster#1029]
Here, we added a new option `--collect-backups` https://github.com/epi052/feroxbuster/issues/489

But the list of extensions used to discover backups can not be customized: https://github.com/epi052/feroxbuster/blob/d805e464742403e1f78c212c556ffa6ab149748f/src/event_handlers/outputs.rs#L403

It would be nice to be able to add more extensions to that list, with an option `--backup-extension` (I had a CTF where the extension was `.save` for some reason).

**Comment by epi052** [comment]
i think this is a pretty reasonable request, thanks for putting it in!

instead of a new option, I updated `--collect-backups` to accept values in place of the defaults

**Comment by epi052** [comment]
@all-contributors add @Mister7F for idea
