### ISSUE TITLE
[BUG] Scan exits before all jobs are finished.

### ISSUE THREAD

**Issue by devx00** [epi052/feroxbuster#1030]
**Describe the bug**
Feroxbuster will exit early despite some jobs still being in process. It appears to happen when the remaining jobs were all added manually through the in-scan management menu.

**To Reproduce**
1. Start a scan
2. When the remaining jobs are around 50% complete pause the scan and enter the scan management menu.
3. Add a few (3 in my reproductions case) paths/urls to scan via the scan management menu in quick succession.
4. When the manually added jobs are the only remaining jobs, the scan exits without completing them.

**Expected behavior**
The scan should have finished all jobs.

**Environment (please complete the following information):**
 - feroxbuster version: feroxbuster 2.10.1
 - OS Kali rolling up-to-date

## Update

Additional Info:

- It doesn't seem to occur when `--dont-extract-links` is set. 
- The master progress bar seems to show the correct percent completion until it suddenly jumps to the end upon the completion of the automatically created jobs.

**Comment by epi052** [comment]
i ran a few tests and can't repro the issue. Are you able to consistently trigger this bug?

**Comment by devx00** [comment]
> i ran a few tests and can't repro the issue. Are you able to consistently trigger this bug?

Ya I can consistently reproduce it with very specific steps. My original repro steps weren't enough to reproduce it though. I think the issue may only arise under some specific circumstances. 

I'll edit my repro steps to include the specific steps I took but I am not even sure the steps alone are enough to reproduce it. For all I know the response of the specific target may be involved as well since so far I have only reproduced it with the exact scan parameters and actions as when I initially experienced the bug.

**Comment by epi052** [comment]
Nice! If the responses matter, and you're able to, capture them and strip out any sensitive info. We can mock up a server with them

**Comment by epi052** [comment]
i may have stumbled across this today and fixed it. I'll link the PR for testing once it's up.

**Comment by epi052** [comment]
give this branch a try with your configs and see if we caught it

https://github.com/epi052/feroxbuster/pull/1035

**Comment by epi052** [comment]
if this doesn't fix what you're seeing, we should probably audit event handlers for cases where a `?` is causing the handler's thread to exit prematurely.

**Comment by epi052** [comment]
@devx00 just checking back to see if you had a chance to try this

**Comment by devx00** [comment]
> @devx00 just checking back to see if you had a chance to try this

Oh man somehow I missed all those other comments. I have not had a chance to test it. I might have some time in a little bit to pull the branch and test it against the same target it was using before. Hopefully I described it well enough for me to repro it following my own instructions.

**Comment by epi052** [comment]
@devx00 it's no problem at all. that branch was merged, you can just give it a shot from main. thank you (also, no hurry)!

**Comment by epi052** [comment]
closing this one as fixed. if that's not the case, feel free to reopen

**Comment by epi052** [comment]
@all-contributors add @devx00 for bugs

**Comment by epi052** [comment]
thought so, good bot
