### ISSUE TITLE
[BUG] Feroxbuster sends specified cookie or header to Github when checking for latest release

### ISSUE THREAD

**Issue by stuhlmann** [epi052/feroxbuster#1031]
**Describe the bug**
When specifying a custom cookie (-b "SESSION=somesession") or header (-H "Authorization: Bearer <token>"), feroxbuster includes it in its first request to check for the latest release of feroxbuster (at https://api.github.com/repos/epi052/feroxbuster/releases/latest).

**To Reproduce**

**A) Sending a cookie**
1. Run the command `feroxbuster --proxy http://127.0.0.1:8080 -u https://example.com -k -b "SESSION=somesession"`
2. Observe the request in a proxy listening on port 8080.

Request:
```
GET /repos/epi052/feroxbuster/releases/latest HTTP/2
Host: api.github.com
Cookie: SESSION=somesession
Accept: */*
User-Agent: feroxbuster/2.10.1
```

Response:
```
HTTP/2 200 OK
[...]
```

**B) Sending a header**
1. Run the command `feroxbuster --proxy http://127.0.0.1:8080 -u https://example.com -k -H "Authorization: Bearer <token>"`
2. Observe the request in a proxy listening on port 8080:

Request:
```
GET /repos/epi052/feroxbuster/releases/latest HTTP/2
Host: api.github.com
Accept: */*
User-Agent: feroxbuster/2.10.1
Authorization:  Bearer <token>
```

Response:
```
HTTP/2 401 Unauthorized
[...]
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

The behavior has 2 problems:
1. It leaks potentially confidential data (token, cookies) to Github.
2. The check for latest release fails when an incorrect bearer token is included in the Authorization header.

**Expected behavior**
The check for latest release must not include any specified cookies, headers, parameters, user agent, etc.

**Environment (please complete the following information):**
 - feroxbuster version: 2.10.1
 - OS: Kali Linux 2023.3

**Comment by epi052** [comment]
Howdy! Thanks for the submission. I confirmed this and wholeheartedly agree it should be addressed. It shouldn't take too long, it's a pretty minimal change.

**Comment by epi052** [comment]
@all-contributors add @stuhlmann  for bug
