### ISSUE TITLE
[BUG] error: thread 'tokio-runtime-worker' panicked at .../into_url.rs a parsed Url should always be a valid Uri: InvalidUri(TooLong)

### ISSUE THREAD

**Issue by dirhamgithub** [epi052/feroxbuster#1049]
This error is facing me after i have provided the url and word list it finds for me some hidden pages and then it throws me this error, I don't know if the websites made this url to prevent from finding thier hidden files or it is just from Feroxbuster tool.
Here is a screenshot of the error:

![feroxbuster](https://github.com/epi052/feroxbuster/assets/115349974/148c92d1-4360-4e69-8e1e-8d3383418170)

**Comment by epi052** [comment]
sorry for the late reply, didn't see this one. 

that looks to be coming from a library that ferox relies on to do url parsing. at best, id be able to check to make sure we don't trigger the underlying core dump... 

thanks for the bug report! ill take a look at a fix

**Comment by epi052** [comment]
ok, following up on this: the underlying library has a pull request to turn this [panic into an `Error`](https://github.com/seanmonstar/reqwest/pull/2040). Once that lands, i can make sure i handle the `Error` (it may already be handled cleanly, if not ill update).

for anyone wondering, the max URI length is `u16::MAX` or 65,535. In the meantime @dirhamgithub you can use `--dont-scan` to prevent that particular folder from being scanned OR if the url is being picked up during link extraction, you can try `--dont-extract-links`. Happy hunting!

pinning this til i get an upstream fix

**Comment by amiremami** [comment]
Hey, thanks for the interesting tool. I installed feroxbuster for the first time today. I tried it on 3 different domains, and for all of them I got the error. It seems feroxbuster is not functional at the moment, am I right?

![image](https://github.com/epi052/feroxbuster/assets/15929497/74b61397-6f2d-417e-812c-41e26a8aa4ab)

**Comment by epi052** [comment]
@amiremami no, that's not correct. you're encountering what i consider an edge case. that you found it on three separate targets is pretty impressive to me, lol. parsing a url over 65,535 characters is not what i would consider the norm. 

at any rate, thank you for pinging this thread. the upstream fix was merged and i can push a fix for this on my end. expect an update soon!

**Comment by epi052** [comment]
@all-contributors add @amiremami and @dirhamgithub for bug

**Comment by epi052** [comment]
https://github.com/all-contributors add @dirhamgithub for bug

**Comment by epi052** [comment]
@all-contributors add @dirhamgithub for bug

**Comment by epi052** [comment]
fixed in main, new release soon

**Comment by amiremami** [comment]
> fixed in main, new release soon

Thanks a lot, it works now 🙏
