### ISSUE TITLE
[BUG] Could not connect to https://0a90009204b7721482277bd300810014.web-security-academy.net/, skipping... 

### ISSUE THREAD

**Issue by cococristo** [epi052/feroxbuster#1059]
Hi, I am currently doing a lab course in which I should use a Feroxbuster to search for endpoints, and when I try to scan, an error occurs.

1. put a command:
/feroxbuster -u https://0a90009204b7721482277bd300810014.web-security-academy.net/ -w common.txt

with a wordlist from the https://github.com/danielmiessler/SecLists/blob/master/Discovery/Web-Content/common.txt repository

It should show me the available vulnerable endpoints

**Traceback / Error Output**
could not connect to https://0a90009204b7721482277bd300810014.web-security-academy.net/, skipping...
  => error sending request for url (https://0a90009204b7721482277bd300810014.web-security-academy.net/): http2 error: connection error received: connection established in response to a CONNECT request was reset or abnormally closedERROR: Could not connect to any target provided
![image](https://github.com/epi052/feroxbuster/assets/157145343/bf0cb4ad-d908-4b99-abd9-7f821c33b68d)

 - OS Parrot 5.3
 - Kernel: Linux 6.1.0-1parrot1-amd64
 OS is on persistent live made on USB pendrive,  connecting to Internet via WiFi

**Comment by epi052** [comment]
hey there!

i just tested `2.10.1` against my own instance of one of the web academy sites and it worked as expected. Which lab in particular were you working on?

```
 🦡  User-Agent            │ feroxbuster/2.10.1
 💉  Config File           │ /home/epi/.config/feroxbuster/ferox-config.toml
 🔎  Extract Links         │ true
 🏁  HTTP methods          │ [GET]
 🔃  Recursion Depth       │ 4
───────────────────────────┴──────────────────────
 🏁  Press [ENTER] to use the Scan Management Menu™
──────────────────────────────────────────────────
404      GET        1l        2w       11c Auto-filtering found 404-like response and created new filter; toggle off with --dont-filter
200      GET      497l     3031w   340269c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/image/productcatalog/products/5.jpg
200      GET        4l       27w     1041c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/resources/images/rating3.png
200      GET      527l     2714w   284600c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/image/productcatalog/products/39.jpg
200      GET        3l       15w      979c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/resources/images/rating1.png
200      GET      417l     2607w   279603c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/image/productcatalog/products/45.jpg
200      GET      455l     2787w   300027c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/image/productcatalog/products/58.jpg
200      GET      309l     1858w   233538c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/image/productcatalog/products/28.jpg
200      GET        3l       18w      812c https://0a4000dd03bc64c58399fab300240063.web-security-academy.net/resources/images/rating5.png```

**Comment by epi052** [comment]
closing; assuming you got straightened out. if not, please reopen
