### ISSUE TITLE
thread 'main' panicked 

### ISSUE THREAD

**Issue by manugramm** [epi052/feroxbuster#1060]
thread 'main' panicked at 'Could not rebuild client: invalid HTTP header name', src/config/container.rs:991:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'feroxbuster -u https://www.reducte…' terminated by signal SIGABRT (Abort)

**Comment by epi052** [comment]
howdy! what header did you try to supply?

**Comment by manugramm** [comment]
-H 'authority: www.reducted.com' -H 'accept: */*' -H 'accept-language:
en-US,en;q=0.5' -H 'content-length: 0' -H 'cookie:
B2BS=QB4xxxxxFBBbgnTnqslkhxxxxxxxxlmbJyzyCCnMJ%2xxxxxxxBVviBTMlmFhGZle294CdjeQs5lBYYR2ZphPRGLCjcjsvhxxxxxOVw6AXDyAhk%2BNyooaV3TPqxeDvxxxxxxU92IN2Kr%2BvM7OkO8nOYcZxEscWLzTxxxxxxxxxxxxxxxarIhYyjlHEkv0UEbBsjCt2G4bNiFjI50YK3xge347MeYXkm6luJ1U45cwaFHj%2BDOb3BiiZRX7eciexxxxxxxxxxxxx90EgPF5ij%2FzWdoMVmd43IOmsxNvV2NDxcaxgxxxxxxxxxxxxxxxxxxxxxqVw%3D%3D;
bto_balance=0.00; keyofcookie=valueofcookie' -H 'origin:
https://www.reducted.com' -H 'referer: https://www.reducted.com/' -H
'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Brave";v="120"' -H
'sec-ch-ua-mobile: ?0' -H 'sec-ch-ua-platform: "Linux"' -H 'sec-fetch-dest:
empty' -H 'sec-fetch-mode: cors' -H 'sec-fetch-site: same-origin' -H
'sec-gpc: 1' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' -H
'x-csrf-token: 2af23b0423cd4dad5adbfc64914xxxxxxxxxxxe75f642f6a1ee2c' -H
'x-requested-with: XMLHttpRequest'

**Comment by epi052** [comment]
fixed. you should be able to grab a new binary from the link below in a few minutes

https://github.com/epi052/feroxbuster/actions/runs/7596898019

**Comment by epi052** [comment]
@all-contributors add @manugramm for bugs

**Comment by epi052** [comment]
feel free to reopen if it's not truly fixed

**Comment by manugramm** [comment]
Thanks
