### ISSUE TITLE
[BUG] SHA256 mismatch for MacOS

### ISSUE THREAD

**Issue by 20backslash** [epi052/feroxbuster#108]
**Describe the bug**
Using the 2 provided commands to install on Mac gives a SHA256 mismatch

**To Reproduce**
1. brew tap tgotwig/feroxbuster
2. brew install feroxbuster

**Expected behavior**
A successful install 

**Traceback / Error Output**
brew install feroxbuster                                                                                                 
Updating Homebrew...
==> Installing feroxbuster from tgotwig/feroxbuster
==> Downloading https://raw.githubusercontent.com/epi052/feroxbuster/master/ferox-config.toml.example
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 70ace4e70c7f532cc4f7e7958106d035c62bd9d12a6a91de433b815f607911ba
Actual: d53171328e75472612470e337ec374376ede56631d12129aecb1cd29fefb69b8

**Environment (please complete the following information):**
 - feroxbuster version: [ v1.4.0]
 - OS [mac OS Catalina 10.15.7]

**Comment by epi052** [comment]
Thanks for the report!  

I just updated both Mac and Linux taps to reflect the new hash (`d53171328e75472612470e337ec374376ede56631d12129aecb1cd29fefb69b8`).  I forgot to update the config hash when it changed in 1.3.0.  Marking as closed.  Thanks again!
