### ISSUE TITLE
[BUG] deb file seems not in Releases section

### ISSUE THREAD

**Issue by FieldOfRice** [epi052/feroxbuster#1080]
**Describe the bug**
Calling `curl -sLO https://github.com/epi052/feroxbuster/releases/latest/download/feroxbuster_amd64.deb.zip` has a 404 error.

**To Reproduce**
1. curl -sLO https://github.com/epi052/feroxbuster/releases/latest/download/feroxbuster_amd64.deb.zip
2. cat feroxbuster_amd64.deb.zip
3. Not Found

**Expected behavior**
The expected file feroxbuster_amd64.deb.zip could be downloaded,
could be unpacked with `unzip`,
does not only contains the executable, but all other needed files/folders like /usr/share/seclists/Discovery/Web-Content/...

**Traceback / Error Output**
see **To Repoduce** at 3.

**Environment (please complete the following information):**
 - followed the apt install path inside debin bookworm

**Additional context**
./.

**Comment by epi052** [comment]
there's one here, give this a shot and lmk how it goes

https://github.com/epi052/feroxbuster/actions/runs/8019324006

**Comment by FieldOfRice** [comment]
Meanwhile got it running using a different approach through using docker, see below.
Took me some time to find that word/directory file, seems i followed the wrong path ...

# Dockerfile:
```
FROM alpine:3.17.1 as build
RUN apk upgrade --update-cache --available && apk add --update openssl
RUN wget https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip -qO feroxbuster.zip \
    && unzip -d /tmp/ feroxbuster.zip feroxbuster \
    && chmod +x /tmp/feroxbuster \
    && wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-medium-directories.txt -O /tmp/raft-medium-directories.txt
FROM alpine:3.17.1 as release
COPY --from=build /tmp/raft-medium-directories.txt /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt
COPY --from=build /tmp/feroxbuster /usr/local/bin/feroxbuster
RUN adduser \
    --gecos "" \
    --disabled-password \
    feroxbuster
USER feroxbuster
ENTRYPOINT ["feroxbuster"]
```
# build script

```
#!/bin/bash
DOCKER_BUILDKIT=1 docker image build -t abc/http-feroxbuster:1.0.0 .
```
# run script

```
#!/bin/bash
# docker run --rm -it --network host abc/http-feroxbuster:1.0.0 --url http://192.168...:8080/ --rate-limit 5 --scan-limit 1 # -q
docker run --rm -it --network host abc/http-feroxbuster:1.0.0 --url http://192.168...:8080/ --auto-tune
```

**Comment by epi052** [comment]
@all-contributors add @FieldOfRice for infra
