### ISSUE TITLE
Can't Open Wordlist

### ISSUE THREAD

**Issue by spacezero20** [epi052/feroxbuster#1085]
I am running this on Windows, and am having an issue. 

I ran

 ./feroxbuster -u https://mergify.com/ -w common.txt
and 

./feroxbuster -u https://mergify.com/ -w Desktop/common.txt

No matter what I do, common.txt won't open and run. It's a simple wordlist text file. What's going on here? How do I fix this?

![common txt-error](https://github.com/epi052/feroxbuster/assets/46658915/d7b64c43-1a79-428b-bc4f-420628c37ad5)

**Comment by epi052** [comment]
howdy! it looks like you're using cygwin or wsl. i'm not a windows user, so can't advise too much further on this setup. can you `cat` common.txt? it looks similar to a container issue where the insdie of the container can't see the outside filesystem. 

are you able to use one of the windows builds?

**Comment by epi052** [comment]
doing some housekeeping, feel free to reopen

**Comment by khabab500** [comment]
move common.txt to your wsl (by any way you can used windows file Explorer or download it to your wsl)

form the directory you move common.txt to it well work
