### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by sdfdfasd12** [epi052/feroxbuster#1115]
errors How to retry, whether to consider adding retries to reduce errors, and if so, whether there are relevant parameters to specify, such as: how many times to retry before giving up.
![image](https://github.com/epi052/feroxbuster/assets/144324900/b3b3c23d-e8f6-428d-ab4d-29a806bca228)

**Comment by epi052** [comment]
USUALLY those errors are from the webserver being overloaded. There aren't any options to retry error'd requests at the moment. `--auto-tune` is the closest option to automatically adjust the speed based on error rate. Other than that, you can manually tune the speed until you stop seeing errors

**Comment by epi052** [comment]
closing this for now. please reopen if you still have other questions
