### ISSUE TITLE
[FEATURE REQUEST] Include Raw Request instead of Headers

### ISSUE THREAD

**Issue by Raymond-JV** [epi052/feroxbuster#1116]
**Is your feature request related to a problem? Please describe.**
Many other tools like ffuf and sqlmap provide a raw request option, which makes transferring a session from a browser or tool like burp suite less error prone, and saves a lot of time.

**Describe the solution you'd like**
Provide a --request flag that automatically retrieves the user-agent, headers, cookie, and other attributes from a raw HTTP request.

**Describe alternatives you've considered**
Creating my own wrapper script that includes the data with a custom flag.

**Additional context**
I would be open to working on this feature if you consider it useful.

**Comment by epi052** [comment]
hi @Raymond-JV! sorry for the late reply. I'd happily work with you to get this included as a feature if you'd like to work ont it. Just let me know. Pinning for now

**Comment by epi052** [comment]
hey @Raymond-JV, just merged this in. Give it a try and lmk what you think!

https://epi052.github.io/feroxbuster-docs/docs/examples/raw-request/

**Comment by epi052** [comment]
@all-contributors add @Raymond-JV for ideas

**Comment by Raymond-JV** [comment]
Apologies for not reaching out sooner, I have been fairly inactive on GitHub.

The feature works really well. Thank you for making this tool more compatible with raw requests and Burp.
