### ISSUE TITLE
[FEATURE REQUEST] Improved POSTs requests (2): automatic POST HTTP verb when using --data

### ISSUE THREAD

**Issue by JulianGR** [epi052/feroxbuster#1118]
Sister issue with https://github.com/epi052/feroxbuster/issues/1117

### **FEATURE REQUEST 2: automatic POST HTTP verb when using --data**
**Is your feature request related to a problem? Please describe.**

When using the `--data` flag to add data to the body of the request, the HTTP verb that remains is GET (default). Everytime I use `--data` flag, has to be used together with `-m POST`

**Describe the solution you'd like**

I'd like that, when using `--data` flag, the HTTP verb automatically updates to POST. Also, `-m` will now only accept POST or PUT. As far as I'm concerned, GET requests are allowed to have body, but the server parses them useless.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by epi052** [comment]
howdy!

this is an easy fix and makes sense to me. i'm going to add this into a PR i already have in progress. thanks!

**Comment by JulianGR** [comment]
nice, thank you!

**Comment by epi052** [comment]
It's not merged yet, but will be this week likely

**Comment by JulianGR** [comment]
ooops sorry

**Comment by epi052** [comment]
@all-contributors add @JulianGR  for ideas
