### ISSUE TITLE
[BUG] Mishandling of whitespace for supplied request headers

### ISSUE THREAD

**Issue by soutzis** [epi052/feroxbuster#1122]
**Describe the bug**
When manually supplying headers (`-H` option) for a scan, feroxbuster does not gracefully handle whitespace and will add one (1) additional whitespace character after the `Host:` prefix.

**To Reproduce**
Start a scan while supplying the host header with the `-H` flag. You can capture the request with your proxy server and observe that there will always be n+1 whitespace characters, where n is the amount of whitespace characters supplied by the user.

**Expected behavior**
Ideally, the excess whitespace should be stripped. When no whitespace is provided, the tool **correctly** adds a whitespace character and that functionality should be preserved.

**Traceback / Error Output**
![image](https://github.com/epi052/feroxbuster/assets/25797286/19f65806-54be-4d61-88a1-170f5a462088)
The above command shows that 1 space is added after the `Host` HTTP header, as is normally expected.

![image](https://github.com/epi052/feroxbuster/assets/25797286/66d944a5-1031-46cc-9cbc-bb19e5057335)
The screenshot shows (highlighted in red) that an additional whitespace character is added.

**Environment (please complete the following information):**
 - Feroxbuster 2.10.2 (bug observed in previous versions as well)
 - Windows 11

**Comment by epi052** [comment]
howdy and thanks for submitting!

is it only the host header?

**Comment by soutzis** [comment]
Just checked, it seems that it's all headers added manually.
![image](https://github.com/epi052/feroxbuster/assets/25797286/68fc13a6-f95f-4862-aa39-650471ef5411)
![image](https://github.com/epi052/feroxbuster/assets/25797286/a83e3403-6772-4de2-b648-2f07a8e4c95e)

**Comment by epi052** [comment]
Yea, I jumped the gun asking. It's an easy fix, I'm just trying to set it up to handle this case specifically and still allow for intentional leading whitespace

**Comment by epi052** [comment]
@all-contributors add @soutzis  for bug
