### ISSUE TITLE
[FEATURE REQUEST] Add the option for including a custom suffix in URLs

### ISSUE THREAD

**Issue by soutzis** [epi052/feroxbuster#1123]
**Is your feature request related to a problem? Please describe.**
I have been testing multiple applications for the past week that are based on JavaServer Faces (JSF). Since these applications use state changes to determine what should be viewed to the front end, there are usually not many files/directories to discover. However, they usually have a specific suffix on every request, such as `.xhtml`.

**Describe the solution you'd like**
An option to add a custom suffix to each request. In the same way that we can use `-f` to add a trailing '/', it would be nice to be able to specify a custom suffix.

**Describe alternatives you've considered**
The only way I can achieve this, is to manually edit the wordlists I use and replace the suffixes myself.

**Comment by epi052** [comment]
howdy! It sounds like you're looking for the following option
```
  -x, --extensions <FILE_EXTENSION>...
          File extension(s) to search for (ex: -x php -x pdf js); reads values (newline-separated) from file if input starts with an @ (ex: @ext.txt)
```

**Comment by soutzis** [comment]
Ah, thanks for pointing me in the right direction. Cheers, closing!
