### ISSUE TITLE
[BUG] Internet slow down after using feroxbuster

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [epi052/feroxbuster#1124]
**Describe the bug**
For some reason when I use feroxbuster with `10 threads` or less my internet connection slows down up until the point I need to reboot the router

**To Reproduce**
1. Start feroxbuster with 10 threads
2. Watch internet slow down
3. Check that its no longer possible to open internet pages
4. Reboot router and stop feroxbuster

**Expected behavior**
Its expected to not break the internet even by using a small amount of threads

**Environment (please complete the following information):**
 - feroxbuster version: feroxbuster 2.10.2
 - OS: Debian 12

**Comment by epi052** [comment]
This sounds like an issue with your router, no? Or are you saying that a higher number of threads doesn't cause this behavior?

**Comment by epi052** [comment]
so, when you experience this behavior, are there a bunch of directories all being scanned at the same time? Each directory is effectively its own scan, with its own threads, limits, etc... 

you can use `--scan-limit 1` to limit the scan to a single directory at a time. Further, you can limit the rate of requests per second with `--rate-limit 100` 

[further rate limiting documentation](https://epi052.github.io/feroxbuster-docs/docs/examples/rate-limit/)
[further scan limiting documentation](https://epi052.github.io/feroxbuster-docs/docs/examples/limit-scans/)

**Comment by epi052** [comment]
closing this for now (housekeeping). feel free to reopen it to continue the conversation!

**Comment by BrunoTeixeira1996** [comment]
@epi052 you can close this, looks like its already fixed!
