### ISSUE TITLE
[FEATURE REQUEST] Filter by redirect destination or response header

### ISSUE THREAD

**Issue by sa7mon** [epi052/feroxbuster#1141]
**Is your feature request related to a problem? Please describe.**
When busting a certain URL, it will frequently redirect to a "maintenance" page. The Ferboxbuster output looks like this:

```
301      GET        0l        0w        0c https://example.com/WEB_2011 => https://example.com/pages/maintenance.html
301      GET        0l        0w        0c https://example.com/1024x768 => https://example.com/pages/maintenance.html
301      GET        0l        0w        0c https://example.com/1280x800 => https://example.com/pages/maintenance.html
301      GET        0l        0w        0c https://example.com/1440x900 => https://example.com/pages/maintenance.html
```

**Describe the solution you'd like**
An option to filter either by the 301 destination or by arbitrary response headers. I'd still like to see redirects to other pages in the output, but filter out redirects to specific pages.

**Describe alternatives you've considered**
I tried `--filter-similar-to`, but that compares the body of the filtered page with the body of the busted page which will not be similar since the busted page has no response body. Likewise, the `--filter-regex` flag also compares only the response body

**Comment by epi052** [comment]
howdy, and thanks for submitting!

i agree that there's no built-in way to do what you're after. I don't like the idea of filtering by redirect location (pretty sure i turned down a similar proposal a while back). 

On the other hand, filtering by headers, or modifying --filter-regex to include headers seem like reasonable changes that are generic enough to be useful to more than a single usecase.

**Comment by epi052** [comment]
there's a debug build here (untested), lmk how it does. you should be able to `--filter-regex` on headers


https://github.com/epi052/feroxbuster/actions/runs/9047212741

**Comment by sa7mon** [comment]
I'm a bit embarrassed to say, but I can't find the subdomain I was busting at the time when I created this issue so I'm not able to test it out but if the functionality works I'd say merge it!
Thank you for such a quick turnaround.

**Comment by epi052** [comment]
this will be live in 2.10.4 :tada:
