### ISSUE TITLE
[FEATURE REQUEST] Flag to purge finished progress lines

### ISSUE THREAD

**Issue by L1-0** [epi052/feroxbuster#1144]
**Is your feature request related to a problem? Please describe.**
When scanning a server with many directories the terminal output becomes polluted with finished tasks to the point where one cannot see the main progress any more. 

**Describe the solution you'd like**
My suggestion would be to either introduce a flag to keep the finished tasks in the console, or a flag to automatically purge finished scans from the output. Either way would be good. An easy fix for the problem would be to print the finished scans first, then the global scan progress and then the currently running scans, that way you can still see the progress at least.

**Describe alternatives you've considered**
None, as after a 15h scan all i could see was a flashing terminal window with finished scans, with no progress display whatsoever.

**Comment by epi052** [comment]
hey there, thanks for the suggestion! I am merging in `--limit-bars`, which (i think) satisfies this request. Feel free to reopen if not. 

https://epi052.github.io/feroxbuster-docs/docs/examples/limit-bars/

**Comment by epi052** [comment]
@all-contributors add @L1-0 for ideas
