### ISSUE TITLE
[BUG] Time estimation goes to 0s and never recovers

### ISSUE THREAD

**Issue by L1-0** [epi052/feroxbuster#1145]
**Describe the bug**
In the global scan progress line the time estimation goes to 0s after a time of the program running.

**To Reproduce**
This bug should be automatically reproducible. I have witnessed it in the following scenarios:
A scan finishes and another concurrent scan takes its place.
You open the Scan Management Menu and add a manual additional url to scan.

**Expected behavior**
The total time estimator should output the estimated time. Instead it is displaying "0s"

**Traceback / Error Output**
[##############>-----] - 45m   104568/140835  >>> 0s <<<      found:12      errors:0

**Environment (please complete the following information):**
 - feroxbuster version: [e.g. v2.10.2]
 - OS [e.g. kali, feroxbuster manually updated]

**Additional context**
![console output](https://github.com/epi052/feroxbuster/assets/123986259/ad513263-ec1f-4160-bbbc-84f88b1f9b57)

**Comment by epi052** [comment]
thanks for this! i was able to reproduce it by adding a scan in the menu. going to take a look at this today and see what's going on
