### ISSUE TITLE
[FEATURE REQUEST] Add a flag to automatically path traverse every directory level

### ISSUE THREAD

**Issue by L1-0** [epi052/feroxbuster#1146]
**Is your feature request related to a problem? Please describe.**
When a linked local resource is found, feroxbuster automatically adds its containing path to the scan queue. 
For example we have a linked resource of:
https://target.local/adminUI/ressources/includes/secrethive.json on https://target.local/index.php
AFAIK (please correct me) only https://target.local/adminUI/ressources/includes/ gets added to the scan queue.
but what is about the following, where each of them could have their own set of findings:
https://target.local/adminUI/ressources/
https://target.local/adminUI/

**Describe the solution you'd like**
A flag to automatically parse links into their parts and add each path level to the scan queue if it wasn't in there before.

**Describe alternatives you've considered**
Manually adding links is quite exhausting.

**Comment by epi052** [comment]
Howdy, and thanks for reaching out! This should be happening already. Can you run it through burp or similar and verify it is or isn't? This has been the expected behavior since I added link parsing, so if it's not working as I intended we may ha e a bug.

**Comment by epi052** [comment]
since this functionality is implemented [here](https://github.com/epi052/feroxbuster/blob/main/src/extractor/container.rs#L425), i'm going to assume this issue is invalid.

if you confirm that ferox is misbehaving (i.e. not adding those subpaths), please reopen the issue and we can discuss.
