### ISSUE TITLE
[FEATURE REQUEST] Functionality to add relative paths in Scan Management Menu

### ISSUE THREAD

**Issue by L1-0** [epi052/feroxbuster#1147]
**Is your feature request related to a problem? Please describe.**
Instead of always resorting to adding the full url like `a[dd] https://target.local/adminUI/common/test123/`
it should be possible to add it also like this: `a[dd] /adminUI/common/test123/` 
Feroxbuster would then always consider the base host as the start.
Right now this fails when trying to add a relative url.

**Describe the solution you'd like**
Add relative path parsing to the add function off the Scan Management Menu

**Describe alternatives you've considered**
None

**Comment by epi052** [comment]
in general, i think this is a nice feature. However, it becomes ambiguous when more than one target is present. 

Due to this not being suitable for all use-cases, I'm going to decline this one.
