### ISSUE TITLE
[BUG] There is no ARM Mac OS X release

### ISSUE THREAD

**Issue by wikamp-collaborator** [epi052/feroxbuster#1149]
**Describe the bug**
There is no ARM Mac OS X release. There is only x86_64 release for Mac OS X however Intel Macs are note produced for many years.

**Comment by epi052** [comment]
There are two arm variants. One of them should work on Mac (aarch64 I think). Lmk if neither work

**Comment by sectroyer** [comment]
Here: https://github.com/epi052/feroxbuster/releases/tag/v2.10.3 there is aarch64 and armv7 release for linux but for Mac OS X there is only x86_64

**Comment by epi052** [comment]
Is homebrew an option for you?

https://formulae.brew.sh/formula/feroxbuster

**Comment by sectroyer** [comment]
I don't use home-brew myself but I used cargo so I was able to compile it. However I think it's still good idea to support modern Macs :)

**Comment by epi052** [comment]
Yea, rustup supports it at tier 2 now, I can add a build action for it. Didn't realize it was missing, thanks !

**Comment by sectroyer** [comment]
No problem. Glad I could help 👍

**Comment by epi052** [comment]
added a build step for arm on mac. give it a whirl. if it runs on your machine, ill add the pipeline to the main branch

https://github.com/epi052/feroxbuster/actions/runs/9433072060
