### ISSUE TITLE
[FEATURE REQUEST] Candidate Deduplication

### ISSUE THREAD

**Issue by cmprmsd** [epi052/feroxbuster#1156]
**Is your feature request related to a problem? Please describe.**
When I discover directories *sometimes* the webpage does some redirects that feroxbuster does not see and follow. So I use httpx -fr to create one result line with the main url as well as the redirection target. 
I then split the target into multiple lines according to its folder depthness. 

Example: 
test.com/ is the main url 
test.com/deep/path/xyz/login.html 

It'll create 
test.com/deep/ 
test.com/deep/path/ 
test.com/deep/path/xyz/

When I now pass the new list to feroxbuster, will it deduplicate it's URL candidates or will it recursively traverse each path part multiple times if the words are in a wordlist? 

**Describe the solution you'd like**
When the fuzz candidates get created for subfolders feroxbuster could match all new candidates to already tested candidates in this run before executing the request and omit requests that have already been send to the exact same location in order to omit duplicate requests.

**Comment by epi052** [comment]
ferox keeps track of what it has scanned/not scanned. so, the `deep/path` will be skipped when it's reached by the `deep/` scan and so forth. It's not a deduplication of urls, but it attempts to not duplicate effort/bandwidth/time etc. 

as a side note, ferox should be adding all of those sub-folders to the current scan on your behalf (unless you mean just for those were the redirect gets wonky)

test.com/deep/path/xyz/login.html => test.com/deep/
test.com/deep/path/
test.com/deep/path/xyz/

**Comment by cmprmsd** [comment]
Hey there, thank you for the clarification especially on how intermediate folders are added automatically. 😊 
The wonky redirects are my concern. But then it should be no problem to pass multiple intermediate paths to the scan input. 

Feroxbuster should only call the urls once as far as I understand. 
I'll close the issue. Thanks again 🥳🙏
