### ISSUE TITLE
any one can help me to slove this error ?

### ISSUE THREAD

**Issue by HaCk0r1-cyber** [epi052/feroxbuster#1161]
![Uploading Screenshot_2024-06-08_19_31_11.png…]()

**Comment by HaCk0r1-cyber** [comment]
![Screenshot_2024-06-08_19_31_11](https://github.com/epi052/feroxbuster/assets/122724011/a007304b-5350-4ac0-b046-7c0466d63052)

**Comment by epi052** [comment]
this has happened before, and i couldn't reproduce it. I'm guessing it's some sort of os/env configuration dorking with ferox. 

- https://github.com/epi052/feroxbuster/issues/1059
- https://github.com/epi052/feroxbuster/issues/947

**Comment by epi052** [comment]
feel free to reopen to continue any discussion. closing this for housekeeping
