### ISSUE TITLE
[QUESTION] can i install feroxbuster on parrot os  

### ISSUE THREAD

**Issue by spacezero20** [epi052/feroxbuster#1170]
**Describe the bug**
Unable to locate package when installing via Kali method. I am using Parrot OS. What is going and why can't I install Feroxbuster? Is it truly limited to Kali and not Parrot, or is something else wrong? Can you tell? I am confused.

![feroxfailure](https://github.com/epi052/feroxbuster/assets/46658915/60cb7b86-af01-410a-84f3-f2ccbb897fef)

**Comment by epi052** [comment]
morning! 

i dont use parrot os, but unless they're setup to use kali's repos (which appears to not be the case), you won't be able to use `apt` out of the box to install it.

adding ferox to debian's repos was too much of a headache when i tried. that would have likely allowed you to pull from debian as it's (probably) used as an upstream repo.

your best bet is installing via the bash script or downloading the `.deb` file from the releases page here on the repo.

**Comment by epi052** [comment]
closing this one for now, feel free to reopen if you have additional questions
