### ISSUE TITLE
Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt

### ISSUE THREAD

**Issue by Vx12345678** [epi052/feroxbuster#1183]
错误信息：Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt
<img width="561" alt="image" src="https://github.com/epi052/feroxbuster/assets/105026809/7c193ac0-ba07-4730-9e59-65f8824bcb65">

**Comment by lopya** [comment]
hi man i search on this case you have to chang the path and put this path /mnt/c/Users/your user name/Downloads/name of your wordlist

**Comment by F1oww** [comment]
> 错误信息：Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt错误信息：无法打开 /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/105026809/345312237-7c193ac0-ba07-4730-9e59-65f8824bcb65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzU0MzAsIm5iZiI6MTcyMDMzNTEzMCwicGF0aCI6Ii8xMDUwMjY4MDkvMzQ1MzEyMjM3LTdjMTkzYWMwLWJhMDctNDczMC05ZTU5LTY1Zjg4MjRiY2I2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNjUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2QwYmNjMTJhZDk5YTgxNWIzOWVkMTVjYTQ2ZmU5OTM1Y2Y1MGQ3ZjhhY2NjMzA4ZWFjNzVlMTQwYzU0MmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g2_0mImdtpCrwjhx37grtMHuF5o2LdXUEWFrxW__lQI">

you need to add Path or URL of the wordlist. like this
![dir](https://github.com/epi052/feroxbuster/assets/97645118/312f0d41-4511-4cbe-9029-1b5800fe5d1c)

**Comment by epi052** [comment]
Howdy! See if #724 helps and let me know

**Comment by epi052** [comment]
assuming it helped, or something else did. Please feel free to reopen if not.
