### ISSUE TITLE
[FEATURE REQUEST] -q Flag (same detail, less frequent updates)

### ISSUE THREAD

**Issue by islanddog** [epi052/feroxbuster#119]
**Is your feature request related to a problem? Please describe.**
Nope. Refer to previous post on the love of this script.

**Describe the solution you'd like**
To change (or have a different -q flag) for:
![image](https://user-images.githubusercontent.com/16761753/98454819-b5624900-2136-11eb-81cf-a7ef570d6b40.png)

**Describe alternatives you've considered**
Using `-q` works but I would prefer to have all the information but the time visible. Or to show progress only once it has found a URL or String.

**Additional context**
My reasoning for this is I use TMUX and I have it set to notify me on panes when something appears in the HUD. Useful for notifying me well-running an HTTP server and picking up the request... or doing further enumeration well exploring other ports. Having this feature would mean I would only get a notification when a URL/string was found.

**Comment by epi052** [comment]
So, we meet again... Thanks for the new request!

If I understand this correctly, you're wanting something similar to `--no-status-bars`?  The functionality could be something like 

```
200       253 http://internal-01.bart.htb/LOG/LOG.php
...
Scanning: http://internal-01.bart.htb
Scanning: http://internal-01.bart.htb/LOG
```

The portion you've highlighted isn't the only thing that updates frequently (basically everything in the bars except for the directory falls into this category).

**Comment by islanddog** [comment]
Thanks for the quick response! Yes, something similar which provides updates only when an entry is found. I might be asking the silliest question to date but I tried `--no-status-bars` at the begging, middle, and end of my string and I keep getting errors. Is this meant to be used with only a specific syntax:

![image](https://user-images.githubusercontent.com/16761753/98607539-65f75680-22b7-11eb-8699-eea11998a34d.png)

**Comment by epi052** [comment]
My bad, I could have been more clear.  

I meant that a new flag could be added (`--no-status-bars`) that would essentiallly remove the status bars.  You're correct that it doesn't currently exist. 

Did my summary above seem like it would satisfy the request?

**Comment by islanddog** [comment]
Haha no problem at all. I saw it on another request before you mentioned it and thought it was already implemented. Yes, that would be awesome down the pipe if you could and thanks for your time.

**Comment by epi052** [comment]
Thinking about this, we could do a `-q` that increases in the amount of quiet, similar to how `-v` works.

- `-q` => no status bars, similar to what's proposed above.
- `-qq` => current `-q` behavior where only the results are printed (for use in piped output etc)

Add new command line option checklist
- [ ] config.rs
    - [ ] add new value to `Configuration` struct
    - [ ] update `Configuration::default` with new value
    - [ ] update `Configuration` docstring with the new value/default (if appropriate)
    - [ ] update `Configuration::new` so that the new value is stored in `config`
    - [ ] update `Configuration::merge_config` with new value
    - [ ] update `Configuration::tests::setup_config_test` with new value
    - [ ] add unit test to check config parsing
- [ ] ferox-config.toml.example
    - [ ] add new value to example config
- [ ] banner.rs
    - [ ] add new check for the value in `banner::initialize`
    - [ ] create new entry to be written in the banner for the new value
        - [ ] add new emoji to the entry (should be somewhat related to the value name)
    - [ ] add new integration test (`tests/test_banner`) or update existing so that it's displayed under test
- [ ] Cargo.toml
    - [ ] bump version: add 1 to minor release and set patch release to 0
- [ ] README.md
    - [ ] update default config section (if needed)
    - [ ] update example config file section
    - [ ] update help output section
    - [ ] add an example with a heading that conforms to others (new in `v1.4.0`...)
        - [ ] add an entry for the example in the table of contents
- [ ] parser.rs
    - [ ] add the option to the parser
- [ ] wherever.rs
    - [ ] implement the new feature

**Comment by islanddog** [comment]
Yes, that makes perfect sense above. As in my situation I tend to use TMUX with notification panes running. Having a flag that allows me to get an update when it hits an active link with a running time interval or the current state (25066/40230 from the example above). This would give me the information I need without the constant update of the pane itself.

**Comment by LaiKash** [comment]
> another option: `-q|--quiet` and `--silent` to denote the difference between the two

And how about to have a --silent that do not prompts the error messages?

**Comment by epi052** [comment]
> > another option: `-q|--quiet` and `--silent` to denote the difference between the two
> 
> And how about to have a --silent that do not prompts the error messages?

I'd be ok with that.  I've been thinking about how best to break out the error messages (specifically the ones that can spam the terminal) from the ones that are meaningful.  Know that it's on my mind and something I plan to address.

**Comment by epi052** [comment]
ok, this will be in v2.0.0. 

```
    -q, --quiet            Hide progress bars and banner (good for tmux windows w/ notifications)
        --silent           Only print URLs + turn off logging (good for piping a list of urls to other commands)
```

--quiet output:
```
302        0l        0w        0c https://localhost.com/Login
200      126l      281w     4091c https://localhost.com/maintenance
200      126l      281w     4092c https://localhost.com/terms
... more individual entries, followed by the directories being scanned ...
Scanning: https://localhost.com
Scanning: https://localhost.com/homepage
Scanning: https://localhost.com/api
```

--silent output (also disables ALL logging)
```
https://localhost.com/contact
https://localhost.com/about
https://localhost.com/terms
```
