### ISSUE TITLE
[FEATURE REQUEST] Enable passing Headers from a file

### ISSUE THREAD

**Issue by ghecko** [epi052/feroxbuster#1201]
**Is your feature request related to a problem? Please describe.**
I often encounter frustration when required to specify multiple headers, especially lengthy ones like the Authorization header, directly through the CLI. Updating these headers involves manually removing and re-pasting them each time, which is time-consuming and error-prone. A more efficient approach would allow headers to be passed directly from a file.

**Describe the solution you'd like**
I’d like the ability to pass headers from a file, with each header specified on a separate line. The tool would read and apply each header listed in the file, simplifying the process of updating or adding headers without requiring direct CLI input for each one.

**Describe alternatives you've considered**
I've considered no alternative solutions that achieve the same convenience as file-based header loading.

**Additional context**
N/A

**Comment by epi052** [comment]
howdy!

it's not exactly what you're asking for, but version 2.11.0 added the ability to [scan from a raw http request](https://epi052.github.io/feroxbuster-docs/docs/examples/raw-request/) file e.g. from burp.

**Comment by epi052** [comment]
closing this one since the requested functionality exists in the linked feature. Please fee free to reopen/continue discussion if needed.
