### ISSUE TITLE
[FEATURE REQUEST] Structured log output (JSON lines, ideally)

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#124]
Currently, the output format is line-based, but to parse it, you need to split it based on whitespace separators. This isn't a *huge* problem, but it's not the cleanest way to programmatically analyze with large collections of output files, for the purpose of eliminate "uninteresting" findings- e.g. results that are similarly sized, but not exactly the same- generic responses with some small amount of varing content, like the URL itself, or a unique transaction id or log/error id

It would be great if log output could be written in line-based NDJSON format. This allows for much quicker, cleaner and mistake-free loading of the files into the language of your choice for doing automated analysis on a large set of output files. In python, for example, you can read the lines, use `split()` on them, and then manually name the fields, or keep them as a tuple with the column values in them. It would be preferred to simply load a JSON file. This is especially useful for error conditions, which are a little exceptional in their formatting compared with successful outputs

An alternative of course is just parsing the line-based output using either regex or primitive whitespace splitting- this isn't by any means impossible or even difficult, but it takes some trial and error to handle exceptional lines that may not be common (or you can just ignore these lines)

Just to clarify, I realize this is not something as useful for looking at a single output file as it is for looking at a large collection of outputs from a parallelized batch during a large penetration test that may have output from 1000 or more sites- this use-case is similar to what I described in #123

Thoughts?

Thanks again!

**Comment by epi052** [comment]
Structured logging has been something I've wanted to do, but haven't prioritized yet.

When you do analysis on results from these kinds of scans, do you ever need/want the error output?  I'm assuming you're really only concerned with actual results that haven't been filtered out by one or more options to feroxbuster.

I like being able to put trace/debug output to a file (mostly for me, lol).  That functionality could be moved to a `--debug-log` and the structured logging could be implemented as kind of a dual option thing:

- `--output somefile --output-type json`
- `--output somefile --output-type text`

what do you think?

**Comment by mzpqnxow** [comment]
> Structured logging has been something I've wanted to do, but haven't prioritized yet.

I can relate.. only so much time in a day

> When you do analysis on results from these kinds of scans, do you ever need/want the error output? I'm assuming you're really only concerned with actual results that haven't been filtered out by one or more options to feroxbuster.

Generally I'm not too interested in the *specifics* of the errors- e.g. which exact URL caused an error. Though it's nice to see sometimes if you're running something in the console, just curious about what's going on, and maybe trying to identify a bug or misbehavior. This kind of contradicts the issue I entered in #125 earlier today, but that's mainly because today is my first experience with `feroxbuster` and am just interesting in getting a feel for it and seeing if I can spot anything it's doing well, but could do better with a small change.

As far as tracking errors at a *high* level- especially when running as part of a continuous process, with hundreds or thousands of endpoints, and keeping the data time-serie/snapshot style in a database, with roughly the same collection of inputs- it's very nice to have good tracking of counts/metrics of specific types of errors. This is just for the purpose of comparing them over time. 

Even (or maybe especially) if the error data is just an aggregate/set of metrics dumped at the end of the run- it would be nice to know for each individual scan at its conclusion things like (just from the hip):

```
n requests timed out
n requests had connection refused
n requests encountered a disconnect
n requests encountered invalid SSL protocol data
n requests encountered invalid HTTP protocol data
n requests redirected and had general failure at the redirect
n requests redirected and timed out
n requests redirected fan connection was refused
n requests resulted in status code X
n requests resulted in status code Y
...
```

Probably your reaction to this giant laundry list is "are you nuts?" - to which I kind of wonder the same thing sometimes.... BUT, my philosophy is if you're going to add the infrastructure in the code to track *any* metrics, you might as well track as many as is reasonably possible, unless there are adverse efects. Again though, keep in mind, my ideas here come very much from the perspective of running `feroxbuster` as more of an active snapshot/monitoring tool than as a one off recon/sweep tool against a specific (and usually different) set of targets each time. I keep the output from the tools I use for this process indefinitely and after a while it often becomes possible to mine interesting data from things that (in isolation) seem to be just pedantic or noisy

Another thing that I think is important (sorry, I wrote this before reading your next question) is doing as good a job as possible at keeping errors caused by the local system or the application itself labeled/categorized separate from target errors. Sometimes it isn't possible to identify the application as the cause of an error (e.g. disconnects) but for error conditions within the application, it's really useful to know about them separately from the usual set of errors that occur when hammering websites that may be broken in some way, under-resourced, or behind an active WAF

I think the short answer to your question is in general, nah, I'm not interested in individual detailed errors- it's just too much data, and there's rarely much that you can do with it. But I am interested in collecting the aggregate/summary of each type of error/result at the end of the scan. Right now I'm really just doing very dumb parsing of the output to look at in a big batch to see how it might be most useful to store, and to evaluate how effective the tool is (I've already concluded it's very effective, btw- really the best at this that I've seen, and something I was waiting for as a natural progression from `gobuster`)

> I like being able to put trace/debug output to a file (mostly for me, lol). That functionality could be moved to a `--debug-log` and the structured logging could be implemented as kind of a dual option thing:
> 
> * `--output somefile --output-type json`
> * `--output somefile --output-type text`
> 
> what do you think?

Maybe not what you're asking, but my opinion on the semantics, I prefer `-o<format> <filename>` just because it's less clunkier (e.g. `-oJ output.json`, `-eJ error.json`, `-dJ debug.json`, `-tT -` ... which is how a few other tools are doing this as I think you know (`massdns`, `masscan`, etc.) but with just a little more logical separation between the categories. Maybe an option to send all to one file if you want to. Anything with `-` would just stream/flush the full free-text content in real-time to stdout or stderr, which may be what you want when you're testing or sitting and watching a scan at the terminal.

On the topic of trace/debug output- would you consider performance data to be debug and/or trace output? Or maybe something separate? That's one thing that I think is useful both for development/debugging as well as just tracking performance over time, which might help users who are tracking that data over time to find bugs for you. Ideally the aggregated version of this data that gets spewed out at the end of the scan would be categorized/labeled so different types of events/measurements can be analyzed/processed/stored logically separate

At the end of the day, in my opinion, the implementation would be some basic infrastructure in the code that lets your individual threads increment per-thread counters (probably within a hashmap, or several hashmaps, keying on the category/type of metadata/event) as the scan runs, and then at the end of the run, some logic to aggregate them and output them in a clear structured way at the end, into separate files where it makes sense. I'm assuming that each of the threads is either long-lived, or has a way to safely write its data to a central data structure before it dies (without causing anything to block, to avoid killing the performance)

**Comment by epi052** [comment]
preview of json output

```
{"type":"configuration","wordlist":"test","config":"/home/epi/.config/feroxbuster/ferox-config.toml","proxy":"","replay_proxy":"","target_url":"https://bitdiscovery.com","status_codes":[200,204,301,302,307,308,401,403,405],"replay_codes":[200,204,301,302,307,308,401,403,405],"filter_status":[],"threads":50,"timeout":7,"verbosity":3,"quiet":false,"output":"things3","user_agent":"feroxbuster/1.7.0","redirects":false,"insecure":false,"extensions":[],"headers":{},"queries":[],"no_recursion":false,"extract_links":false,"add_slash":false,"stdin":false,"depth":4,"scan_limit":0,"filter_size":[],"filter_line_count":[],"filter_word_count":[],"dont_filter":false}
{"type":"log","message":"set open file descriptor limit to 8192","level":"DEBUG","time_offset":0.000423907,"module":"feroxbuster::utils"}
{"type":"log","message":"Writing scan results to things3","level":"INFO","time_offset":0.001456711,"module":"feroxbuster::reporter"}
{"type":"log","message":"Starting scan against: https://bitdiscovery.com","level":"INFO","time_offset":0.58131415,"module":"feroxbuster::scanner"}
{"type":"response","url":"https://bitdiscovery.com/api","status":301,"content_length":173,"line_count":10,"word_count":16,"headers":{"content-length":"173","referrer-policy":"origin-when-cross-origin","connection":"keep-alive","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","access-control-allow-headers":"X-Requested-With","date":"Sun, 22 Nov 2020 02:30:07 GMT","content-security-policy":"default-src 'none'","access-control-allow-origin":"https://bitdiscovery.com","content-type":"text/html; charset=UTF-8","location":"/api/","server":"nginx/1.16.1","strict-transport-security":"max-age=31536000; includeSubDomains","x-frame-options":"SAMEORIGIN"}}
{"type":"log","message":"static wildcard: filtered out https://bitdiscovery.com/api/api","level":"DEBUG","time_offset":1.0270598,"module":"feroxbuster::filters"}
{"type":"log","message":"All scans complete!","level":"INFO","time_offset":1.0279808,"module":"feroxbuster"}
```

**Comment by epi052** [comment]
> Maybe not what you're asking, but my opinion on the semantics, I prefer -o<format> <filename> just because it's less clunkier (e.g. -oJ output.json, -eJ error.json, -dJ debug.json, -tT - ... which is how a few other tools are doing this as I think you know (massdns, masscan, etc.) but with just a little more logical separation between the categories.

Unfortunately, the parsing library i use doesn't allow short options that use more than a single letter `-oJ` and friends are verboten :disappointed:.  I wanted to use double short options for some other stuff and found clap doesn't support it.

**Comment by uBadRequest** [comment]
It would really be awesome if we could get a simple json output of the results. I'm currently using grep and gron to get ffuf's json output to this format, because i'm trying to integrate with an automation platform. Personally, the reason why I am using the output log feature, I don't need all of that extra noise, configuration details, messages, etc.
![image](https://user-images.githubusercontent.com/47282747/99914888-5f60da00-2cce-11eb-81d1-0a2320af096a.png)

**Comment by epi052** [comment]
That's what it'll end up being (although compressed/not pretty).  The logs and config stuff will be in a debug log and only response messages will be in the output file. That's what you're saying, right ?

**Comment by mzpqnxow** [comment]
> preview of json output
> 
> ```
> {"type":"configuration","wordlist":"test","config":"/home/epi/.config/feroxbuster/ferox-config.toml","proxy":"","replay_proxy":"","target_url":"https://bitdiscovery.com","status_codes":[200,204,301,302,307,308,401,403,405],"replay_codes":[200,204,301,302,307,308,401,403,405],"filter_status":[],"threads":50,"timeout":7,"verbosity":3,"quiet":false,"output":"things3","user_agent":"feroxbuster/1.7.0","redirects":false,"insecure":false,"extensions":[],"headers":{},"queries":[],"no_recursion":false,"extract_links":false,"add_slash":false,"stdin":false,"depth":4,"scan_limit":0,"filter_size":[],"filter_line_count":[],"filter_word_count":[],"dont_filter":false}
> {"type":"log","message":"set open file descriptor limit to 8192","level":"DEBUG","time_offset":0.000423907,"module":"feroxbuster::utils"}
> {"type":"log","message":"Writing scan results to things3","level":"INFO","time_offset":0.001456711,"module":"feroxbuster::reporter"}
> {"type":"log","message":"Starting scan against: https://bitdiscovery.com","level":"INFO","time_offset":0.58131415,"module":"feroxbuster::scanner"}
> {"type":"response","url":"https://bitdiscovery.com/api","status":301,"content_length":173,"line_count":10,"word_count":16,"headers":{"content-length":"173","referrer-policy":"origin-when-cross-origin","connection":"keep-alive","x-xss-protection":"1; mode=block","x-content-type-options":"nosniff","access-control-allow-headers":"X-Requested-With","date":"Sun, 22 Nov 2020 02:30:07 GMT","content-security-policy":"default-src 'none'","access-control-allow-origin":"https://bitdiscovery.com","content-type":"text/html; charset=UTF-8","location":"/api/","server":"nginx/1.16.1","strict-transport-security":"max-age=31536000; includeSubDomains","x-frame-options":"SAMEORIGIN"}}
> {"type":"log","message":"static wildcard: filtered out https://bitdiscovery.com/api/api","level":"DEBUG","time_offset":1.0270598,"module":"feroxbuster::filters"}
> {"type":"log","message":"All scans complete!","level":"INFO","time_offset":1.0279808,"module":"feroxbuster"}
> ```
> 
> each line is a json entry, making it NDJSON (as far as i know... lol).
> 
> can be parsed in python by splitting on the newlines
> 
> ```
> [json.loads(x) for x in Path('things3').read_text().splitlines()]
> ```

Looks good to me- aside from loading in Python (or whatever language) JSON and line-based JSON can be searched and transformed in the shell very neatly with `jq` which is a a huge time-saver and much nicer than `grep`, `cut`, `awk`, `sed`, etc..

Looking forward to checking this out, thanks!

**Comment by uBadRequest** [comment]
Also, if you could include only the path, and remove the host, that would be awesome. Not just including the match from the wordlist, because when you start going recursive you wouldn't have the complete path to that location.

But with the awesome feature you have that looks for links in a documents, lets say you find a link thats referencing a location on a subdomain, that would have to be an exception to that.

**Comment by epi052** [comment]
> Also, if you could include only the path, and remove the host, that would be awesome. Not just including the match from the wordlist, because when you start going recursive you wouldn't have the complete path to that location.
> 
> But with the awesome feature you have that looks for links in a documents, lets say you find a link thats referencing a location on a subdomain, that would have to be an exception to that.

So, given this example output

```
{
   "type":"response",
   "url":"https://localhost.com/api",
   "status":301,
   "content_length":173,
   "line_count":10,
   "word_count":16,
   "headers":{
      "content-length":"173",
      "referrer-policy":"origin-when-cross-origin",
      "connection":"keep-alive",
      "x-xss-protection":"1; mode=block",
      "x-content-type-options":"nosniff",
      "access-control-allow-headers":"X-Requested-With",
      "date":"Sun, 22 Nov 2020 02:30:07 GMT",
      "content-security-policy":"default-src 'none'",
      "access-control-allow-origin":"https://bitdiscovery.com",
      "content-type":"text/html; charset=UTF-8",
      "location":"/api/",
      "server":"nginx/1.16.1",
      "strict-transport-security":"max-age=31536000; includeSubDomains",
      "x-frame-options":"SAMEORIGIN"
   }
}
```

I understand your request to be the addition of the following
```
...
    "path":"/api",
...
```

Is that what you mean by path?

**Comment by mzpqnxow** [comment]
@epi052 I will just let you know now to anticipate exceptional cases- there are some broken servers (usually they're load-balancers as you might guess) that will respond with same header name on two different lines (and even two different values), e.g.:

...
HTTP/1.1 200 OK

...
Server: bah123
Server: bah456
...
```

This is not *common* but against very large target lists, it happens. You'll have to either overwrite the first instance of the header with the second given that the output is implemented as a map/hash/dict.

The way `zgrab2` handles this is by treating each header *value* as a list- which is a bit annoying to deal with, but I guess their priority was being fully lossless (different kind of tool, different purpose)

Just an FYI, I don't feel too strongly about how this is handled since it's such an edge case and `feroxbuster` isn't meant to be a general purpose HTTP data gathering tool- I consider this data an added bonus. For all I care it can be lossy and the last occurring header with a duplicate name can just overwrite the prior ones.

**Comment by epi052** [comment]
As far as duplicate headers, that's not something I manually manage.  The reqwest library (and hyper underneath) does all that heavy lifting.  The headers i get back are in essentially a hashmap, so i suspect the most recently seen will overwrite the former. If you have a reliable test case to throw it against, let me know the results!

**Comment by mzpqnxow** [comment]
Got it. I will pick out a test case at some point and see how it goes. Good to know it's abstracted so you don't worry about it, though I'm curious how it will handle it

**Comment by mzpqnxow** [comment]
Wanted to put a note in here- really nice job with the structured output- I especially like the line count and word count. Post-processing is soooo much simpler without having implement your own fuzzy matching on strings and/or content-length, and the data in the new output format solves that. Thanks!

**Comment by epi052** [comment]
Glad it's working out well, thank you!
