### ISSUE TITLE
[BUG] Unable to scan HTTPS sites on HtB

### ISSUE THREAD

**Issue by LMAY75** [epi052/feroxbuster#128]
**Describe the bug**

When attempting to scan HTTPS sites on HackTheBox, ferox throws an error saying: "heuristics::connectivity_test Could not connect to any target provided"

https://imgur.com/IQe15md

**To Reproduce**

1. connect to HtB VPN
2. Add '10.10.10.216    laboratory.htb' to /etc/hosts
3. feroxbuster -u https://laboratory.htb/ -s 200 -t 25 -x txt,php,sql -w /usr/share/wordlists/dirb/common.txt

**Expected behavior**

Ferox connects and begins to brute force the directories

**Traceback / Error Output**

heuristics::connectivity_test Could not connect to any target provided

**Environment (please complete the following information):**
 - feroxbuster version: 1.0.5
 - OS: Parrot 5.7.0-2parrot2-amd64

**Additional context**

When scanning HackTheBox machines

**Comment by epi052** [comment]
Pretty sure you just need a `-k`.  Let me know if that fixes it!  Also, you're like, 12 versions behind.  There's a much clearer error message for this specific problem now 😁

**Comment by LMAY75** [comment]
> Pretty sure you just need a `-k`. Let me know if that fixes it! Also, you're like, 12 versions behind. There's a much clearer error message for this specific problem now grin

Awesome, thanks!

Wasn't sure if I should have messaged you on HtB or posted a bug here xD I'll go update it

**Comment by epi052** [comment]
This is probably the better option, in case others have similar problems, they're all centrally located.  Closing this one.
