### ISSUE TITLE
[FEATURE REQUEST] Blacklist redirect destinations by domain or fqdn

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#130]
I swear, this is my last feature request until I'm able to at least contribute something myself ...

It would be nice to have an option to specify either a line-based file or a list of comma separated string arguments (or an option that can be repeated to build a list) representing a blacklist of FQDN (exact matches) or domain (all subdomains underneath that domain) that will not be followed from a redirect.

For example:

`-u http://mysite.com/ --prevent-redirect login.microsoftonline.com,sso.whateverelse.com`

This is mainly useful in dealing with SSO redirects, as you can probably guess from the examples. A less useful feature (nmap does this with some of its plugins, I think it's too limiting) would be having a flag to restrict redirects to the originating FQDN or domain- e.g. allow `http://www.google.com 302 => https://www.google.com` or `https://google.com 302 => https://www.google.com`, but prevent following `https://www.blablabla.com => https://www.domain-parking-to-earn-treasure.net`

Probably on your list of TODO if/when time permits as this isn't a particularly novel idea- if so, consider this a placeholder :wink:

This would complement the `--depth` option nicely, I think

**Comment by epi052** [comment]
This is a pretty simple add. 

Just need to expose a new command line option and create a [custom redirect policy](https://docs.rs/reqwest/0.10.10/reqwest/redirect/struct.Policy.html#method.custom) where each blacklisted redirect is added to the policy.

**Comment by epi052** [comment]
In looking at #286 , i think a more generic approach would satisfy both feature requests.
