### ISSUE TITLE
[BUG]  Error while making request, no file descriptors available, and question about -t option.

### ISSUE THREAD

**Issue by LaiKash** [epi052/feroxbuster#131]
**Describe the bug**

I am testing this vs a server with a WordPress installed. I know what directories are in the WordPress and the wordlist used is wide known and tested to have the directories I am hoping to find with the scan.

Here I have three bugs/questions. 

1. Sometimes I randomly get this error, which I really do not know why it promts, as they are 404:

![image](https://user-images.githubusercontent.com/24409595/99387360-255d9580-28d4-11eb-82b0-d0fc6ab6b00c.png)

2. When I increment the number of threads from 100 to 200, it seems as... different (I do not know if this could help):

200 threads:

![image](https://user-images.githubusercontent.com/24409595/99388177-74f09100-28d5-11eb-987a-b832fb1ddcf3.png)

Another iteration of 100 threads:

![image](https://user-images.githubusercontent.com/24409595/99388716-4cb56200-28d6-11eb-938a-f5a790177d8d.png)

3. I get a lot of "no file descriptors available". I am with a root account and I have done what is done in the readme. From my experience, with -t 50 this does not happen so often, but when it is increased more than that, it will surely happens. 

**To Reproduce**
1. Just execute what is in the images of the description vs a WordPress server. The wordlist used is directory-list-2.3-medium.txt.

**Expected behavior**
No errors promts and the directories /wp/ and /wp/wp-admin are "quickly" found.

**Traceback / Error Output**
ERR    259.611 Error while making request: error sending request for url (http://10.11.1.251/wp/001649): connection closed before message completed

**Environment (please complete the following information):**
 - feroxbuster version: 1.5.3
 - OS:

![image](https://user-images.githubusercontent.com/24409595/99388966-a3bb3700-28d6-11eb-821b-5f819d727c84.png)

**Additional context**
The Kali I am using is installed in a host with only a root account; it is not a VM.
I have checked it whit a Kali in a VM without root and this still happens.

If I can help a bit more in any test, please, tell me.

**Comment by epi052** [comment]
Thank you for checking out the project and the report!

The error in question can be boiled down to 'networking stuff'.  `feroxbuster` uses reqwest which uses hyper to make requests to the server. [This issue report](https://github.com/hyperium/hyper/issues/2136#issuecomment-589345238) to the hyper project explains what is happening (quoted below to save you a click).  This isn't a bug so much as it's a target-specific tuning issue.  As you found, when lowering the `-t` value, the error doesn't occur (or happens much less frequently).

For the open file limit you're hitting, you can simply raise the limits (hard and soft) higher than the recommended 8192.  I'd be interested to know if the different `sysctl` commands listed in the README have any affect.  

Either way, this isn't a bug.  Just slow down the scan (or in the case of the open file limit, just make it higher) :wink:.  A `-t` value of `50` was chosen as a sane default that's still quite fast out of the box.  However, network related errors may occur when the client and/or server become over-saturated. 

Closing this issue with the recommendation to tune each scan to the specific target.  Please feel free to reach out to me directly over twitter if you have any additional issues related specifically to this issue.  Thanks again!

> This is just due to the racy nature of networking.
> 
> hyper has a connection pool of idle connections, and it selected one to send your request. Most of the time, hyper will receive the server's `FIN` and drop the dead connection from its pool. But occasionally, a connection will be selected from the pool and written to at the same time the server is deciding to close the connection. Since hyper already wrote some of the request, it can't really retry it automatically on a new connection, since the server _may_ have acted already.

**Comment by bennettwarner** [comment]
Hi Epi052,

Love the tool, keep up the awesome work. Just one follow-on question. Is there currently a way to suppress the error from output?

Thanks!

**Comment by epi052** [comment]
> Hi Epi052,
> 
> Love the tool, keep up the awesome work. Just one follow-on question. Is there currently a way to suppress the error from output?
> 
> Thanks!

Hey, sorry i missed this message.  Keep an eye on https://github.com/epi052/feroxbuster/issues/119 for updates. It should address your concern (and is probably next on the chopping block)
