### ISSUE TITLE
[BUG] Small addition to docs for cargo building

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#134]
This is just a quick administrative placeholder for a tiny PR I'm going to send. It's just a note for building from source that those who don't use `cargo` may find helpful.

In my configuration (I guess because I have my gitconfig set to convert https://github.com => ssh://github.com) cargo install of a checked out repo fails as it seems to do some parsing/honoring of the gitconfig, but not all. So when you `cargo build`, it tries to authenticate to GitHub via ssh, but without using the settings in ~/.ssh/config ... I don't really care to figure out why this is, but `CARGO_NET_GIT_FETCH_WITH_CLI=true` fixes it and is documented [here](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli)

I'll just add a one line note next to the building from cargo line in the readme if you'll take it.

**Comment by epi052** [comment]
Please see my [comment on the PR](https://github.com/epi052/feroxbuster/pull/135#issuecomment-733688181) on my reasoning for closing this one.  Thank you again for all of your help!
