### ISSUE TITLE
[FEATURE REQUEST] Filter based on regex or a blacklist

### ISSUE THREAD

**Issue by uBadRequest** [epi052/feroxbuster#136]
**Is your feature request related to a problem? Please describe.**
When running a content discovery tool on a a host, you may eventually get blocked and the page may change to start saying "You've been blocked." or "Please contact an administrator." or "Intrusion detected" for example.

**Describe the solution you'd like**
The ability to supply a regex that can be used to filter out "false positives"
OR
The ability to supply file that contains your "blacklist" of sentences that if the response contains them, then ignore it.

**Describe alternatives you've considered**
ffuf supports it? but your recursion seems to work when you enable follow redirects, where ffuf currently doesn't :+1: 

**Additional context**

Add an json output format so i can easily integrate into my tool and insert to my database :+1: 
In the json output, drop the target url, and just include the path. If you could, try to match dirsearch's json output :+1: 
Maybe that should be another feature request^ :thinking:

**Comment by epi052** [comment]
Haha, I'm working the json output now in #124, can you drop the logging comment about paths in that issue so I remember when Im reviewing it?

The regex filter is something that's crossed my mind. It's actually a simple add with some of the other filtering code I added recently.
