### ISSUE TITLE
[BUG] Filter by response size 

### ISSUE THREAD

**Issue by N0ur5** [epi052/feroxbuster#154]
**Describe the bug**
If you submit the -S flag in addition to the -r flag, the -S flag will be ineffective on responses that are a result of a redirection (the final "location" the response points to). 

**To Reproduce**
1. Find a URL with a known redirect. Run Feroxbuster with -r flag against URL to determine size of the page an user lands on AFTER the redirect occurs.
2. Re-run the scan above but with -S <size of page from step 1>
3. Note that the size filter does not work against the target when the page is a result of a redirect

**Expected behavior**
Feroxbuster looks at the final location of the redirect (when the -r flag is present) and determines that size to compare to size supplied in -S flag. I am assuming that right now it looks at the size of the 301/302 redirect response instead. 

**Environment (please complete the following information):**
 - feroxbuster version: v1.8.0

**Comment by epi052** [comment]
Thanks for the report!  

I'll take a look at this soon.

**Comment by epi052** [comment]
@N0ur5 Here's what I'm seeing

A scan without `-r` shows the 302

```
feroxbuster -u https://SOME_TEST.URL  -w word
...
302        1l        4w       39c https://SOME_TEST.URL/register
```

Adding `-r` shows the redirection location and 4091 as the length of the returned page

```
feroxbuster -u https://SOME_TEST.URL  -w word -r
...
200      126l      281w     4091c https://SOME_TEST.URL/invitation_error
```

Adding `-S 4091` filters out `invitation_error`.  
```
feroxbuster -u https://SOME_TEST.URL  -w word -r -S 4091
...
```

This appears to work as I would expect it to.  

Did I misunderstand something?

**Comment by N0ur5** [comment]
Hmm. No it appears that is behaving exactly how I would expect. Let me see if I can redact a screencap. Worth noting I'm on 1.8.0. Not sure if anything changed since that would effect this. Reporting back shortly with screencap

**Comment by N0ur5** [comment]
![image (1)](https://user-images.githubusercontent.com/24260009/101828455-940ec700-3aff-11eb-8589-4e462b9c660b.png)

**Comment by epi052** [comment]
Thanks for the screenshot, that clears it up!  Here's what is happening.  You're specifying `-S 1671`, but should be using `-S 188425`.  

You COULD use `1671`, but that would be `-N 1671` or `--filter-lines 1671`

For the sake of completion (and helping anyone else who stumbles here later on):
- The first column is the number of lines in the body (`1671l`) and can be filtered with `-N|--filter-lines`.
- The second column is the number of words in the body (`4667w`) and can be filtered with `-W|--filter-words`.
- The third column is the number of characters (aka the Content-Length, aka the Size) in the body (`188425c`) and can be filtered with `-S|--filter-size`.

Please let me know if adjusting according based on the info above helps.

**Comment by N0ur5** [comment]
Oh I am confident it certainly will. My apologies for the confusion. Let me give it a go.

**Comment by N0ur5** [comment]
You know what else I just realized is that the number is 167, but I was mistaking it for 1671 because of the "l" that is representing "lines" much like the "w" and "c" after the other numbers. Also my own confusion somewhat but maybe wouldn't hurt to add a space or some font formatting (eg. bold/colorized/etc) to those 3 chars. Just my opinion of course! Love this tool regardless though, it performs like a champ! I will close this up and thank you again for your time.

**Comment by epi052** [comment]
I'll sneak some kind of formatting change in to address that, it's a good suggestion.  

Thank you for the kind words, and for taking the time to submit an issue.  I really appreciate both!
