### ISSUE TITLE
[BUG] error trying to connect: tcp connect error: Connection refused (os error 111)

### ISSUE THREAD

**Issue by tdefise** [epi052/feroxbuster#156]
**Describe the bug**
I'm using feroxbuster against a website and have the following bug

![image](https://user-images.githubusercontent.com/36169753/101931829-3e5b1d00-3bda-11eb-9069-648d862ca8c6.png)

**To Reproduce**
1../feroxbuster -u  http://192.168.0.35/ -k -r --depth 6 --extract-links # Within an environment similar as mine

**Expected behavior**
N/A

**Traceback / Error Output**
Please see the screenshot

**Environment (please complete the following information):**
 - feroxbuster version:1.9.1
 - OS version: 5.9.0-kali1-amd64

**Additional context**
I'm using VMWare Player on Windows 10. One VM is the Kali Linux 2020.4 and the other one is a vulnerable box from VulnHub.
Both VMs are in Bridge Mode.
I'm able to run Gobuster against it, but I would like to use Feroxbuster for the capabilities that Gobuster don't propose.

**Comment by epi052** [comment]
Howdy!  

If I had to guess based solely on the image, I suspect there's a redirect on the page you're scanning that sends you to localhost. 

Can you do the following? 
- try running without `-r`
- add `--debug-log debug.log -vvv` to the command

In the event that you still see odd behavior, please let me know and attach the debug.log that gets generated (assuming you're allowed by whomever you're scanning)

**Comment by tdefise** [comment]
Hello @epi052 

Please find the debug log below

[debug.log](https://github.com/epi052/feroxbuster/files/5680633/debug.log)

**Comment by epi052** [comment]
Thanks!  I see you still used `-r` in the provided debug.log.  Can you try again without it?
