### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Alphaz0r** [epi052/feroxbuster#164]
**Describe the bug**
Hello, just installed the service, it is really great tbh but I'm facing an error, here's a screenshot of it
![image](https://user-images.githubusercontent.com/17253480/102548339-ce0d3980-40ba-11eb-8ab9-9fed3bc1db61.png)

**To Reproduce**
1. 10.10.10.209 is Doctor box from HackTheBox.eu ( a vm )
2. Launch the vm from the website 
3. Command is just above ( _sudo ./feroxbuster -w medium.txt -u https://10.10.10.209:8089/ -t 25_ )

**Expected behavior**
Enumeration of this website

**Traceback / Error Output**
Look at screenshot :)

**Environment (please complete the following information):**
 - feroxbuster version: [e.g. v1.10.1]
 - OS [kali linux 2020.3 VMWARE]

**Additional context**
I tried to enumerate the same target with gobuster and it worked really well, I'm wondering why it doens't work with ferox... 
![image](https://user-images.githubusercontent.com/17253480/102548690-512e8f80-40bb-11eb-9a12-666716b4e165.png)

**Comment by epi052** [comment]
Hey there, thanks for giving ferox a try!  

You just need a `-k` added to your command. 

Ferox rejects self signed certs and other "insecure" certificates by default.  You can choose to scan these services anyway by telling ferox to ignore insecure server certs. 

Let me know if that fixes your issue, and thanks again!

**Comment by FlorianVanbelle** [comment]
Hello !

Thanks a lot, it did work. Sorry for bothering you !

Have a nice day, merry christmas !

**Comment by epi052** [comment]
Not a bother at all, thanks for reporting back!  

:christmas_tree: Merry christmas to you as well :christmas_tree: 

closing

**Comment by epi052** [comment]
Also, the README will be updated to capture this in the FAQ, thanks again!
