### ISSUE TITLE
[BUG] FeroxScan not found when scanning multiple targets via STDIN

### ISSUE THREAD

**Issue by SleepiPanda** [epi052/feroxbuster#169]
**Describe the bug**
I'm getting a Scan Error when piping multiple URLs into feroxbuster. Is this error expected when sending multiple different top level URLS?

**To Reproduce**
1. Use a tool to generate a list of targets. In this case I used aquatone to generate a list of URLs. 
   ```https://xxx.xxx.xxx.xxx
      https://xxx.xxx.xxx.xxx
      https://xxx.xxx.xxx.xxx
      https://xxx.xxx.xxx.xxx
      https://xxx.xxx.xxx.xxx
      https://xxx.xxx.xxx.xxx
      http://xxx.xxx.xxx.xxx
      http://xxx.xxx.xxx.xxx
      https://xxx.xxx.xxx.xxx ```
2.  Pipe those into feroxbuster using ` cat targets.txt | feroxbuster --stdin ARGS`
3.  Get  `Could not find FeroxScan associated with` error.

**Expected behavior**
Scanning should continue as expected with multiple URLs

**Traceback / Error Output**
If applicable, add error output to help explain your problem.

**Environment (please complete the following information):**
 - feroxbuster version: Release Branch
 - OS: Amazon Linux 2

**Comment by epi052** [comment]
Thanks for the report!  After a quick look, it seems like this is a legitimate bug.  

I'll take a closer look later, but in the interim, you can use something like 

```
for i in $(cat targets); do ./feroxbuster -u $i ARGS; done
```

or [parallel](https://www.gnu.org/software/parallel/).

**Comment by epi052** [comment]
thanks for this! 

Version 1.10.3 contains the fix (which I'll have published here shortly).

**Comment by epi052** [comment]
done
https://github.com/epi052/feroxbuster/releases/tag/v1.10.3
