### ISSUE TITLE
[BUG] Cargo Install Fails when building for arm64

### ISSUE THREAD

**Issue by HenryHoggard** [epi052/feroxbuster#180]
**Describe the bug**
Feroxbuster fails on installation using cargo. It appears to be due to the fuzzyhash dependency, possibly due to the fact that its attempting to build on arm64.

**To Reproduce**
```
cargo install feroxbuster
```

**Expected behavior**
Cargo installation should succeed.

**Traceback / Error Output**

```
   Compiling fuzzyhash v0.2.0
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuzzyhash-0.2.0/src/lib.rs:248:5
    |
241 | pub unsafe extern "C" fn fuzzyhash(buf: *const u8, length: usize) -> *mut i8 {
    |                                                                      ------- expected `*mut i8` because of return type
...
248 |     s.into_raw()
    |     ^^^^^^^^^^^^ expected `i8`, found `u8`
    |
    = note: expected raw pointer `*mut i8`
               found raw pointer `*mut u8`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuzzyhash-0.2.0/src/lib.rs:274:43
    |
274 |     let f = FuzzyHash::new(CStr::from_ptr(first).to_string_lossy().into_owned());
    |                                           ^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuzzyhash-0.2.0/src/lib.rs:275:43
    |
275 |     let s = FuzzyHash::new(CStr::from_ptr(second).to_string_lossy().into_owned());
    |                                           ^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `fuzzyhash`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `feroxbuster v1.11.0`, intermediate artifacts can be found at `/tmp/cargo-installoih7XN`

Caused by:
  build failed
```

**Environment (please complete the following information):**
 - Ubuntu 20.04.1 LTS 
 - Using ubuntu docker image
 - arm64 architecture

**Comment by epi052** [comment]
Thanks for the report!

That's interesting.  Could you post your `rustc` version?  

In the meantime, I'd recommend downloading a pre-compiled binary from the [releases](https://github.com/epi052/feroxbuster/releases/tag/v1.11.0) page.

**Comment by epi052** [comment]
I apologize, I missed the arm64 bit.  I can see if my pipeline can pop out an arm build for you

**Comment by HenryHoggard** [comment]
> Thanks for the report!
> 
> That's interesting. Could you post your `rustc` version?
> 
> In the meantime, I'd recommend downloading a pre-compiled binary from the [releases](https://github.com/epi052/feroxbuster/releases/tag/v1.11.0) page.

```
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

I'm currently testing this on arm64, and there isn't a precompiled binary for that.

I've modified lib.rs to use c_char instead, it appears to compile without error using the below patch:

```
diff --git a/src/lib.rs b/src/lib.rs
index 0e32cc1..c38b733 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -59,6 +59,7 @@ use hasher::Hasher;
 use std::ffi::{CStr, CString};
 use std::fmt;
 use std::path::Path;
+use std::os::raw::c_char;

 /// Result of fuzzy hash operations
 pub type Result<T> = std::result::Result<T, error::Error>;
@@ -238,7 +239,7 @@ impl From<String> for FuzzyHash {
 ///
 /// ```
 #[no_mangle]
-pub unsafe extern "C" fn fuzzyhash(buf: *const u8, length: usize) -> *mut i8 {
+pub unsafe extern "C" fn fuzzyhash(buf: *const u8, length: usize) -> *mut  c_char {
     let data = std::slice::from_raw_parts(buf, length);
     let mut fuzzy_hash = FuzzyHash::new(data);
     fuzzy_hash.finalize();
@@ -270,7 +271,7 @@ pub unsafe extern "C" fn fuzzyhash(buf: *const u8, length: usize) -> *mut i8 {
 /// assert_eq!(compared, 17);
 /// ```
 #[no_mangle]
-pub unsafe extern "C" fn fuzzyhash_compare(first: *const i8, second: *const i8) -> u32 {
+pub unsafe extern "C" fn fuzzyhash_compare(first: *const c_char, second: *const c_char) -> u32 {
     let f = FuzzyHash::new(CStr::from_ptr(first).to_string_lossy().into_owned());
     let s = FuzzyHash::new(CStr::from_ptr(second).to_string_lossy().into_owned());
```

This was copied from https://github.com/PyO3/pyo3/commit/a0960f891801c0534856cb90fa90451828579470 which also had a similar bug due to the different platform architectures, using https://doc.rust-lang.org/std/os/raw/type.c_char.html instead fixes it.

**Comment by epi052** [comment]
Nice! I imagine the proper way to do this is to submit a PR to [fuzzyhash](https://github.com/rustysec/fuzzyhash-rs).  If the maintainer isn't interested in fixing, a separate fork could be maintained for building this project on arm.

**Comment by epi052** [comment]
[fuzzyhash v0.2.1](https://docs.rs/fuzzyhash/0.2.1/fuzzyhash/) incorporates the fix. Updated Cargo.toml to reflect the new lib version; closing.
