### ISSUE TITLE
Feature Request- Recursion on 403 dirs

### ISSUE THREAD

**Issue by N0ur5** [epi052/feroxbuster#183]
Hello - Just me again :) 

I have found there to be a good number of cases where a directory that is 404'ed still has subdirs or files than can be 200's (or other non-forbidden responses). 

Any chance you could implement recursion on 404'ed directories? If the feature exists already and I missed it, I apologize in advance! 

Thank you!
Nick

**Comment by epi052** [comment]
Hey there!

If you've got a specific site to test against, can you try using the `--add-slash` option to see if that accomplishes your goal?

**Comment by N0ur5** [comment]
Thanks for the fast response! I will see if that works and let you know!

**Comment by N0ur5** [comment]
Ok let me start by saying I totally meant to say 403'ed (forbidden) not 404 (not found). My apologies.

**Comment by epi052** [comment]
ha! ok, that's different, for sure, lol.  

do you envision this being default behavior, or opt-in?

**Comment by N0ur5** [comment]
Lol yea a recursion on 404 would be a little silly, sorry about that hahaha.

Ummm I feel like yes to it being default behavior in my opinion. I have been taking the 403 dirs in my pentests and bug bounty recon and re-running ferox manually for each 403. Seems to be something I come across pretty consistently! 

Of course, totally your call! 

Thanks!

**Comment by epi052** [comment]
i should mention, i'm generally ok with this feature.  I've considered adding something like the checks performed by https://github.com/lobuhi/byp4xx, but it felt a little too invasive/prone to false positives.  However, simply testing a 403 to see if it's likely to be a directory, and then recursing into it if it is, sounds reasonable.

**Comment by epi052** [comment]
ill take a look at this a little later, i'm pretty sure it's a relatively small change to make it work

**Comment by N0ur5** [comment]
![image (2)](https://user-images.githubusercontent.com/24260009/104367776-48c64a80-54e9-11eb-8647-d1b417d24813.png)

For your reference. You can see the /customtags/ dir was found as 403, recursion set to infinite. Although in this specific example I dont have a screencap then showing something in that dir that's accessible (eg. a 200 response) but there have been times for sure! So adding that "customtags" dir (using this example) to the recursion list would be awesome. Sounds like you know what I meant now that I got the right HTTP response code across hahah. 

Happy to provide more thoughts/opinions as needed, otherwise thank you for your time and consideration!

**Comment by epi052** [comment]
Thanks for submitting the request!  It sounds like a good feature add to me

**Comment by epi052** [comment]
done. check out `v1.12.1`
