### ISSUE TITLE
[BUG] Wildcard doesn't filter when content length is 0

### ISSUE THREAD

**Issue by BitThr3at** [epi052/feroxbuster#195]
**Describe the bug**
Sometimes tool  fails to avoid wildcard responses whether with 200 status code or 302 status code

**To Reproduce**
See the attached screenshot, choose any wordlist you want with the domain seen in screenshot

**Expected behavior**
Can you optimize it to Filter almost all wildcard responses

**Environment:**
 - feroxbuster version: v1.12.3
 - OS windows 10 wsl 2 with kali linux

**Additional context**
![image](https://user-images.githubusercontent.com/45028933/104876850-7c3c2580-597e-11eb-9d96-212cda2cdf3f.png)

**Comment by epi052** [comment]
hey there, and thanks for the report!  

I don't immediately see a public program for the url in the screenshot, so I don't plan on scanning it myself (unless you can point me to their program).

First: can you try `feroxbuster ... your normal options ... --filter-similar-to https://account-alt.noon.com/uae-en`?

`--filter-similar-to` was added specifically to handle instances where the (arguably simplistic) wildcard checker fails to filter. 

Second, the content length of `0` is what's throwing off the filtering, static wildcard filtering only filters on non-zero length responses.  After seeing your screenshot, I'm not sure that's a reasonable check anymore... lol. 

I'll think on the filtering of `0` length wildcards, but can you try the `--filter-similar-to` and let me know if that works for you? 

```rust
        if self.size > 0 && self.size == response.content_length() {
            // static wildcard size found during testing
            // size isn't default, size equals response length, and auto-filter is on
            log::debug!("static wildcard: filtered out {}", response.url());
            log::trace!("exit: should_filter_response -> true");
            return true;
        }
```

**Comment by BitThr3at** [comment]
Seems to be working for me, Thank you buddy for such awesome tool😉

**Comment by epi052** [comment]
Just an update on this, 0-length wildcards will filter properly in 2.0.0.
