### ISSUE TITLE
[BUG] - stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by sh0reline** [epi052/feroxbuster#197]
**Describe the bug**

When launching a scan on any website I get this error:
Error while scanning: stream did not contain valid UTF-8

**To Reproduce**
1.UP to date kali VM machine
2.Shared IP with host (working internet connection)
3.Fresh pull from ferox

**Expected behavior**

An actual scan.

**Traceback / Error Output**
If applicable, add error output to help explain your problem.

Error while scanning: stream did not contain valid UTF-8

**Environment (please complete the following information):**
 - feroxbuster version: [e.g. v1.0.1] 
 latest
 - OS [e.g. ubuntu 20.04]
 kali latest

**Additional context**

**Comment by epi052** [comment]
Morning! 

It sounds like a wordlist problem.  Can you try a few different wordlists and let me know the results? 

ex: `..../seclists/Discovery/Web-Content/common.txt`

**Comment by epi052** [comment]
also, in case it isn't a wordlist issue, can you post the command used and your installation method?

If you're able to share the url scanned, that'd be cool, but I understand if you can't.

**Comment by sh0reline** [comment]
Hey, thanks for the response you where right. big.txt from dirbuster somehow has trouble parsing with ferox.
<3

**Comment by epi052** [comment]
i took a closer look at this; in the event that a single line isn't UTF-8, that line will be skipped when reading the wordlist. 

The behavior you saw exits if ANY line isn't UTF-8.  With this change, you'll still be able to use the wordlist, assuming it has other lines that are valid UTF-8.

Change will be included in 1.12.4
