### ISSUE TITLE
sudo apt install ./feroxbuster_amd64.deb not working on Kali

### ISSUE THREAD

**Issue by cocoonkid** [epi052/feroxbuster#218]
sudo apt install ./feroxbuster_amd64.deb not working on Kali

sudo dpkg -i feroxbuster_amd64.deb
>> works

just for the ReadMe.

wget https://github.com/epi052/feroxbuster/releases/latest/download/feroxbuster_amd64.deb.zip
does suffice as well? the current -s flag in the ReadMe is not supported.

Thanks for this project!

**Comment by epi052** [comment]
Hey there, thank you for the report!  

I'll see what's going on with this before I release the next update. Thanks again!

**Comment by epi052** [comment]
i spun up kail 2020.4 and found a few issues with the instructions on the README.  First, the `-sLO` flags are options to `curl`, not `wget` :sweat_smile: .  Second, the unzipped deb has the version in the name.  I've updated the readme with the following commands.  Can you let me know if these work on your machine? I didn't have any issues on my VM with them.  

```
curl -sLO https://github.com/epi052/feroxbuster/releases/latest/download/feroxbuster_amd64.deb.zip
unzip feroxbuster_amd64.deb.zip
sudo apt install ./feroxbuster_*_amd64.deb
```

thanks again!

**Comment by epi052** [comment]
In addition to updating the readme, feroxbuster is now available in the official kali repos and should be installed from there when using kali; closing

**Comment by cocoonkid** [comment]
My apology for not responding earlier.  Everything works yes :-)
