### ISSUE TITLE
[BUG] Did not find page

### ISSUE THREAD

**Issue by secure-77** [epi052/feroxbuster#226]
**Describe the bug**
feroxbuster just did not found a site, (gobuster did). dont want to spoil the htb box to much, so no specific text here (just check screenshots). since a few boxes i only use feroxbuster and so, this tooks me hours to get forward with this box. the desired word is in line 271 so feroxbuster should had already found it

**To Reproduce**
1. in the htb vpn, add the subdomain of the bucket machine to your hosts file
2. run feroxbuster with the wordlist
3. no result :(

**Expected behavior**
should found the site

**Environment (please complete the following information):**
 - feroxbuster version: 2.0.0 and also 2.2.1
 - OS: Kali Debian 5.10.13-1

![ferobug](https://user-images.githubusercontent.com/31564517/108784117-f445ce80-756e-11eb-980a-f0d9be59ba0e.png)
![response](https://user-images.githubusercontent.com/31564517/108784119-f4de6500-756e-11eb-930b-d162494e5ad9.png)

**Comment by epi052** [comment]
Thanks for this! I'll take a look later, however, I suspect it was an unfortunate timeout.  Ferox is a bit more aggressive with timeouts than gobuster (7s vs 10s). Htb boxes, especially on public, can bust that timeout pretty consistently.

**Comment by epi052** [comment]
Also, if you didn't let feroxbuster run to the end of the wordlist, that could be the problem as well.  Ferox doesn't request words in the same order that they're seen in the wordlist.  There's a chance the word you were looking for could be the very last request made, even though it's 271 in the wordlist

**Comment by epi052** [comment]
![image](https://user-images.githubusercontent.com/43392618/108789853-d9f4fc00-7540-11eb-84b1-d9b6869efc03.png)

**Comment by epi052** [comment]
![image](https://user-images.githubusercontent.com/43392618/108789891-ed07cc00-7540-11eb-9044-7dd81dd38c74.png)

**Comment by epi052** [comment]
Scanned it and was able to find it using the same wordlist; it ended up being the 141905th request (for me, ymmv)

**Comment by epi052** [comment]
Leaving this open for now, in case you saw behavior different from what I've described/seen above.

**Comment by secure-77** [comment]
ah, i see. didnt know about this behavior. i let it run again for a while and can confirm that it found the url. so this bug can be closed.

is there a chance to force feroxbuster to use the wordlist content in ascending order? in the field that should not matter but there are many CTF boxes arround where the hidden urls or words are in the top ~1000 . i know there is no confidence about that but a comlete scan does take about 30min so i would be glad if get the quick wins as quick as possible

**Comment by epi052** [comment]
currently, no.  it's something i can toy around with, but nothing right now would allow that. the simplest solution (which is something i do) is to have a smaller wordlist that you use for more immediate results (i usually use common.txt in seclists). Once that is complete, i typically have a few urls i can investigate, during which i kick off a scan with a larger wordlist.  

The same strategy could be used for htb. 

I'll keep the ordered wordlist read in mind though.  Thank you!
