### ISSUE TITLE
[BUG] Cant build feroxbuster on ARM

### ISSUE THREAD

**Issue by tienna-0051** [epi052/feroxbuster#235]
**Describe the bug**
I'm trying to build feroxbuster on the raspberry pi but run into an error with `serde`

**To Reproduce**

```
Raspberry Pi 3 Model B+
```

```
➜  feroxbuster git:(main) rustup show
Default host: armv7-unknown-linux-gnueabihf
rustup home:  /home/pi/.rustup
stable-armv7-unknown-linux-gnueabihf (default)
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

```
➜  feroxbuster git:(main) cargo build --release
   Compiling feroxbuster v2.2.2 (/home/pi/sectools/feroxbuster)
error[E0277]: the trait bound `AtomicUsize: Deserialize<'_>` is not satisfied
  --> src/statistics/container.rs:28:5
   |
28 |     /// tracker for number of timeouts seen by the client
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `AtomicUsize`
   |
   = note: required by `next_element`

error[E0277]: the trait bound `AtomicUsize: Deserialize<'_>` is not satisfied
  --> src/statistics/container.rs:31:5
   |
31 |     /// tracker for total number of requests sent by the client
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `AtomicUsize`
   |
   = note: required by `next_element`

error[E0277]: the trait bound `AtomicUsize: Deserialize<'_>` is not satisfied
  --> src/statistics/container.rs:34:5
   |
34 |     /// tracker for total number of requests expected to send if the scan runs to completion
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `AtomicUsize`
   |
   = note: required by `next_element`
```
At [https://serde.rs/derive.html#troubleshooting](https://serde.rs/derive.html#troubleshooting), the docs suggest to "upgrade or downgrade libraries as appropriate until the Serde versions match" but `cargo tree -d` return nothing. Can you check this?

Best regards,

**Comment by epi052** [comment]
Thanks for the report! I'll take a look tomorrow

**Comment by epi052** [comment]
Good morning, 

I've added a dynamically linked armv7 build to my CI pipeline (link to the built binary below).  Can you give it a try and see if it works on your end? 

For whatever reason serde won't derive Serialize/Deserialize on atomics for arm, so I wrote a custom [de]serializer for the Stats struct. My tests still pass using an x86 binary, but I don't know if they truly pass on an arm host.  

Could you try the following and make sure nothing goes haywire?
- start scan with save_state enabled (default is true)
- let it run for a bit and then `ctrl+c`, this will hit the serialization of the Stats struct
- resume the scan using `--resume-from STATE_FILE`, this will hit the deserialization of the Stats struct

If everything looks ok for you, ill merge to main.

armv7 feroxbuster: https://github.com/epi052/feroxbuster/suites/2188250532/artifacts/45096600

**Comment by tienna-0051** [comment]
Hi,

I ran a test with the new artifact on my raspberry pi, and it seems working correctly 👍 
Log: https://pastebin.ubuntu.com/p/b8cCSYsX72/
