### ISSUE TITLE
[FEATURE REQUEST] HTML report generation

### ISSUE THREAD

**Issue by Regala** [epi052/feroxbuster#244]
**Is your feature request related to a problem? Please describe.**
Currently the tool supports a limited type of output formats. Generating a HTML report is one solution to very easily review the results generated.

**Describe the solution you'd like**
[ffuf](https://github.com/ffuf/ffuf) has a good working example of this. Anything that has some sort of DataTables on top, to be able to do sorting/search is more than enough.
An advanced version of this feature would be to combine all the results from parallel/multiple scans in one HTML report file - which would be awesome.

**Describe alternatives you've considered**
None.

**Additional context**
Thanks for your work! This tool seems amazing, good work 🙏

**Comment by epi052** [comment]
thank you for the kind words and the request! 

i like the idea of supporting more output formats and a final html report would be nice. 

I'm currently enrolled in offsec's new course, so don't plan on working anything significant for ferox until that's complete, just as a heads up. Though, I'd be more than happy to accept a PR for this in the interim if anyone would like to work it.

Thanks again for taking the time to make a request!

**Comment by poorpy** [comment]
Hi, @epi052 can I take this issue?

**Comment by epi052** [comment]
@poorpy of course! Please hit me up if you have any questions 🎉🎉

**Comment by epi052** [comment]
@poorpy as far as the command line, what do you think of adding `--format FORMAT` and then redirecting `--json` to whatever the underlying dispatcher is for different formats?   That would maintain the old api in case folks are using --json in scripts etc, and would also allow for additional formats to be added easily later on.  What are your thoughts?

**Comment by poorpy** [comment]
@epi052 yeah, I think that's the way to go. Imo deprecating/removing `--json` flag should happen in separate release (if ever desired).

**Comment by epi052** [comment]
@poorpy below is my personal checklist for adding a new command line option. I've forgotten things enough times to necessitate its creation.

- Add new command line option checklist
    - config/container.rs
        - add value to `Configuration` struct
        - add value to `Configuration::default`
        - update `Configuration` docstring
        - add value to `Configuration::parse_cli_args`
        - add value to `Configuration::merge_config`
    - config/tests.rs
        - update `Configuration::tests::setup_config_test` with new value
        - update `Configuration::tests::default_configuration` with new value
        - add test to check config parsing
    - ferox-config.toml.example
        - add new value
    - banner/container.rs
        - add new `BannerEntry` to `Banner` struct
        - update `Banner::new` with a `BannerEntry`
        - update `print_to` with whether to print or not
    - tests/test_banner.rs
        - add new test so that the new `BannerEntry` is displayed and examined under test
    - Cargo.toml
        - bump version - minor release +1 - patch release = 0
    - README.md
        - update default config section (if needed)
        - update example config file section
        - update help output section
        - consider adding an example (new or existing)
        - update comparison table (if needed)
    - parser.rs
        - add the option
    - wherever.rs
        - implement the new feature

**Comment by GobiasSomeCoffeeCo** [comment]
Hey @poorpy! Just curious if you're still working on this issue or if you need any help? If not, would you mind if I took a crack at it? Please let me know. Thanks!

**Comment by poorpy** [comment]
Hi @GobiasSomeCoffeeCo, feel free take over this issue.

**Comment by GobiasSomeCoffeeCo** [comment]
Hope this question makes sense:

Hey @epi052, I started to look at this issue. Can you point me in the direction of where the finalized state is held/updated? Looking around the codebase, it seems FeroxResponse is responsible for this task, but I'm not exactly sure which file is handling the logic that is actually performing the task? Any help would be appreciated.

**Comment by epi052** [comment]
Yes, your question makes sense. There are a few structures you'll probably care about. The first is the [Stats struct](https://github.com/epi052/feroxbuster/blob/main/src/statistics/container.rs#L26).  Next is [FeroxResponses](https://github.com/epi052/feroxbuster/blob/main/src/scan_manager/response_container.rs#L7). Both of those structures can be serialized individually or as part of the [FeroxState struct](https://github.com/epi052/feroxbuster/blob/main/src/scan_manager/state.rs#L9).

If it were me, I'd approach this issue by first examining what data is available to be reported. This would include the members of the Stats struct as well as the different items in a FeroxResponse (status code, url, etc...). After noting all of the data and what is relevant as an end user, I'd begin work on the html report, using dummy data as a starting point.

Once an html report is ready using dummy data, I'd then ping the project owner and figure out a good strategy on integrating the change into the larger project :wink: 

Hopefully that's enough to get you going in the right direction. Lmk if you need anything else.

**Comment by epi052** [comment]
After thinking about it a bit, you could get the dummy data from a scan with `-o` and `--json`. I believe that'll have the configuration, each FeroxResponse, and the Statistics struct all serialized into json.

**Comment by GobiasSomeCoffeeCo** [comment]
Appreciate the info! That'll help a lot. I was printing out the structs in different places last night to get a sense of where it was being handled.

**Comment by GobiasSomeCoffeeCo** [comment]
Hey! Just wanted to let you know I haven't forgotten about this issue. Been traveling quite a bit, but will be back home in a couple days. Try and get a rough draft going this upcoming weekend.

**Comment by epi052** [comment]
Hopefully the traveling has been for a fun/good reason. 

It's not a problem, there's no rush or pressure. If you have stuff going on, it's also ok to drop the issue as well. No harm, no foul.

**Comment by GobiasSomeCoffeeCo** [comment]
Looking at the original request, and having some free time last night, my first instinct was to write a csv output file for the html report (as it's easy to search through different columns (IMO)).

I wrote what might be a naive solution to this, but wanted to test it out by integrating it into the larger project. I've been looking around, and was wondering where I could incorporate the logic? 

The `utils::write_to` takes a ferox response, output file, and boolean json value and handles it. Was thinking something similar for writing a csv file? Hoping that I can take a response struct, the output file designated by the user, and create a report. Something along the lines of ```rust
pub fn write_to_csv(ferox_data: &FeroxResponse, file: file: &mut io::BufWriter<fs::File>```
and match on a Command::Report or creating a similar arm called Command::CSVReport?

Let me know if I am going in the right direction, or if I'm taking crazy pills and should restart from the beginning of the rust book with a `hello world` 😆?  If I need to do a 180, no issues, just want to make sure it fits into your larger picture with where you'd like it to go. Let me know! Thanks!

**Comment by epi052** [comment]
@GobiasSomeCoffeeCo sorry! I saw this message, and then spaced on the reply.  I saw the PR, I'll get a review going soon and provide feedback there directly. Thanks!
