### ISSUE TITLE
[FEATURE REQUEST] Detect when directory listing is enabled

### ISSUE THREAD

**Issue by its0x08** [epi052/feroxbuster#245]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when Im scanning for directories and ferox finds an open directory and still does bruteforce even there is just 1 item alredy vissible!

**Describe the solution you'd like**
I would like to have an opendir pattern recognition that would either stop in an opendir or just include everything thats inside without bruteforcing it.

**Comment by epi052** [comment]
Good morning, and thanks for the report!

Do you mean when the server has directory listing enabled? 

![image](https://user-images.githubusercontent.com/43392618/111029708-b09ef180-83c3-11eb-97ea-2993b4626289.png)

**Comment by its0x08** [comment]
Exactly.
I understand different servers have different ways to show dir listing which makes it challenging but its something that's needed at least for apache 😄

**Comment by epi052** [comment]
This sounds reasonable, and could be a heuristic check performed at the start of a new directory (in my experience most servers just generate a static index.html from the directory contents). 

In the meantime, if you already know that certain directories are listable, you could simply [cancel that directory](https://github.com/epi052/feroxbuster#cancel-a-recursive-scan-interactively-new-in-v1120). I know this isn't a great solution, since you normally find out after the fact, but it's something to keep in mind for now.

**Comment by godylockz** [comment]
Just to let you know, DirBuster is able to resolve directory listings just fine. Didn't know if you wanted to use some of it's code for pseudo code. I think its the only tool I have found that supports them (that I know of).
I found the source here: https://github.com/KajanM/DirBuster

I don't use DirBuster anymore, but feroxbuster is definitely the go to. I know gobuster, ffuf, wfuzz, etc. all DO NOT support directory listings as well for some reason.

**Comment by epi052** [comment]
@godylockz yea, to get from where `-e` is currently, to doing what you found in dirbuster, we'd have to parse a tags, (i.e. #291)

**Comment by epi052** [comment]
fixed; `-e` now detects directory listing, sucks up all the links (recursing as necessary), and aborts that scan to not waste cycles scanning for things we already know.

**Comment by epi052** [comment]
@all-contributors add @its0x08 for ideas

**Comment by epi052** [comment]
@all-contributors add @godylockz  for ideas and code
