### ISSUE TITLE
[FEATURE REQUEST] Automatically find directories in `/robots.txt` and bust them

### ISSUE THREAD

**Issue by bee-san** [epi052/feroxbuster#248]
**Is your feature request related to a problem? Please describe.**

I had this idea a little while back. `URL/robots.txt` is supposedly a place where people hide directories they don't want found.

**Describe the solution you'd like**

Add an option that allows FeroxBuster to parse `robots.txt` and add those directories to the wordlist to bust.

**Describe alternatives you've considered**

Doing it by hand, which sucks because manual work.

**Additional context**

You'll make this cat very happy by adding this feature.
![image](https://user-images.githubusercontent.com/10378052/111299904-67130880-8648-11eb-8ddf-b47cfbe1c578.png)

**Comment by epi052** [comment]
Thanks for the request!

fortunately for the cat, this is [already implemented](https://github.com/epi052/feroxbuster#extract-links-from-robotstxt-new-in-v1102)! It only looks at Allow and Disallow entries, do you think it should account for other robots entries on top of those two?

**Comment by bee-san** [comment]
Ahh no, it becomes a web crawler at that point I believe
