### ISSUE TITLE
[FEATURE REQUEST] Allow dash-delimited numbers in scan cancel menu

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#268]
**Is your feature request related to a problem? Please describe.**

When there are more than 5-10 threads active in the scan cancel menu, it can be cumbersome to type each thread number out, delimited by commas

**Describe the solution you'd like**

It would be nice to support simple range notation, e.g. instead of 1,2,3,4,5 supporting 1-5. Ideally 1,2,3-5 format

**Additional context**

Apologies for not contributing a PR for this, it's laughably trivial- but I've not even touched rust code at this point so it's probably a lot more efficient for you to take a quick look

Thanks, the features are coming along really well, very impressed with how quickly you've put this all together. Really appreciate the time and effort

**Comment by mzpqnxow** [comment]
One additional note, it I can fit it into this issue- it would be nice to be able to set a flag so you don't have to confirm each thread before it's cancelled. Example:

```
───────────────────────────────────────────────────────────
Enter a comma-separated list of indexes to cancel (ex: 2,3)
───────────────────────────────────────────────────────────
100,101,102,103,104
You sure you wanna cancel this scan: https://mail.whatever.com/~old? [Y/n]
...

It's another thing that's very clunky to deal with when a lot of threads are created and need to be cancelled. Ideally it would be on the user to tune the scan so that this many threads don't pop up- either by filtering certain noisy paths, or by adjusting the scan rate- but in some cases there will always be a lot of junk paths to deal with

**Comment by epi052** [comment]
this is done in #270 ; i just need to push the release

**Comment by epi052** [comment]
merged
