### ISSUE TITLE
[BUG] infinite recursion

### ISSUE THREAD

**Issue by Raywando** [epi052/feroxbuster#285]
Hello,

The tool runs into infinite recursion, I think i have a good example for that to demonstrate:

![image](https://user-images.githubusercontent.com/33800255/121001671-326ca400-c794-11eb-99ea-a72780231913.png)

The first directory `cgi-bin` returned 403 and anything after that is 404 which led the tool to assume that it is a directory which is a good technique but the directory `.git`  returns 403 and everything after that returns 403 also which made the tool assume everything after `.git` is a directory and finally the process gets killed because it ate up all the memory

My suggestion:

```
if .git returns 403 then:
    BLACKLIST_STATUS_CODE = https://targets.com/.git/RANDOMSTRING

    if https://target.com/.git/WORDLIST rerurns BLACKLIST_STATUS_CODE then:
        return NOT_VALID_RESULT
    else
        return VALID_RESULT
```

This can work for both files and directories (because it also happened to me with files and retuned all of the files in the wordlist as valid results in a new discovered directory)

**Comment by epi052** [comment]
Good morning and thanks for the report! 

This is a great use-case for the [scan cancel menu](https://github.com/epi052/feroxbuster#cancel-a-recursive-scan-interactively-new-in-v1120).  

It looks like your suggestion is essentially the same [wildcard test](https://github.com/epi052/feroxbuster/blob/main/src/heuristics.rs#L151) we already perform on each recursed directory, or am i missing something?

**Comment by Raywando** [comment]
Hey,

I actually don't know the first thing in rust xd
It seems like you already run a wildcard test but sometimes it fails hard and considers the whole wordlist as valid results as you see in the above picture, maybe it's because the server is returning a 403 and the wildcard test is only checking for 200? Not sure.

As for the scan cancel menu, first of all, it would be nice to expect a range like 2-10 to remove all tasks in range.
And for my example, every time I cancelled a task, 10 more gets generated so it didn't help.

I've sent you my example URL on your Twitter account if you are interested to test it.

Thanks for the amazing work btw.

**Comment by epi052** [comment]
> Thanks for the amazing work btw
:pray: 

> As for the scan cancel menu, first of all, it would be nice to expect a range like 2-10 to remove all tasks in range.
So, the kali repo is a little behind github. [v2.2.4](https://github.com/epi052/feroxbuster/releases/tag/v2.2.4) has exactly that feature. `1-6,7-11` etc... are valid and a `-f` can be used to skip the verification prompts.

**Comment by epi052** [comment]
overhauled the wilcard stuff in 2.8.0, haven't seen any additional reports about this, closing for now. feel free to reopen if needed
