### ISSUE TITLE
[FEATURE REQUEST] add abiIity to blacklist by url

### ISSUE THREAD

**Issue by black-A** [epi052/feroxbuster#286]
sorry，I am not good at English，so i just  my upload my situation by photos
![test](https://user-images.githubusercontent.com/30686803/121119189-c5b5e000-c84d-11eb-9be4-4566a14a65e0.png)

as you can see,i want to blast a domain like "www.xxx.com/cn" ,It's important to note that i don't  want to blast www.xxx.com ,i just want to blust www.xxx.com/cn  , but the machine works and automatictally add this "www.xxx.com" to blast,i konw i can enter and cancle this，but it can‘t work with this way when i use feroxbuster in  my scripts, i'll appreciate if someone can help！thankyou！

**Comment by epi052** [comment]
Good morning and thanks for the report! 

The [scan cancel menu](https://github.com/epi052/feroxbuster#cancel-a-recursive-scan-interactively-new-in-v1120) does exactly what you want, simply cancel the directory you don't want to scan.

**Comment by black-A** [comment]
> Good morning and thanks for the report!
> 
> The [scan cancel menu](https://github.com/epi052/feroxbuster#cancel-a-recursive-scan-interactively-new-in-v1120) does exactly what you want, simply cancel the directory you don't want to scan.

yeah，thank you,you're right,i can Cancel a Recursive Scan Interactively,but i mean how can i  avoid that happened when i use the scripts write by myself like a python script maybe and the ferobuster just a part of this script,and i can't  Cancel the Recursive Scan Interactively in this way,because i want my scritpt run itself automatictally！Am I explaining this clearly? thanks again for you help！

**Comment by epi052** [comment]
Yup, I understand what you're asking for. You basically want a domain blacklist

```
--dont-scan
```
or something like that. Seems reasonable, ill see what kind of effort this would require soon.

**Comment by epi052** [comment]
i think that we can safely roll this request and #130 into the same request, as blacklisting a domain should take effect whether it's via a redirect or not.
