### ISSUE TITLE
[FEATURE REQUEST] always parse the --help parameter

### ISSUE THREAD

**Issue by secure-77** [epi052/feroxbuster#287]
Hi,

first of all, nice and congrats that your tool did it to the new kali release! :)

One little suggestion:
if there is a unexpected parameter/option or error, feroxbuster will print the error and usage message. That is, of course, fine!

In many cases, then i dont want to delete the hole wrong parameter before i knew the correct one, so i just add the --help parameter to the end of my command to print the help.

Unfortunately feroxbuster ignore the parameters that came past of the incorrect one. so i need first to delete the wrong parameter, then print the help and then add the correct parameter. 

would be nice if feroxbuster can always check for the parameter --help to print the help, regardless of the other options.

Example:
```
feroxbuster -u http://10.10.77.145:3333 -fc 403 -w /usr/share/seclists/Discovery/Web-Content/raft-small-words.txt --help
```
will not work, couse of the wrong -fc, so i fist need to delete "-fc 403" to print the help

Thanks for your work!
BR!

**Comment by epi052** [comment]
> first of all, nice and congrats that your tool did it to the new kali release! :)

:pray: ty!

That's kind of odd.  I use the [clap](https://docs.rs/clap/2.33.3/clap/) crate to handle command-line processing.  I reckon I could add a manual check for `--help`, as the desired behavior you described is definitely what I'd expect to happen.  Ultimately, I think this should probably be confirmed and filed with the clap project, but I think it's trivial enough to squeeze in a manual fix somewhere along the line.

**Comment by secure-77** [comment]
Great, thank you for the investigation!
