### ISSUE TITLE
brew install feroxbuster Not works

### ISSUE THREAD

**Issue by Teicu** [epi052/feroxbuster#295]
Hi 

Can you please check why it doesn't work?  The download page seems to be empty
 
https://github.com/epi052/feroxbuster/releases/download/v2.2.5/x86_64-macos-feroxbuster.tar.gz - NOT FOUND

Thanks

_brew install feroxbuster
==> Installing feroxbuster from tgotwig/feroxbuster
==> Downloading https://raw.githubusercontent.com/epi052/feroxbuster/master/ferox-config.toml.exampl
######################################################################## 100.0%
==> Downloading https://github.com/epi052/feroxbuster/releases/download/v2.2.5/x86_64-macos-feroxbus
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "feroxbuster"
Download failed: https://github.com/epi052/feroxbuster/releases/download/v2.2.5/x86_64-macos-feroxbuster.tar.gz_

**Comment by epi052** [comment]
that was 100% my fault, thanks for the heads up!  It should work now, lmk if it doesn't.
