### ISSUE TITLE
[FEATURE REQUEST] do not return exit code 1 if parameter --help is used.

### ISSUE THREAD

**Issue by sbrun** [epi052/feroxbuster#301]
Hello,

In the latest release 2.3.0 if we pass the parameter --help or -h, feroxbuster will always exit with the exit code 1.
(The code has been changed to fix https://github.com/epi052/feroxbuster/issues/287)

I think it would be better to exit with the exit code 0 (maybe even if others parameters are not correct).

In Kali we are trying to add auto package tests to our packages to detect quickly big regressions or issues. And one basic test is to run the commandline -h and check the exit code.

**Comment by epi052** [comment]
this was such a small fix, i didn't bother branching. Fix is pushed in 2.3.1, which i'm deploying now. Thank you! (and sorry for breaking your tests :grimacing: lol)
