### ISSUE TITLE
[FEATURE REQUEST] Add scope/blacklist support to limit redirect following to within a specified domain/subdomain.

### ISSUE THREAD

**Issue by KillyP** [epi052/feroxbuster#308]
Say I am scanning app.example.com and most of requests redirect to www.example.com but some requests redirect within app.example.com, I would like to be able to follow redirects unless they jump to a different domain/subdomain.

**Comment by epi052** [comment]
It sounds like you're looking for [this feature](https://github.com/epi052/feroxbuster#prevent-specific-domaindirectory-scans-aka-a-deny-list-new-in-v230)
