### ISSUE TITLE
[BUG] wordlist cant be found

### ISSUE THREAD

**Issue by kr0t3** [epi052/feroxbuster#325]
i have used -w option and the same issue is happening. what can i do? 
![image](https://user-images.githubusercontent.com/13562845/128593409-95bb6795-2846-4dd6-8e43-ee48f37cc83d.png)

**Comment by epi052** [comment]
My first guess is that you installed using the snap package.  If that's the case, please check out the information [here](https://github.com/epi052/feroxbuster#snap-install) that explains how to deal with the wordlist and a snap install.
