### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GobiasSomeCoffeeCo** [epi052/feroxbuster#356]
**Describe the bug**
Hey @epi052 ! Downloaded feroxbuster via `cargo install feroxbuster`, but when running an initial scan on a localhost instance, it continued to produce the error " Failed while scanning: Could not open /wordlists/raft-medium-directories.txt". In this example, I changed to ferox-config.toml "wordlist" to the specified directory, because the default "/usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt" was getting the same error (I checked and the directory did not exist). I noticed this was an issue when installing with snap, but unsure if this is a common issue with other install methods? 

**To Reproduce**
1. Download via `cargo install feroxbuster`
2. run `feroxbuster -u http://127.0.0.1:8000`
3.

**Expected behavior**
Hoping it works without the `-w ~/wordlists/raft-medium-directories.txt` flag.

**Traceback / Error Output**
" Failed while scanning: Could not open /wordlists/raft-medium-directories.txt".

**Environment (please complete the following information):**
 - feroxbuster version: 2.3.2
 - MacOS 11.6

**Additional context**
Seems like an awesome tool and would be willing to help contribute with any fixes going forward!

<img width="995" alt="Screen Shot 2021-09-20 at 7 59 29 PM" src="https://user-images.githubusercontent.com/60927833/134098194-88b9b064-c276-4c4a-ab20-cda8ab1dc306.png">

**Comment by epi052** [comment]
Howdy, and thanks for checking out the project! 

If I understand the question correctly, you're saying that the path to your wordlist isn't being read correctly from your config file? 

If so, does your entry in the config file look like `~/wordlists/raft-medium-directories.txt`?  If you used the tilde in your config file, can you please try it with an absolute path, i.e. `/Users/chris/...`?

**Comment by GobiasSomeCoffeeCo** [comment]
Hey!
Sorry, looks like it doesn't like the absolute path either...

<img width="851" alt="Screen Shot 2021-09-20 at 8 43 31 PM" src="https://user-images.githubusercontent.com/60927833/134099551-e45e4d3c-5be3-42cb-bb90-b6f7eccd698b.png">

**Comment by epi052** [comment]
That is very strange. Can you send upload your ferox-config.toml? 

Also, could you run ferox with strace? Is that a thing on mac? 

If not, can you run it with `--debug-log debug.log -vvvv`? and send me the log please? 

Also, just to make sure, you're NOT running it in a snap?

**Comment by GobiasSomeCoffeeCo** [comment]
Here you go, please let me know if you need anything else!

Looks like Mac does not have strace.

Converted .toml to a txt file:
[ferox-config.txt](https://github.com/epi052/feroxbuster/files/7199649/ferox-config.txt)

Here is the debug.log:
[debug.log](https://github.com/epi052/feroxbuster/files/7199663/debug.log)

And correct, I am NOT running it in a snap.

**Comment by GobiasSomeCoffeeCo** [comment]
Looks like I found the issue. I messed around with the `File::open` method, and apparently I didn't include a leading `/` for the file to be read :grimacing:. Sorry about that! Fixed the .toml file to read `/Users/chris/..`, and it worked like a charm. My bad for the false alarm!!!

**Comment by epi052** [comment]
No worries, glad it's sorted !

**Comment by GobiasSomeCoffeeCo** [comment]
Thanks for being so responsive! 

On a side note, and I'm sure I've lost all credibility at this point, but if you need any help going forward I'd love to get involved. I'll keep my eyes open for some "good first issues".

**Comment by epi052** [comment]
Not at all, typos get everyone now and again. 

As far as good issues:
- https://github.com/epi052/feroxbuster/issues/245 - research needs done on how one could detect directory listings
- https://github.com/epi052/feroxbuster/issues/244 - has been assigned for a while, but I haven't heard anything back since then. Could bump the thread and see what the status is
- https://github.com/epi052/feroxbuster/issues/165 - not exactly rust, but i don't have a mac to do the testing for this

**Comment by GobiasSomeCoffeeCo** [comment]
More than happy to see what I can do! Forewarning though, my coding skills are nowhere even close to yours. You could say they're "in development" at the moment, but if you don't mind some dumb questions and sending back code that needs to be refactored, I'd really like to see how I could help.

**Comment by epi052** [comment]
understood, and that's totally normal and fine. If you see something you want to work on, the first step is to reply to the issue and let me and everyone else know that you're going to tackle it. After that, we can chat about what comes next.
