### ISSUE TITLE
[FEATURE REQUEST] HTTP/1.1 Pipelining

### ISSUE THREAD

**Issue by c3l3si4n** [epi052/feroxbuster#389]
I'm pretty sure HTTP Pipelining is a very desirable feature for a content discovery tool like FeroxBuster, mainly due to the potential for it to increase the request rate in magnitudes by removing TCP handshakes overhead.

Turbo Intruder implements this and it scales up the request speed magnitudes higher.

**Comment by epi052** [comment]
I'm not against this necessarily, but don't know what an implementation would look like. I'll do some research on it and see.

**Comment by c3l3si4n** [comment]
Hello @epi052, check out this talk by James Kettle. It explains very well the feature and how it's implemented on Turbo Intruder.
https://www.youtube.com/watch?v=vCpIAsxESFY
