### ISSUE TITLE
[FEATURE REQUEST] Add URL to queue while paused

### ISSUE THREAD

**Issue by narkopolo** [epi052/feroxbuster#418]
I would like to propose a function that makes it possible to add a URL to the queue when pausing feroxbuster. 
Sometimes you find a valid directory by other means after having started scanning.

Imagine something like this when pressing enter and seeing the Scan Cancel Menu:

```
Enter a comma-separated list of indexes/ranges to cancel (ex: 1-4,8,9-13)
                Add -f to skip confirmation (ex: 3-5 -f)

       Type "add" followed by a URL to add it to the queue
                 eg. "add https://example.com"
```

**Comment by epi052** [comment]
i think this is pretty reasonable. It also amounts to an implementation detail, as the actual cli doesn't need to change. Going to pin it for now, until i get some time to work on it, unless you/someone else would like to take a stab at it. If so, I'm happy to help/guide along the way.

**Comment by epi052** [comment]
@all-contributors please add @narkopolo for ideas
