### ISSUE TITLE
[FEATURE REQUEST] Supply hostname to be used

### ISSUE THREAD

**Issue by rufflabs** [epi052/feroxbuster#423]
**Is your feature request related to a problem? Please describe.**
When doing HTB/etc websites sometimes provide different content if you're using proper FQDN. 

**Describe the solution you'd like**
A command line switch to supply a hostname/fqdn to be used when running scans.

**Describe alternatives you've considered**
Editing hosts file is always an option, but if the box doesn't actually require FQDN, I'd rather not spend the time adding it to a hosts file.

**Comment by epi052** [comment]
Can you elaborate on what the solution would look like? 

ferox can already request domains and can set arbitrary headers. 

Have you tried just setting the host header? i.e. 

`feroxbuster -u htb.ip.addy -H HOST: Box.Fully.Qualified`

**Comment by rufflabs** [comment]
Actually, I suppose supplying the -H and the Host header actually would suffice!
