### ISSUE TITLE
Direcotory listing - GET parameter

### ISSUE THREAD

**Issue by bizibabe** [epi052/feroxbuster#428]
Hello,
Is it possible to run feroxbuster only on a get parameter ?
exemple :
http://test.fr/api/download?file=FILE.txt
http://test.fr/api/download?file=FILE2.txt
...

**Comment by epi052** [comment]
If you mean inserting words from the wordlist into the file parameter in your example: no. 

[This issue](https://github.com/epi052/feroxbuster/issues/242 ) would enable that feature, but it's not implemented. 

To do what you're wanting, I'd recommend using [ffuf](https://github.com/ffuf/ffuf).
