### ISSUE TITLE
[FEATURE REQUEST]  Add support of multiple methods during scan

### ISSUE THREAD

**Issue by MD-Levitan** [epi052/feroxbuster#440]
**Is your feature request related to a problem? Please describe.**
During work I am always facing the problem that application are using REST API. And I just miss a lot of endpoints during scan. 

**Describe the solution you'd like**
So I propose just to add a list of methods like list of extension, with GET as default method.

**Describe alternatives you've considered**
None

**Additional context**
Thanks for your application!

**Comment by epi052** [comment]
@MD-Levitan if you've got a twitter account you'd like to me @ when i push 2.5.0, let me know, and thanks again!

**Comment by epi052** [comment]
@all-contributors add @MD-Levitan  for ideas and code
