### ISSUE TITLE
wordlist is not opening[BUG] 

### ISSUE THREAD

**Issue by Dixith1999** [epi052/feroxbuster#475]
**Describe the bug**
when trying to use it by giving a wordlist it says error can't open.

![ferox](https://user-images.githubusercontent.com/29366858/150771229-bee87246-a759-43cf-9371-c938313c0a2a.png)

**Comment by epi052** [comment]
My first guess is that you installed using the snap package. If that's the case, please check out the information [here](https://epi052.github.io/feroxbuster-docs/docs/installation/install-snap/#gotchas) that explains how to deal with the wordlist and a snap install.

**Comment by Dixith1999** [comment]
![image](https://user-images.githubusercontent.com/29366858/150817800-f494d44f-94d8-46c8-8041-1e22ef41a4d1.png)

**Comment by epi052** [comment]
Right, so you are using the feroxbuster snap. If you downloaded feroxbuster using curl, try running that exact file with an absolute or relative path. Conversely, you could use the link I provided earlier and continue using the snap.

**Comment by AliAlShammari** [comment]
Have the same problem.

**Comment by epi052** [comment]
try these commands, as-is:

```
curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/master/install-nix.sh | bash
./feroxbuster -u https://bitdiscovery.com -w /usr/local/bin/onelistforall.txt --time-limit 1s
```

**Comment by epi052** [comment]
apologies, i didn't catch that the latest reply was from a different person 😢 

@AliAlShammari let me know if [these instructions](https://epi052.github.io/feroxbuster-docs/docs/installation/install-snap/#gotchas) help you

**Comment by AliAlShammari** [comment]
Yup I remember how this works. Thank you for your help @epi052

**Comment by epi052** [comment]
assuming one thing or the other resolved the initial ask; closing. Feel free to reopen if needed.
