### ISSUE TITLE
[BUG] --dont-scan honored, but dont_scan in ferox-config.ini not

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#483]
**Describe the bug**

I came across the following behavior, and it's been a bit of a thorn in my side since I have a system that is based entirely on `ferox-config.toml` for the session parameters. I was able to break it down into what I *think* is the simplest issue, which is that `dont_scan` is not being honored in `ferox-config.toml`, but it *is* honored on the command-line, as `--dont-scan`

## To Reproduce**

The most contrived way to reproduce is as follows

### Confirm functionality via command-line is as expected

```
$ feroxbuster -u https://whatever.com --dont-scan https:// -w wordlist.txt
Could not determine initial targets: The regex 'https://' matches https://whatever.com; the scan will never start
```

This is expected behavior, :+1: 

### Confirm unexpected behavior via ferox-config.toml

Create a `./ferox-config.toml` with only the following:

```
dont_scan = 'https://'
```

Followed by:

```
$ feroxbuster -u https://whatever.com -w wordlist.txt
... merrily scans https://whatever.com ...
```

This is *not* what I expected as the behavior :-1:  - I expected it to bail with the same error as it does when used on the command-line

Other settings in `./ferox-config.toml` are honored, but `dont_scan` seems to either be ignored, or somehow overwritten/cleared, despite there being no other `ferox-config.toml` files in the search path or flags on the command-line to cause it to happen

#### Ruling out potential collisions with other `ferox-config.toml` files in the search path

To confirm that there were no conflicting `ferox-config.toml` files messing things up, I used `strace -o LOG -f` followed by `grep 'ferox-config.toml' | grep -v ENOENT`. As expected, I see the following (this is the entirety of the output, there are no other `ferox-config.toml` files loaded to worry about screwing up the behavior)

```
27200 statx(AT_FDCWD, "/working/directory/ferox-config.toml", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=23, ...}) = 0
27200 openat(AT_FDCWD, "/working/directory/ferox-config.toml", O_RDONLY|O_CLOEXEC) = 3
```

## Expected behavior**

I would expect `--dont-scan https` (via command-line) and `dont_scan = "https"` (via `ferox-config.toml`) to behave the same. I'm using a contrived example here obviously, but I initially observed this behavior in a more sane configuration

**Environment (please complete the following information):**
 - feroxbuster version: built from source (master @ 1/20/2022)
 - OS: Debian 10

## Additional context

* I'm also seeing some unexpected behavior of `url_denylist` (when used independently of `--dont-scan`) but I'll enter a separate issue for that after this is resolved, in case they are somehow related, maybe due to some bug in `ferox-config.toml` loading.
* I observed this when using extensive settings in `ferox-config.toml` as well, most of those other settings were working as expected (again, excluding `url_denylist`) so it's not a matter of a complete failure in loading `ferox-config.toml`

## TODO (for me)

I'll run with extra verbose/debug output and add what I find here. I'm a bit busy (and I'm sure you are too) but I'll try to spend a little time on it today if possible

**Comment by mzpqnxow** [comment]
So I guess I forgot the discussion about how this was implemented, but I see now from the debug output- ultimately `--dont-scan` arguments end up in `regex_denylist`. I confirmed that when specifying `--dont-scan https://` on the command-line, the `regex_denylist` setting internally is set to `["https://"]` as expected, while specifying `dont_scan = 'https://'` in `ferox-config.toml` leads to `regex_denylist` having the value of an empty list (`[]`) internally

I'll try to see if specifying `https://` directly as `regex_denylist` resolves the issue

**Comment by epi052** [comment]
yup, looks like you found it; the config expects the names of the struct, not necessarily the names of the cli flags. Not picking on you, just laying it out here for anyone else who finds their way here. 

I try to keep [the docs](https://epi052.github.io/feroxbuster-docs/docs/configuration/ferox-config-toml/) and [the example config](https://github.com/epi052/feroxbuster/blob/main/ferox-config.toml.example) up to date when new cli options are added. Those **should** be considered ground truth for which options are available via the config.

**Comment by epi052** [comment]
I agree that given the naming for most other things, the names used to control those values are surprising. Since we're deriving [De]Serialize from serde, there may be a clever flag for the serde attribute on that can handle `dont-scan` when deserializing from the config.

**Comment by mzpqnxow** [comment]
> yup, looks like you found it; the config expects the names of the struct members, not necessarily the names of the cli flags.

Ah, yeah OK I'm a doofus- I didn't realize that the toml wouldn't throw errors for unknown settings. There's no need at all for this specific flag being supported in the `toml` file, it's all just confusion on my part

I think this can be closed, thanks for the quick clarification!

**Comment by mzpqnxow** [comment]
In case this is helpful to anyone, I put this little hacky script together to do a best-effort check to identify any invalid keywords I might have in my `ferox-config.toml`:

```bash
#!/bin/bash
# Extract all of the documented keywords
cat ferox-config.toml.example | sed -e 's/^[ #]\+//g' | grep -P '[a-z_]\s*=\s*' | cut -d '=' -f 1 | sed -e 's/ //g' | sort -u > known_keywords.lst
cat ferox-config.toml | grep -Ev '^#' | grep -P '[a-z_]\s*=\s*' | cut -d '=' -f 1 | sed -e 's/ //g' | sort -u > used_keywords.lst
comm -2 -3 used_keywords.lst known_keywords.lst
```

It's not perfect, because of the `[headers]` section, but it should work on the majority of files. For best results, remove the `[headers]` section entirely before running
