### ISSUE TITLE
[FEATURE REQUEST] Dynamically expanding the wordlist based on metadata (DNS labels) and non-link page content

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#487]
This one may be a bit "out there", it's not something I feel too strongly about, but it definitely has value in certain cases. That said, it's easy for the user to do as a pre-run step on their own, so don't take this too seriously...

**Is your feature request related to a problem? Please describe.**

When enumerating directories on a site (e.g. https://someapp.bah.com) feroxbuster has knowledge of potentially useful words for enumeration- specifically, it knows each of the DNS labels of the FQDN ("someapp", "bah")

An example of a not uncommon use for this would be to find the directory https://someapp.bah.com/someapp, even when "someapp" is not in the wordlist

**Describe the solution you'd like**

It would be neat to have one or both of the following:

1. A flag that instructs feroxbuster to dynamically add some words derived from the DNS name into the wordlist (in the someapp.bah.com example, these might be as simple as "someapp" and "bah")
2. Similar to link extraction from JS, HTML or robots.txt, a subset of HTML content could be added to the wordlist. Maybe to start, the words in /index.html

**Describe alternatives you've considered**

The user can very easily adjust the wordlist themself before invoking feroxbuster for each host, with a small script that derives a few words from the FQDN and then appends them to the baseline/standard wordlist. Ditto for adding words tokenized from index.html or any other page. Doing it in feroxbuster is just more seamless

**Additional context**

I'm not sure this is worth the effort. If it is, I think the effort/value curve would flatten beyond the addition of just a few words. Maybe just adding each label of the DNS name to the words to be tried (for "https://someapp.bah.com", just ensure that "someapp" and "bah" are in the list of words tried)

**Next Steps**

Unless you feel gung ho about doing this, I'd like to implement this as a pre-run step and gather some data. If it turns out that this actually results in non-negligible improvements to findings, maybe it will be worth considering as a native feature. That's still your call, but the data should help inform it

I'll report back with data after I have some

Thanks for the great work!

**Comment by epi052** [comment]
I'm working on some stuff for the next release (if i can get it working and it doesnt suck :upside_down_face:) that this would align with this. I'm interested to hear what you find out as far as results.

**Comment by epi052** [comment]
implementation is live; the non-link content is something i've been planning for awhile. Coincidentally, I had started adding it locally just a few days before you put this issue in. I didn't add the domain stuff, but likely will on the next go around (2.6.0 is a pretty massive change)

**Comment by mzpqnxow** [comment]
Another suggestion- dynamically extending `extensions` at runtime, based on some threshold of scraped links or wordlist discoveries. The benefits are obvious, but there are some downsides (aside from the effort it requires)

One downside I can think of would be an explosion in requests when the user hasn't carefully tuned their `regex_denylist` and some configuration is encountered that replies to all requests in a directory. A common example being `/.ht*`. The other (possibly) more common one would be a server that always returns a response for a given extension

There are obviously many ways to deal with those cases, most fall on the user, though I'm sure you could be very intelligent with your logic- as one example, the engine might have logic to only record an "extension hit" when the content is of a unique size or exact content- that way `/.htbah/a.php

Imagined use would be something like `--dynamic-threshold=10` (where 10 is either an absolute number, or some sort of ratio based on the wordlist size, or "positive" responses

Anyway, I'm very happy with the work you've done here, it's just food for thought. I'm not sure at what point the logic will be impossible to untangle given all of these features, I'll leave that judgement to you ;)

**Comment by epi052** [comment]
Pretty sure this is implemented already, if I understand right.  --collect-extensions ?

**Comment by epi052** [comment]
Well, the dynamic part anyway, not the threshold
