### ISSUE TITLE
[BUG] The default wordlist file does not exist.

### ISSUE THREAD

**Issue by ekilzen** [epi052/feroxbuster#488]
**Describe the bug**
The default wordlist file does not exist.

**To Reproduce**
1. install feroxbuster via Homebrew
2. run `feroxbuster --url https://google.com`
3. show following output 
```shell
❯ feroxbuster --url https://google.com

 ___  ___  __   __     __      __         __   ___
|__  |__  |__) |__) | /  `    /  \ \_/ | |  \ |__
|    |___ |  \ |  \ | \__,    \__/ / \ | |__/ |___
by Ben "epi" Risher 🤓                 ver: 2.5.0
───────────────────────────┬──────────────────────
 🎯  Target Url            │ https://google.com
 🚀  Threads               │ 50
 📖  Wordlist              │ /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt
 👌  Status Codes          │ [200, 204, 301, 302, 307, 308, 401, 403, 405, 500]
 💥  Timeout (secs)        │ 7
 🦡  User-Agent            │ feroxbuster/2.5.0
 🏁  HTTP methods          │ [GET]
 🔃  Recursion Depth       │ 4
───────────────────────────┴──────────────────────
 🏁  Press [ENTER] to use the Scan Management Menu™
──────────────────────────────────────────────────
ERROR: Failed while scanning: Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt
```

**Expected behavior**
run without error.

**Traceback / Error Output**
see above

**Environment (please complete the following information):**
 - feroxbuster version: 2.5.0
 - OS: macOS Monterey 12.2

**Additional context**
N/A

**Comment by epi052** [comment]
Good morning, and thank you for the bug report! 

feroxbuster doesn't ship with any wordlists. Most commonly, you'd clone https://github.com/danielmiessler/SecLists and put them wherever you'd like, then point feroxbuster at your wordlist of choice. The default location was chosen based on kali's seclists install location.

In short, you'll need to grab wordlists from another project and use those. Hope that helps!

**Comment by pepa65** [comment]
Should add that to the readme..!
