### ISSUE TITLE
[FEATURE REQUEST] no-state flag

### ISSUE THREAD

**Issue by c0rv4x** [epi052/feroxbuster#502]
Hey, this is a question: I saw that some time ago you had `--no-state` flag which allowed a user to not save state on a run. Is there a way to do this now? I wasn't able to find any suitable flags in the help

**Comment by epi052** [comment]
Hey there, thanks for the question! As of v2.5.0, you can only turn off `.state` files by adding a line to your `ferox-config.toml`.

`--no-state` will be available as a cli option in v2.6.0. Let me know if you need anything else! 

https://epi052.github.io/feroxbuster-docs/docs/configuration/ferox-config-toml/
https://epi052.github.io/feroxbuster-docs/docs/examples/resume-scan/#opt-out-of-saving-state
