### ISSUE TITLE
[BUG] Discover backup feature only looking in root directory

### ISSUE THREAD

**Issue by gtjamesa** [epi052/feroxbuster#513]
**Describe the bug**
The new discover backups feature is not respecting the directory we are currently scanning, and is searching for backups in the root directory. I suspected something was wrong when I couldn't find the file I was looking for (HTB Dante), but gobuster found the file with no problem.

Gobuster with `--discover-backup` option:

![image](https://user-images.githubusercontent.com/2078364/157224944-6c21d204-b308-4046-8eb7-470e40142352.png)

Feroxbuster with `--collect-backups` option:

![image](https://user-images.githubusercontent.com/2078364/157225089-780d9ceb-ec6f-40e2-8419-9baf4a314479.png)

#489 #498

**To Reproduce**
1. `$ echo wp-config > wp-config.txt`
2. `$ feroxbuster --depth 1 -x php txt html -u http://10.10.110.100:65000/wordpress --collect-backups -w wp-config.txt --burp`

You can see the `/wordpress` directory from my base URL is not applied to the backup feature:

![image](https://user-images.githubusercontent.com/2078364/157225273-4d4f0400-48bb-4146-b940-913491b907fe.png)

**Expected behavior**
The backups should be searched from the base directory, i.e. `/wordpress/.wp-config.php.swp`

**Traceback / Error Output**
n/a

**Environment (please complete the following information):**
 - feroxbuster version: 2.6.0
 - OS: Kali 2021.1

**Additional context**
n/a

**Comment by epi052** [comment]
Thanks for taking the time to submit this, I really appreciate it! 

The fix is already in main. Once the build pipeline finishes, I'll cut a 2.6.1. Thanks again! 

@all-contributors add @gtjamesa for bugs

**Comment by gtjamesa** [comment]
> Thanks for taking the time to submit this, I really appreciate it!
> 
> The fix is already in main. Once the build pipeline finishes, I'll cut a 2.6.1. Thanks again!
> 
> @all-contributors add @gtjamesa for bugs

That's great, thanks for the fast fix! :)

**Comment by epi052** [comment]
> > Thanks for taking the time to submit this, I really appreciate it!
> > The fix is already in main. Once the build pipeline finishes, I'll cut a 2.6.1. Thanks again!
> > @all-contributors add @gtjamesa for bugs
> 
> That's great, thanks for the fast fix! :)

anytime; thanks again for reporting it!

**Comment by epi052** [comment]
bot is drunk

**Comment by gtjamesa** [comment]
My bad - I tagged him in my reply 😂
