### ISSUE TITLE
[FEATURE REQUEST]  Keep file part when extracting URLs

### ISSUE THREAD

**Issue by SecT0uch** [epi052/feroxbuster#519]
Hi, thanks for your work.

Given 
```html
<embed src="example/lol.ext" />
```
in a page.

In addition to add `/example/` to the queue, that would be great if we could also test and add `example/lol.ext` to the results.

**Comment by epi052** [comment]
Good morning! 

What you describe is the intended/expected behavior. If that's not happening, it's likely an oversight/bug. Will take a look this evening. 

Thanks for taking the time to submit this!

**Comment by epi052** [comment]
Just to be clear: 

- `example/` is being added to the scan queue 
- `example/lol.ext` is not being requested? 

That's what you're seeing?

**Comment by SecT0uch** [comment]
Yes, exactly that.

**Comment by epi052** [comment]
That certainly seems odd. I'll see if I can reproduce. Thanks!
