### ISSUE TITLE
Would it be possible not to add the directory to the queue if the listing is empty ?

### ISSUE THREAD

**Issue by epi052** [epi052/feroxbuster#520]
Would it be possible (and wise) not to add the directory to the queue if the listing is empty ?

_Originally posted by @SecT0uch in https://github.com/epi052/feroxbuster/issues/464#issuecomment-1062927922_

**Comment by epi052** [comment]
https://github.com/epi052/feroxbuster/pull/464#issuecomment-1063434950

**Comment by epi052** [comment]
Ok, moved this to a new issue instead of the old PR. 

> Would it be possible (and wise) not to add the directory to the queue if the listing is empty ?
I'm honestly confused as to what's happening.

What I think is happening based on the description:
- directory listing heuristic is triggered (i.e. ferox thinks it's found a directory listing)
- there are no links listed in the directory (i.e. empty directory)
- the empty directory is scanned as though it were a directory found by recursion? <--- part i'm confused about

**Comment by godylockz** [comment]
I'm thinking he didn't have extract links on and it scans the directory ? Is that true?

**Comment by SecT0uch** [comment]
I did have `-e` enabled.
Gonna let you know if I encounter that again.

That would be reproducible like that (not tested):
```
mkdir /tmp/empty
cd /tmp/empty
python -m "http.server"
```
You get an empty listing on http://localhost:8000/

**Comment by epi052** [comment]
I performed the following: 

```
mkdir -p /tmp/test/empty
cd /tmp/test/empty
python3 -m http.server
```
ran a scan 

```
cargo run -- -u http://localhost:8000/ -e
```

and got these results 

```
[####################] - 0s         0/0       0s      found:0       errors:0      
[####################] - 0s      4659/4659    0/s     http://localhost:8000/ => Directory listing
```

This is what I would expect to happen. 

If I understand correctly, you'd want to scan the directory when this happens. Is there a compelling reason to scan? Can web servers be setup in such a way that, when they have directory listing enabled, they can also 'hide' content in that directory? Are you thinking along the lines of .htaccess/basic auth preventing our view of the directory? If that were the case, I don't know that ferox would respond in this same way. 

I ask out of ignorance, so please, don't hesitate to educate me if I'm missing something.

**Comment by SecT0uch** [comment]
Just noticed the package in my distrib is out of date.. --'

You can close the issue, and gonna re-open if still facing the problem.

Sorry for the inconvenience.

**Comment by epi052** [comment]
Good deal, just reopen if needed.
