### ISSUE TITLE
[BUG] feroxbuster on Windows cannot find seclist instance in the same folder as 

### ISSUE THREAD

**Issue by ThisLimn0** [epi052/feroxbuster#537]
**Describe the bug**
When you run feroxbuster from the windows terminal with seclists in the same folder as feroxbuster you get 
Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt
as output.

**To Reproduce**
1. Open Windows Terminal and cd to feroxbuster directory with seclists directory in the same directory
2. .\feroxbuster.exe --url www.example.com 
3. Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt

**Expected behavior**
Run normally

**Traceback / Error Output**
Could not open /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt

**Environment (please complete the following information):**
 PS E:\GitHub\feroxbuster> .\feroxbuster.exe -V
feroxbuster 2.6.4
 - OS: Windows 10 Pro [ 19044.1620 / Windows Feature Experience Pack 120.2212.4170.0 ]

**Additional context**
Feroxbuster should just be able to work in its own directory.

**Comment by epi052** [comment]
hey, thanks for this. It's merged in 2.7.0
