### ISSUE TITLE
[FEATURE REQUEST] - Add Dynamic collection in toml conf

### ISSUE THREAD

**Issue by clem9669** [epi052/feroxbuster#538]
Hey,

It is not possible to configure in toml file the collect-backups, collect-extensions, collect-words.

Thanks 😄

**Comment by epi052** [comment]
they'll need an underscore in the config

- `collect_backups`
- `collect_extensions`
- `collect_words`

the [example config](https://github.com/epi052/feroxbuster/blob/main/ferox-config.toml.example) is a good reference for config names/values

**Comment by clem9669** [comment]
My bad ! I did not see the new config file ...
Thanks @epi052 👍
