### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by DonatoReis** [epi052/feroxbuster#544]
**Describe the solution you'd like**
Hello, @epi052  could you add a function to delete code status.

**Describe alternatives you've considered**
example:

--exclude-code 404-499,500-599
or
--exclude-code 301 404 500

this will make it a lot easier

**Comment by epi052** [comment]
Hey there, thanks for taking the time to submit an issue! 

it seems that you're looking for `--filter-status`

docs: https://epi052.github.io/feroxbuster-docs/docs/examples/filter-status/#filter-response-by-status-code

Let me know if I'm mistaken, thanks again!

**Comment by DonatoReis** [comment]
> Hey there, thanks for taking the time to submit an issue!
> 
> it seems that you're looking for `--filter-status`
> 
> docs: https://epi052.github.io/feroxbuster-docs/docs/examples/filter-status/#filter-response-by-status-code
> 
> Let me know if I'm mistaken, thanks again!
..............................................................................................................................................................

But I can not pass a list of code to remove ? @epi052 

example:
--filter-status 404-499 500-599

it would be very useful that way, instead of going through one by one in the command line

**Comment by epi052** [comment]
so, you're requesting the range syntax to be available for numeric filters? 

To get similar results, you can only allow what you want to see: 

```--status-code 200 301 307```

that would block everything that's not 200, 301, or 307. I understand that the underlying request would be the same, but, in the interim, this would be the best way to go about excluding a large swath of response codes.
