### ISSUE TITLE
[FEATURE REQUEST] Support checking for wordlists in /usr/local/share/seclists

### ISSUE THREAD

**Issue by postmodern** [epi052/feroxbuster#548]
Not all users have the [seclists](https://github.com/danielmiessler/SecLists) collection of wordlists installed in `/usr/share/seclists` and not all users use KaliLinux, which I assume provides this set of wordlists by default. It is also not advised to manually install software into `/usr`, but instead manually installed software should go into `/usr/local`. Thus, feroxbuster could simply check `/usr/local/share/seclists/` for the default wordlist file (`seclists/Discovery/Web-Content/raft-medium-directories.txt`) if `/usr/share/seclists/` does not exist.

**Comment by epi052** [comment]
hey there, thanks for taking the time to file an issue! 

> ... KaliLinux, I assume provides this set of wordlists by default

if on kali, and installed via apt, the seclists project is brought in as a dependency. So, more or less, yes.

I don't mind putting the additional check in, but I'm going to hold off until a larger piece of code gets merged in. At that point, this can be added with very little effort. 

Thanks again!

**Comment by epi052** [comment]
@all-contributors please add @postmodern  for ideas
