### ISSUE TITLE
[BUG] tokio-runtime-worker' panicked at 'called `Option::unwrap()

### ISSUE THREAD

**Issue by jhaddix** [epi052/feroxbuster#563]
**Describe the bug**

When passing the tool a large list from STDIN:

`cat URLs |grep -v SOMEURL| /usr/bin/feroxbuster --stdin -r --auto-tune -k --silent -o bigCDrun`

I get the error:

`thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/scanner/requester.rs:131:14`

Any thoughts?

**Comment by epi052** [comment]
hmmm, has something to do with `--auto-tune`. 

I'll try to reproduce, but in the interim, just removing that option should allow you to get back to what you were doing. Below is a snippet from the docs and is what you're losing out on without that particular option. 

Also, if you're willing to accept some unsolicited advice, you may be leaving a lot on the table by not using `--extract-links`, which does the following
- parses Allow/Disallow from robots.txt
- parses `a:href`, `img:src`, `form:action`, `script:src`, `iframe:src`, `div:src`, `frame:src`, `embed:src` tag attributes from html
- applies linkfinder regex to any found asset, i.e. catch inline JS from html as well as from *.js files found
- detect directory listing and parse the links found therein

Even though that sounds like a lot, the performance hit is negligible, especially for the amount of stuff it finds. I assume you're doing all of this one way or another, but it can all be done in one-shot with `-e`.  

---- auto-tune docs snippet ----
The `--auto-tune` policy enforces a rate limit on individual directory scans when one of the criteria below is met.

- number of general errors (timeouts, etc) is higher than half the number of threads (or at least 25 if threads are lower) (per directory scanned)
- 90% of responses are 403|Forbidden (per directory scanned)
- 30% of requests are 429|Too Many Requests (per directory scanned)

The rate limit self-adjusts every (`timeout` / 2) seconds. If the number of errors have increased during that time, the allowed rate of requests is lowered. On the other hand, if the number of errors hasn’t moved, the allowed rate of requests is increased. If no additional errors are found after a certain number of checks, the rate limit will be removed completely.

**Comment by epi052** [comment]
follow up: 

I'm not able to reproduce this. Can you reliably reproduce with your list of urls? I understand if you can't throw a bunch of requests at them again, lol. 

How many urls are in your list (after the grep)? 

The item that `.unwrap()`'d to `None` is the object that controls the leaky bucket algorithm used for rate limiting. I'm trying to figure out how one of them could missed being instantiated (doesn't look like that should ever happen, but obviously it can... lol)

**Comment by epi052** [comment]
this was fixed in 2.7.1, just forgot to close it out
