### ISSUE TITLE
[FEATURE REQUEST] Extension Parameter, allow prepending .

### ISSUE THREAD

**Issue by IppSec** [epi052/feroxbuster#569]
**Is your feature request related to a problem? Please describe.**
When adding extension to searching, if you specify .extension then Feroxbuster will look for file..extension. I can't think of any use case where you would want a double period.

**Describe the solution you'd like**
For "-x .php" and "-x php" to behave identically

**Describe alternatives you've considered**
I could be less stubborn and just learn the "feroxbuster" way, but think the tool should be accepting of both.

**Additional context**
Gobuster allows for either format :)

**Comment by epi052** [comment]
agreed on the double period. i've been letting smaller things like this pile up until there's enough to warrant a relese, but i can add this to the next one easily.

**Comment by epi052** [comment]
also, it's only `the "feroxbuster" way` because noone asked for the additional flexibility :joy:
