### ISSUE TITLE
Could not open 

### ISSUE THREAD

**Issue by lollipophacker1337** [epi052/feroxbuster#576]
Hello,

I am trying to use feroxbuster for like an hour but every time I am trying to set a wordlist it's giving me the error Could not open.

![Screenshot_53](https://user-images.githubusercontent.com/50530367/168174858-4bf62239-b129-421f-a48c-6064b6721c68.png)

I tried a few things but nothing works. I tried to run the command location where the wordlist is but that didn't work. Gave commands like "php.txt" without any "/" tried ~/php.txt also used other wordlists too nothings work.

the last thing I tried is when we don't give any wordlist the default wordlist it takes is "/usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt" So I created directory into the usr directory with all the directories and create download the raft-medium-directories.txt file into the web-content directory but got the same error even when the default wordlist exists on the directory.

also, I didn't use the snap command to install I used "curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/master/install-nix.sh | bash" this command to use install.  Mention this because have read in other issues that it happens to someone because of using the snap command to install the feroxbuster.

Thanks

**Comment by epi052** [comment]
Hey, just checking in. Did you get this resolved?
