### ISSUE TITLE
[BUG] --auto-tune won't back-off on HTTP 500's

### ISSUE THREAD

**Issue by nestedfunction** [epi052/feroxbuster#577]
**Describe the Bug**
The --auto-tune feature does not seem to recognise HTTP 500's as errors, and does not seem to back-off even when the target is overloaded and starts returning 500 to [almost] every request.

Running feroxbuster on default performance settings (--threads 50 --timeout 7 --scan-limit 0) overloaded the backend database server for a target site, and caused the web server to keep returning 500's.

Enabling --auto-tune did not seem to improve this. Requests went out at the same (or even increased?) speed, marking off almost every URL as a 500 when it could have returned something else if given time to recover.

Have also briefly tried --auto-bail with same effect.

-----

**Steps to Reproduce**

Version: feroxbuster 2.7.0 (feroxbuster/kali-rolling,now 2.7.0-0kali1 amd64)

1. Run:

```
feroxbuster --url $target --auto-tune --threads 50 --timeout 7 --scan-limit 0 --wordlist $wordlist
## Note that above numbers are default values, specified here for clarity.
```

2. Wait for the overloaded target to start returning 500's.

3. Observe that feroxbuster does not slow or back-off, despite target being knocked out of service.

-----

**Expected Behavior**
The --auto-tune (and --auto-bail) option should back-off (or bail) upon receiving a string of 500's.

-----

**Comment by epi052** [comment]
hey there and thank you for the report! 

which version of ferox are you using?

**Comment by epi052** [comment]
Also, this isn't a bug, per se. The auto-tune/bail features are designed to handle 403/429 responses and general networking errors such as timeouts. 

Http response codes that are also errors (401, 404, 500, etc...) are not factored in to the policies.
