### ISSUE TITLE
[BUG] url was provided more than once, but cannot be used multiple times

### ISSUE THREAD

**Issue by tbennett6421** [epi052/feroxbuster#586]
**Describe the bug**
Seems to be a parsing issue when reading in the command line arguments

**To Reproduce**

The following command triggers this
`feroxbuster --thorough --parallel 2 -o ferox.txt -v --url http://192.168.1.100:8080/`

**Expected behavior**

**Traceback / Error Output**
```sh
feroxbuster --thorough --parallel 2 -o ferox.txt -v --url http://192.168.1.100:8080/
error: The argument '--url <URL>' was provided more than once, but cannot be used multiple times

USAGE:
    feroxbuster [OPTIONS]

For more information try --help
```

**Environment (please complete the following information):**
```sh
# Version
feroxbuster -V
feroxbuster 2.7.0
```

```sh
# OS
lsb_release -a
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.2
Codename:       kali-rolling
```

**Additional context**
Just going off the help output, it does not seem indicate any specific positional order to passing in arguments. If there is a desired or required order then the help screen should properly show the format of the expected invocation

**Comment by tbennett6421** [comment]
This appears specifically related to specifying the --parallel option, as reording the parameters resulted in the same message. Removing --parallel ultimately allowed the scan to run.

**Comment by epi052** [comment]
hey there, thanks for the report! Fortunately, this isn't a bug. 

From the docs:
> `--parallel` spawns a child process for each target passed in over stdin (recursive directories are still async within each child process).

The normal invocation of a parallel scan is something like this:
```cat large-target-list | ./feroxbuster --stdin --parallel 10 --extract-links --auto-bail```

Which would produce a process list something like this: 
```
feroxbuster --stdin --parallel 10
 \_ feroxbuster --silent --extract-links --auto-bail -u https://target-one
 \_ feroxbuster --silent --extract-links --auto-bail -u https://target-two
 \_ feroxbuster --silent --extract-links --auto-bail -u https://target-three
 \_ ...
 \_ feroxbuster --silent --extract-links --auto-bail -u https://target-ten
```

If you want to control the amount of threads / speed while scanning a single url (which appears to be what you were doing given the command you listed), you would use `-t|--threads`

**Comment by tbennett6421** [comment]
Thanks, that makes sense. Love the tool!
