### ISSUE TITLE
[FEATURE REQUEST]  is that even possible?

### ISSUE THREAD

**Issue by kolet** [epi052/feroxbuster#595]
hi ,

i have 2 sets of payload .
first payload is a wordlist .
second payload numbers . 0000-9999 (bf)

i'd like for the scan to stop the BF on  a line when matching a redirect(status code 302)  or length (greater then normal)
so instead of continue going through 10k for each line in payload 1 (wordlist) 
it will stop and continue with the other lines . 
how can i accomplish that ? 

thanks !

**Comment by epi052** [comment]
hi @kolet; there's no built-in way to accomplish what you're asking. i don't think any similar tools do this out of the box either. You're most likely looking at scripting out a solution that wraps ferox, or simply letting the scan run to completion and looking at the results after.

**Comment by kolet** [comment]
hi ! @epi052  
thats unfortunate 
i think adding such feature would be great .

if you think about how much time can be saved here .
if you have 1000 lines and you go into each iteration  10k (0000-9999) thats 10mil requests that has to go through and be received by the website you doing the recon/attack on .
this is alot .

adding such characteristic would save ALOT of time . 
like if response is greater then or lower then , or error codes ..

lets take my situation for example  .

when 302 reach i know i have the right "info" and i dont need to keep looking into the line of the 1000 , therefor saving the request amount that lefts for that line .
now multiple that by the amount of lines \ iteration  this is huge .

and mine is quiet easy , doing that on 2 wordlists with 10k on each one we already reached 100mil requests .

**Comment by epi052** [comment]
@kolet this is exactly the kind of problem that my (unreleased) project solves. Your request here will be one of the examples provided with the library once it's public. 

https://twitter.com/epi052/status/1548335872868634626
