### ISSUE TITLE
Fuzzing terminate due to unknow stack trace error

### ISSUE THREAD

**Issue by amiralkizaru** [epi052/feroxbuster#60]
**Describe the bug**
Hello 
Thank you for the awesome tool

I've been encountering this issue when fuzzing a url it abort the fuzzing and throw so unknow errors
**To Reproduce**
1. Downloaded the latest relases
2. Made an alias for automation looks like this 
```
fastfuzz> # Defined in /root/.config/fish/functions/fastfuzz.fish @ line 1
          function fastfuzz
              feroxbuster --url $argv -w /opt/SecLists/Discovery/Web-Content/dic.txt -d 3 -x html,aspx,php,asp,log
          end
```
Works in fish
3. I run fastfuzz <target>

**Expected behavior**
Bruteforce recursively and print out results

**Traceback / Error Output**
```
[>-------------------] - 8m     44744/1018686 85/s    http://95.163.33.203/
thread 'tokio-runtime-worker' panicked at 'Already joining!', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/indicatif-0.15.0/src/progress.rs:1035:13
stack backtrace:
   0:           0x679af8 - <unknown>
   1:           0x48d8ec - <unknown>
   2:           0x6791a6 - <unknown>
   3:           0x678baa - <unknown>
   4:           0x678431 - <unknown>
   5:           0x533e94 - <unknown>
   6:           0x53fbca - <unknown>
   7:           0x4e8dea - <unknown>
   8:           0x68d290 - <unknown>
   9:           0x68d025 - <unknown>
  10:           0x6873c5 - <unknown>
fish: Job 1, 'feroxbuster --url $argv -w /opt…' terminated by signal SIGABRT (Abort)
```

**Environment (please complete the following information):**
 - feroxbuster version: 1.0.0
 - OS [WSL 1]

**Comment by epi052** [comment]
Good morning!

Thank you for filing this bug report.  I pushed an update to address this problem yesterday.  Can you try the same scan with `feroxbuster` version `1.0.1`?  

You can check the version by running:

```
./feroxbuster -V
feroxbuster 1.0.1
```

I strongly suspect you're using version `1.0.0`.  Can you please confirm?

**Comment by amiralkizaru** [comment]
Hello @epi052 

Thank you for your fast reply 
Yes Indeed I'm using 1.0.0
I'm currently running some fuzzing will see if the same occurs or it fix 

I'll update you in an hour

Regards

**Comment by amiralkizaru** [comment]
Looks like the issue is fixed @epi052 

I just have a small question
Is there any way to not show the timeout URLs ?

![quiet](https://user-images.githubusercontent.com/32225186/95245312-dd465000-080a-11eb-9c5b-64482d0165aa.png)

The quiet will suppress the status and everything ...

Regards

**Comment by epi052** [comment]
great! glad to hear that particular issue is resolved. 

your screenshot cuts off the right-most information.  Are those all timeouts? 

If so, we could make them warnings, then you'd only see them when `-v` is used. 

Would you mind opening a new issue for that, if it sounds like an agreeable solution?  

I'm closing this issue, since `v1.0.1` already addresses the initial problem.
