### ISSUE TITLE
Program Seems to Fail When Line Feed Delimited Input is Given via STDIN[BUG] 

### ISSUE THREAD

**Issue by edwinfred** [epi052/feroxbuster#605]
Feroxbuster gives a
`WRN     58.365 feroxbuster::utils Error while making request: error sending request for url (https://example.com/): operation timed out
WRN     58.365 feroxbuster::utils err: error sending request for url (https://example.com/): operation timed out`
error when a file is given in through stdin, in which the URLs are `\n` delimited. (When `-vvv` option is specified).

It appears to be working perfectly when provided with a file whose contents are` \r\n` delimited.

**Comment by edwinfred** [comment]
Apologies, it seems that I used a fairly long list of hosts (1200+ hosts) with LF delimitation and a very small list (20+ hosts) with CRLF delimitation, and the size of the list seems to be the factor causing the scans to fail. Still could consider this an issue, but the initial bug I reported is inaccurate, therefore closing the issue.

**Comment by epi052** [comment]
no worries! with that many targets, you may want to try `--parallel N`. I think it might be more friendly for huge amounts of targets
