### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by amiralkizaru** [epi052/feroxbuster#61]
**Is your feature request related to a problem? Please describe.**

When you fuzz you need the most confortable output in order to analyze the results 
When the request timeout it's shows in the output without any `-v` used

**Describe the solution you'd like**
I would like if possible a flag to supress this timeout urls and leave only the status code and useful information in the output

**Screenshot**
![githubissue](https://user-images.githubusercontent.com/32225186/95252309-c0167f00-0814-11eb-8c71-3f5efdf2feac.png)

**Comment by epi052** [comment]
ill take a look at this tonight

**Comment by epi052** [comment]
@amiralkizaru 

A few things here.  

1. your screenshot doesn't show a timeout, were you seeing timeouts 
2. if, on another scan, you were getting a bunch of timeouts, it's probably indicative that you should use a fewer number of threads to scan, i.e. `-t 25` 

With that being said, I'm ok with logging timeouts as a warning, but leaving other errors (like a Connection Refused, as shown in your screenshot) logged as errors.  

That means that timeouts can be seen with a `-v`, but won't be seen without it.  Actual errors still can only be suppressed with `-q`.  

You can take a look at the changes here https://github.com/epi052/feroxbuster/pull/62

Let me know what you think

**Comment by epi052** [comment]
closed in 4b4af5a303f292625b2b795ead409623fa369221
