### ISSUE TITLE
./feroxbuster --help Bus error

### ISSUE THREAD

**Issue by ymeteadsoajwndan** [epi052/feroxbuster#617]
**Describe the bug**

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Traceback / Error Output**
If applicable, add error output to help explain your problem.

**Environment (please complete the following information):**
 - feroxbuster version: [e.g. v1.0.1]
 - OS [e.g. ubuntu 20.04]

**Additional context**

**Comment by epi052** [comment]
did you ever get this sorted? to have any hope of helping, i need more information than what you've provided
