### ISSUE TITLE
automatic recursion takes down my home connection 

### ISSUE THREAD

**Issue by asempire** [epi052/feroxbuster#626]
I love this tool so much and the recursion feature is so handy, but the problem is that once a response code eligible for recursion is received it starts a new thread immediately along side the main thread which throttles weak connections and overload my home router. I made a bash script to make ferobuster brute force each response code (403 or 401 for example) one by one after it has finished the initial task on the main domain with the --no-recursion flag. It would be so convenient if such workflow is implemented directly to the tool so that weak hardware can handle (I also tried to lower the threads to the bare minimum but the connection kept going down).

**Comment by epi052** [comment]
Sounds like you've reimplemented -L 🙃

You likely want some combination of

-L

**Comment by epi052** [comment]
https://epi052.github.io/feroxbuster-docs/docs/examples/rate-limit/

https://epi052.github.io/feroxbuster-docs/docs/examples/limit-scans/

**Comment by epi052** [comment]
https://epi052.github.io/feroxbuster-docs/docs/configuration/limit-connections/

**Comment by epi052** [comment]
Sorry, typing on my phone while walking lol

**Comment by asempire** [comment]
alright that seems awesome especially the scan limit flag. should've tested those a little bit more 😅 sorry about that and thanks a lot l!

**Comment by epi052** [comment]
hey, back at home now, just wanted to say that i'm glad you like ferox and are getting use out of it :heart: thanks for taking the time to submit an issue!
