### ISSUE TITLE
[BUG] MINOR: methods not being honored from ferox-config.toml file but working from CLI

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#644]
**Describe the bug**

The `methods` option in `ferox-config.toml` is not being honored. I tried to double-check this wasn't pilot error, but I don't see much room for me to be screwing this one up as I copied it directly from the example config. If I am screwing this up somehow, I apologize in advance :>

**To Reproduce**

1. Use a build from the `main` branch (I build from source but I'm pretty sure the binary release will behave the same- I can test if you want); I used `cargo build --release`, which I believe is at least correct enough :>
2. Create a `ferox-config.toml` like the one below
3. Create a simple wordlist `testing.wl`
3. Run an httpd that makes it easy for you to see the requests being made by `feroxbuster` (e.g. `python2 -mSimpleHTTPServer 9333`)
4. Run `feroxbuster -u http://127.0.0.1:9333`
5. Observe that there are no `POST` requests made in one of several ways; easiest way is to look at your testing HTTP server output, which logs the verbs/methods

To demonstrate that there is not some other subtle issue at play, using `--methods POST` on the CLI with this same configuration/invocation does correctly emit `POST` requests

**Wordlist**

```
$ cat > testing.wl << 'EOF'
derp
api
v1
lol
```

**Contents of ferox-config.toml**

None of the following will produce `POST` requests, they all result in `GET` only:

```toml
wordlist = "testing.wl"
debug_log = "debug.log"
user_agent = "Sentinel User-Agent to make it clear the correct config was loaded hehe"
methods = ["POST"]
```

```toml
wordlist = "testing.wl"
debug_log = "debug.log"
user_agent = "Sentinel User-Agent to make it clear the correct config was loaded hehe"
methods = ["POST", "GET"]
```

**Expected behavior**

- With both of the above configurations, `POST` requests _should_ be made. All I see emitted are `GET` requests
- When I review `debug.log`, I see that `methods` is 
- Using `--methods GET,POST` or `--methods POST` on the command-line works as expected

**Debug Output**

When specifying `methods: ["POST"]` int he configuration file, I see the following in the `debug.log`:

```
› grep -B1 -A3 methods debug.log 
    extensions: [],
    methods: [
        "GET",
    ],
    data: [],
```

When specifying `--methods POST` via the CLI, I see what is expected:

```
› grep -B1 -A3 methods debug.log                        
    extensions: [],
    methods: [
        "POST",
    ],
    data: [],
```

**HTTPS Logs**

The HTTPD shows clearly that no `POST` requests were made when `methods = ["POST"]` is set in the `ferox-config.toml` file:

```
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /912a627bf78e415181f12e0e3b094787 HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /nah HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /sql HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /test HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /derp HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /api HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /ff55aa379781441dab8503e4a0755bfa HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /derp HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /sql HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /nah HTTP/1.1" 404 -
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /api HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:11:15] code 404, message File not found
127.0.0.1 - - [05/Sep/2022 10:11:15] "GET /test HTTP/1.1" 404 -
```

When using `--methods POST` on the CLI, it is clearly working (though I was too lazy to make a handler for `POST` in the server, it's irrelevant here, obviously)

```
127.0.0.1 - - [05/Sep/2022 10:13:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST /602fd4f21c9946e4a8609e78a5d53927 HTTP/1.1" 501 -
127.0.0.1 - - [05/Sep/2022 10:13:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST /sql HTTP/1.1" 501 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST /nah HTTP/1.1" 501 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST /test HTTP/1.1" 501 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST / HTTP/1.1" 501 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST /api HTTP/1.1" 501 -
127.0.0.1 - - [05/Sep/2022 10:13:02] code 501, message Unsupported method ('POST')
127.0.0.1 - - [05/Sep/2022 10:13:02] "POST /derp HTTP/1.1" 501 -
```

**Environment**

 - feroxbuster version 2.7.1
 - Built from master on 2022-09-05, git commit 53e3420
 - Built using `cargo build --release && cp
 - OS: Debian 11, x86_64

**Additional context**

This isn't a hard blocker obviously, so please don't feel you need to allocate immediate time/attention to it!!! If I have a chance I'll read through and maybe send a PR if it's simple enough, I'm nowhere near fluent in Rust, though I'm guessing for a behavior/bug like this, it's akin to a copy/pasta type issue and may be easy to track down

Also, to confirm I wasn't a dummy and somehow using the wrong configuration file, I put that user-agent sentinel value you in there, to match with the output when `feroxbuster` boots:

```
10:03:59 › feroxbuster --url http://127.0.0.1:9333 --methods POST

 ___  ___  __   __     __      __         __   ___
|__  |__  |__) |__) | /  `    /  \ \_/ | |  \ |__
|    |___ |  \ |  \ | \__,    \__/ / \ | |__/ |___
by Ben "epi" Risher 🤓                 ver: 2.7.1
───────────────────────────┬──────────────────────
 🎯  Target Url            │ http://127.0.0.1:9333
 🚀  Threads               │ 50
 📖  Wordlist              │ testing.wl
 👌  Status Codes          │ [200, 204, 301, 302, 307, 308, 401, 403, 405, 500]
 💥  Timeout (secs)        │ 7
 🦡  User-Agent            │ Sentinel User-Agent to make it clear the correct config was loaded hehe
 💉  Config File           │ /home/user/projects/feroxbuster/ferox-config.toml
 🪲  Debugging Log         │ debug.log
 🏁  HTTP methods          │ [POST]
 🔃  Recursion Depth       │ 4
───────────────────────────┴──────────────────────
 🏁  Press [ENTER] to use the Scan Management Menu™
──────────────────────────────────────────────────
[####################] - 0s         6/6       0s      found:0       errors:0      
[####################] - 0s         6/6       481/s   http://127.0.0.1:9333 
```

As always, thanks for the great work you've done on this project, and continue to do. Killer stuff

**Comment by epi052** [comment]
Nice catch! 

I just pushed a change that should fix this. Lmk if it's resolved on your end.

**Comment by mzpqnxow** [comment]
Resolving, looks good- I now see the expected behavior when `ferox-config.toml` contains `method = ["POST"]` or `["POST", "GET"]`

Thanks!

**Comment by epi052** [comment]
Anytime, glad to hear it!
