### ISSUE TITLE
Typo in `--help` with missing one "-" at line 690 for flag `--threads` 

### ISSUE THREAD

**Issue by gyrusdentatus** [epi052/feroxbuster#660]
https://github.com/epi052/feroxbuster/blob/ccb10c1c6810be2bc1f48d4b02c13416fc6ef5aa/src/parser.rs#L690

I know I am annoying but wanted to use this right away and I hate when people use `-<command` instead of using double-dash, good to know this is not the case and just a typo ...:) 
Do not think it is worth it to open a PR for this tiny tiny typo! Looking forward to testing this beauty! Thanks

**Comment by epi052** [comment]
Howdy, and thanks for this! It's not annoying at all, and I'd prefer there to not be typos. 

Pushing a change to `main` here shortly, but the change won't be present until the next release.

Thanks again!
