### ISSUE TITLE
Request -Q but with mini progress, to see how much is left

### ISSUE THREAD

**Issue by swordfish0x0** [epi052/feroxbuster#663]
**Is your feature request related to a problem? Please describe.**
sort of. with out -q I get to much progress, with -q I get no progress. 

**Describe the solution you'd like**
under the -q output I'd like a single general progress bar, maybe a -q+ or something switch, or even an "estimated time to complete" line. 

**Describe alternatives you've considered**
Another option would be to be in the Scan Management Menu show the remaining time as some general status. 

**Additional context**

**Comment by epi052** [comment]
howdy, and thanks for the submission! 

both `--quiet` and `--silent` behave how they do for specific purposes.

`--quiet` is good for tmux windows that have notifications enabled, as the only updates shown by the scan are new valid responses and/or new directories found that are suitable for recursion.

`--silent` is good for piping a list of urls to other commands.

Of your two suggestions, i'd be fine with either one. The main concern being that we don't break `--quiet` workflows for any folks already using it.

i don't plan on prioritizing this over what I'm currently working, but would happily accept a pull request!

pinning it for now, and thank you again!

**Comment by epi052** [comment]
hey there, thanks for the suggestion! Adding time remaining to scan management was pretty easy so i rolled it into the most recent release.

**Comment by epi052** [comment]
@all-contributors add @swordfish0x0 for ideas
