### ISSUE TITLE
[ENHANCEMENT] Homebrew installations should place a config file during installation

### ISSUE THREAD

**Issue by Teicu** [epi052/feroxbuster#69]
Hi 

I just installed the tool via Homebrew on Mac 

Now I need help to find the ferox-config.toml on my Mac, to add the wordlist path. 

Thanks

**Comment by epi052** [comment]
Hey there, 

The homebrew installs don't pull down the config (which is probably an oversight).  For now, you can download [the example](https://github.com/epi052/feroxbuster/blob/master/ferox-config.toml.example) from the top level of this repository.  After that, you can put it in either:

- /etc/feroxbuster
- ~/.config/feroxbuster 
- the same directory as feroxbuster
- your current directory

Once placed, edit to your heart's content. 

Let me know if you have any other questions.

Thanks for checking out the tool!

**Comment by epi052** [comment]
I'm going to hijack this issue in order to track adding the config file to the homebrew installs.

**Comment by epi052** [comment]
By the way, I assumed initially that you wanted a static configuration of your wordlist.  

In the event you just want to specify a wordlist at runtime, you can use the `-w|--wordlist` flag.

```
./feroxbuster --url http://example.com --wordlist /path/to/some/wordlist
```

**Comment by epi052** [comment]
Closed in https://github.com/TGotwig/homebrew-feroxbuster/pull/2 and https://github.com/TGotwig/homebrew-linux-feroxbuster/commit/58937f962ec2368bf92eb0c5020a79404fc0d1ac
