### ISSUE TITLE
extract links option partially working for the initial target URL

### ISSUE THREAD

**Issue by epi052** [epi052/feroxbuster#705]
@epi052 Hey I was also looking at this machine and noticed that the extract links option is not working for the initial target URL.
I thought it was just because the filtered was not captured `<link hrefs=` but adding that in, did not do the job. Example below:
`<link href="/js/app.js" rel="preload" as="script"><link href="/js/chunk-vendors.js" rel="preload" as="script">`

Add to line 215 in src/extractor/container.rs:
```rust
self.extract_links_by_attr(resp_url, links, html, "link", "href");
```

I was analyzing the code and looks like the robots and directory heuristic are the only ones run on the initial target URL and then dumped into looping with words for the input wordlist. Not sure if its because this was matching the wildcard test. Let me know what you think.

I can open up a new issue for this if more appropriate.

_Originally posted by @godylockz in https://github.com/epi052/feroxbuster/issues/689#issuecomment-1290667906_

**Comment by epi052** [comment]
@godylockz 

looked at this today, yes, the issue was that the initial response was being filtered due to the wildcard response.

if you add the code below to `src/scanner/requester.rs:446`
```
log::error!("extracting: {:?}", ferox_response.url().as_str());
``` 

and run the scan with `-e --dont-filter`, you'll see the initial url trigger the extraction logic.

**Comment by epi052** [comment]
added <link> extraction tho :grin: closing this one, thanks! 

```
self.extract_links_by_attr(resp_url, links, html, "link", "href");
```

**Comment by godylockz** [comment]
Thanks boss 👍
