### ISSUE TITLE
Redirect rules

### ISSUE THREAD

**Issue by aasyria** [epi052/feroxbuster#720]
Hey everybody,
sometimes I want that the redirect flag to stay enabled, but excludes the redirect to some defined Host header. Is that possible, right now.
For example, I am testing a website that using external login provider, but it is not allowed to scan the external links, that is why I want to exclude that.
thanx
:D

**Comment by epi052** [comment]
[`--dont-scan`](https://epi052.github.io/feroxbuster-docs/docs/examples/deny-list/) is probably what you're looking for

**Comment by aasyria** [comment]
i tried this and did not work 
this was my command :
```
#!/usr/bin/env zsh
cat aquatone_urls.txt |feroxbuster --stdin --silent --redirects --burp --timeout 3 --auto-bail --force-recursion --rate-limit 5 --threads 6 -w ./base.fuzz.txt --output ./enum/result.txt  --collect-extensions --dont-collect js jpg png -s 200 302  --dont-scan xxx.xx 
```

**Comment by aasyria** [comment]
OK, 
i looked in to the code the redirect is new scan for the location header and the don't scan is regx that is mean if disable the --force-recursion and used regx , it is working .
````
#!/usr/bin/env zsh
cat aquatone_urls.txt |feroxbuster --stdin --silent --redirects --burp --timeout 3 --auto-bail --rate-limit 5 --threads 6 -w ./base.fuzz.txt --output ./enum/result.txt  --collect-extensions --dont-collect js jpg png -s 200 302  --dont-scan 'regx'
````
