### ISSUE TITLE
Could not open Wordlist 

### ISSUE THREAD

**Issue by mjulda** [epi052/feroxbuster#724]
I'm a Windows user getting an error -> Could not open .\SecLists\Discovery\Web-Content\raft-medium-directories.txt

I browsed to the directory -> C:\Users\Bray\AppData\Roaming
But it doesn't find -> ferox-config.toml

But still error too.

**Comment by epi052** [comment]
howdy! 

the wordlists aren't provided with feroxbuster, it's expected that you provide your own. The default location on windows is 

```
#[cfg(target_os = "windows")]
pub const DEFAULT_WORDLIST: &str =
    ".\\SecLists\\Discovery\\Web-Content\\raft-medium-directories.txt";
```

however, if that doesn't fit your situation, you'll need to provide a path to your wordlist via the `-w` option.

similarly for the config file, it doesn't get installed automatically on windows. You'll need to create one with your config and then drop it in one of 3 locations

- `C:\Users\Bray\AppData\Roaming\feroxbuster`
- The same directory as the feroxbuster executable
- your current working directory

**Comment by epi052** [comment]
closing this since there's no response. feel free to reopen if you need to

**Comment by revorun** [comment]
I have the same problem 
the solution you added didn't help me

**Comment by epi052** [comment]
@revorun could you be more specific? which part of the provided solution doesn't solve your problem? What exactly is the problem you're having?

**Comment by revorun** [comment]
![Screenshot 2024-06-21 204128](https://github.com/epi052/feroxbuster/assets/173461661/e9679195-8318-4c7f-80f4-9aaffca67540)

i am using WSL when i try to use feroxbuster that massage pops up 
itried to make the file .config but still didnt work 
i tried the solution you added it also didnt work 
 so i need help

**Comment by epi052** [comment]
the exact error you provided can be fixed with the following:
```
./feroxbuster -u roknsh.com -w Downloads/common.txt
```

WSL is linux and the backslash character (`\`) is special to the executing shell.

**Comment by revorun** [comment]
![Screenshot 2024-06-21 231358](https://github.com/epi052/feroxbuster/assets/173461661/1a0ae782-cef1-473b-9f95-acca5f9c09dd)
i tried it but still didnt work

**Comment by epi052** [comment]
does that file exist? can you run the following commands

```
pwd
ls -al
ls -al Downloads
```

**Comment by revorun** [comment]
it must exist but it is deosnt in the WSL how can make it exist??

![Screenshot 2024-06-21 235937](https://github.com/epi052/feroxbuster/assets/173461661/0713b2a3-33a6-4b3a-be85-8ca49f549b79)

**Comment by epi052** [comment]
try
```
ls /mnt/c/Users/<YOUR_WINDOWS_USER_NAME>/Downloads/
```
if the file is there, point your `-w` to it.

you can also just symlink your windows downloads folder into a friendlier location in wsl
```
ln -s /mnt/c/Users/<YOUR_WINDOWS_USER_NAME>/Downloads ~/downloads
```
