### ISSUE TITLE
Request for full link output

### ISSUE THREAD

**Issue by hakdogpinas** [epi052/feroxbuster#743]
Can I request to have full link instead of just outputting the path?
what I wanted is to have https://secure.indeed.com/settings/account instead of =>
![image](https://user-images.githubusercontent.com/71529469/208992347-103b05f8-70d9-4d53-8684-cf6207787f0b.png)

**Comment by hakdogpinas** [comment]
The output is ok if it's 200, but if it's 302 response the output will is =>. Any possible workaround?

**Comment by epi052** [comment]
Sorry for the long reply time. That info may be available with some of the output/logging options. I'd have to dink with it to see tho

**Comment by epi052** [comment]
@all-contributors add @hakdogpinas for ideas

**Comment by epi052** [comment]
https://github.com/all-contributors add @hakdogpinas for ideas

**Comment by epi052** [comment]
@all-contributors add @hakdogpinas for ideas

**Comment by hakdogpinas** [comment]
Thank you so much

**Comment by epi052** [comment]
It's np. For the record, it was just displaying the Location header. So, sometimes it was an absolute url and sometimes it wasn't, it just depended on the response. This way it should just always be absolute
