### ISSUE TITLE
[FEATURE REQUEST] Save canceled scans to state file

### ISSUE THREAD

**Issue by n0kovo** [epi052/feroxbuster#748]
When running feroxbuster and manually canceling the scan of certain URLs using the Scan Management Menu, the canceled-state of those URLs are not saved to the .state-file when Ctrl-c'ing to stop the scan. So when resuming the scan using `--resume-from file.state`, feroxbuster will start scanning all URLs including those that were canceled before saving the state.

It would be very convenient to have feroxbuster remember what URLs we don't want to scan. Remembering what URLs are irrelevant can be hard for the user when resuming a scan after a while, and manually canceling the scans again can be a pretty tedious task.

**Comment by epi052** [comment]
Howdy! Agreed, a scan being cancelled should be saved in the state file. Will take a look. Thanks for submitting the issue!
