### ISSUE TITLE
`--auto bail` on the banner isn't aligned properly

### ISSUE THREAD

**Issue by epi052** [epi052/feroxbuster#774]
![image](https://user-images.githubusercontent.com/6473725/213772892-9d31f7c2-5990-4a22-80a6-c2e746cda152.png)

_Originally posted by @joaociocca in https://github.com/epi052/feroxbuster/discussions/773#discussioncomment-4739933_

**Comment by joaociocca** [comment]
one day I'll get the hang of what to make an issue and what to keep as discussion 😅

**Comment by epi052** [comment]
Not a problem at all! Just wanted it out of discussion to track, since it's a confirmed bug. 

There's no right or wrong, as long as I get the info 😁

**Comment by epi052** [comment]
@all-contributors add @joaociocca for bugs and ideas
