### ISSUE TITLE
[NON-IMPACTING IMPERFECTION] Stale reference to debian/cargo.config breaks (unsupported) use of make

### ISSUE THREAD

**Issue by mzpqnxow** [epi052/feroxbuster#782]
**Describe the imperfection**

This is not a bug and it doesn't need any corrective action. It might be a "cleanup", though- either removing a line from the `Makefile` or removing the entire file if it's not actually used anymore

Here's the problematic target from the `Makefile`, specifically the `cp debian...` command:

```
$(TARGET)/$(BIN): extract
	mkdir -p .cargo
	cp debian/cargo.config .cargo/config.toml
	cargo build $(ARGS)
```

The `debian/` directory is no longer in the feroxbuster repo, I believe because you moved what was in it into the main `Cargo.toml` file at some point. Because `make` is all about the zeros and non-zeros, `make` fails before building

Should that `cp debian..` line be removed the `Makefile`? I'm not asking that you support users building via `make` (unless you really want to) but I figured if the `Makefile` is going to be present, might as well make it work, right?

I only stumbled upon this because I had to add `feroxbuster` to some build automation stuff that has a lot of applications with the traditional `configure && make && make install` pattern. At that time I noticed that there was a `Makefile` with `feroxbuster`. I usually just use `cargo` directly and it works very well, but I thought maybe there was an opportunity to make things look more uniform :)

I apologize for taking your time up with something so trivial. Feel free to close with a "kthxbye" and no action taken. If you still use the `Makefile`, maybe you'll want to just remove that line. Or maybe the `Makefile` is completely moribund at this point and it can be destroyed?

Until this _**CRITICAL FLAW**_  is corrected, I will be forced to continue using `cargo build --release && cp target/release/feroxbuster /opt/$APPS/bin/` - a real tragedy :)

Thanks again for all your work on this project

**Comment by epi052** [comment]
ha! thanks for this. It's from when i was getting ferox ready to be added to the kali repos. I THINK they don't need this anymore, but, to be on the safe side, i fixed up the makefile in such a way that if they are relying on this one, it won't break anything AND it should be fixed in the future if anyone else runs make :grin:
