### ISSUE TITLE
[FEATURE REQUEST] Auto Update feature

### ISSUE THREAD

**Issue by aancw** [epi052/feroxbuster#812]
**Is your feature request related to a problem? Please describe.**
For now, feroxbuster only show the message "new release available" and user need to manual download

**Describe the solution you'd like**
Implementing auto update feature when user supply `--update` argument. It will download, unzip, and replace existing binary.

**Describe alternatives you've considered**
Implementing auto update feature when user supply `--update` argument. It will download, unzip, and replace existing binary.

![image](https://user-images.githubusercontent.com/6284204/223905325-667317aa-11d6-4ca7-bbd0-7bc2df7b40ca.png)

**Comment by aancw** [comment]
I'm working on this feature. Still testing in local, will push to new branch when ready.

**Comment by epi052** [comment]
ha! you're awesome :partying_face: 

adding a new command line option takes a lot of small changes. I made a checklist early on to help me (and others) find those quickly. You may not need every single one of these, but it should be helpful.

Add new command line option checklist
- [ ] config.rs
    - [ ] add new value to `Configuration` struct
    - [ ] update `Configuration::default` with new value
    - [ ] update `Configuration` docstring with the new value/default (if appropriate)
    - [ ] update `Configuration::new` so that the new value is stored in `config`
    - [ ] update `Configuration::merge_config` with new value
    - [ ] update `Configuration::tests::setup_config_test` with new value
    - [ ] add unit test to check config parsing
- [ ] ferox-config.toml.example
    - [ ] add new value to example config
- [ ] banner.rs
    - [ ] add new check for the value in `banner::initialize`
    - [ ] create new entry to be written in the banner for the new value
        - [ ] add new emoji to the entry (should be somewhat related to the value name)
    - [ ] add new integration test (`tests/test_banner`) or update existing so that it's displayed under test
- [ ] Cargo.toml
    - [ ] bump version: add 1 to minor release and set patch release to 0
- [ ] README.md
    - [ ] update default config section (if needed)
    - [ ] update example config file section
    - [ ] update help output section
    - [ ] add an example with a heading that conforms to others (new in `v1.4.0`...)
        - [ ] add an entry for the example in the table of contents
- [ ] parser.rs
    - [ ] add the option to the parser
- [ ] wherever.rs
    - [ ] implement the new feature

**Comment by epi052** [comment]
> Sorry I don't know about the checklist. I'm only read your code and implement the new feature. Maybe if you don't mind, you can try the feature first and I will add as you requested on the checklist

yea, don't worry about it. I thought you were just starting to work on it. I glanced through and it looks good. I'll take a closer look tomorrow. Thank you again, that's a super nice feature!

**Comment by aancw** [comment]
This is my checklist for the new commit, please kindly check 😃 

Add new command line option checklist

* [ ]  config.rs
  
  * [x]  add new value to `Configuration` struct
  * [x]  update `Configuration::default` with new value
  * [x]  update `Configuration` docstring with the new value/default (if appropriate)
  * [ ]  update `Configuration::new` so that the new value is stored in `config`
  * [x]  update `Configuration::merge_config` with new value
  * [x]  update `Configuration::tests::setup_config_test` with new value
  * [x]  add unit test to check config parsing
* [x]  ferox-config.toml.example
  
  * [x]  add new value to example config
* [ ]  banner.rs
  
  * [x]  add new check for the value in `banner::initialize`
  * [x]  create new entry to be written in the banner for the new value
    
    * [x]  add new emoji to the entry (should be somewhat related to the value name)
  * [x]  add new integration test (`tests/test_banner`) or update existing so that it's displayed under test
* [x]  Cargo.toml
  
  * [x]  bump version: add 1 to minor release and set patch release to 0
* [ ]  README.md
  
  * [ ]  update default config section (if needed)
  * [x]  update example config file section
  * [ ]  update help output section
  * [x]  add an example with a heading that conforms to others (new in `v1.4.0`...)
    
    * [ ]  add an entry for the example in the table of contents
* [x]  parser.rs
  
  * [x]  add the option to the parser
* [ ]  wherever.rs
  
  * [ ]  implement the new feature
