### ISSUE TITLE
[BUG] Feroxbuster doesn't give an option to remove from scans manually added urls

### ISSUE THREAD

**Issue by sectroyer** [epi052/feroxbuster#816]
**Describe the bug**
Feroxbuster gives an option to add new scan urls via "Scan Management Menu". However there is no way to remove manually added urls via same menu from scans.

**To Reproduce**
1. Launch scan
2. Open "Scan Management Menu"
3. Add new url manually
4. Open "Scan Management Menu"
5. No way to remove

**Expected behavior**
If there is an option to add urls manually there should an option to remove them.

**Comment by epi052** [comment]
my local testing branch noted [here](https://github.com/epi052/feroxbuster/issues/818) fixes this
