### ISSUE TITLE
[FEATURE REQUEST] Ferxobuster doesn't cancel running scan doesn't work

### ISSUE THREAD

**Issue by sectroyer** [epi052/feroxbuster#818]
**Describe the bug**
Once scanning specific url is started cancelling it using "Scan Management Menu" doesn't work

**To Reproduce**
1. Start scan
2. Choose running url
3. Launch Scan Management Menu
4.  Cancel running url

**Expected behavior**
Cancelling running url should work

**Comment by epi052** [comment]
There was a reason it worked this way initially (it was due to limitations of the design). 

> https://epi052.github.io/feroxbuster-docs/docs/examples/cancel-scan/#add-or-cancel-a-recursive-scan-interactively
>
> ...
> Scans that are started via -u or passed in through --stdin cannot be cancelled, only scans found via --extract-links or recursion are eligible.

I fiddled with it a bit and got this to work in a local branch, but it'll need some testing to make sure the change didn't break anything. Thanks for filing this!
