### ISSUE TITLE
[BUG] Feroxbuster crashes when trying to resume from state file

### ISSUE THREAD

**Issue by sectroyer** [epi052/feroxbuster#819]
**Describe the bug**
I tried on two different machines and I get same result. I take original cmdline and change -u to --resume-from and give it a state file as an arguments. It starts "normally" I see urls parsed, etc. but after that I get this:
thread 'tokio-runtime-worker' panicked at 'range start index 206257 out of range for slice of length 107983', src/event_handlers/scans.rs:302:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

with RUST_BACKTRACE=1 I get:
thread 'tokio-runtime-worker' panicked at 'range start index 206257 out of range for slice of length 107983', src/event_handlers/scans.rs:302:33
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted

301      GET        7l       20w      244c https://example.com/flv => http://example.com/flv/
301      GET        7l       20w      248c https://example.com/ads => http://example.com/ads/
301      GET        7l       20w      243c https://example.com/ps => http://example.com/ps/
[####################] - 0s   1142938/0       0s      
thread 'tokio-runtime-worker' panicked at 'range start index 206257 out of range for slice of length 107983', src/event_handlers/scans.rs:302:33
stack backtrace:
   0:     0x7f580f7ea42c - <unknown>
   1:     0x7f580f5640be - <unknown>
   2:     0x7f580f7bd7f4 - <unknown>
   3:     0x7f580f7eb9ef - <unknown>
   4:     0x7f580f7eb5ef - <unknown>
   5:     0x7f580f7ec672 - <unknown>
   6:     0x7f580f7ec154 - <unknown>
   7:     0x7f580f7ec0bc - <unknown>
   8:     0x7f580f7ec091 - <unknown>
   9:     0x7f580f4be802 - <unknown>
  10:     0x7f580f562fa1 - <unknown>
  11:     0x7f580f4be896 - <unknown>
  12:     0x7f580f6194ab - <unknown>
  13:     0x7f580f617765 - <unknown>
  14:     0x7f580f613bfe - <unknown>
  15:     0x7f580f6125a6 - <unknown>
  16:     0x7f580f7f93a5 - <unknown>
  17:     0x7f580f7fc9bc - <unknown>
  18:     0x7f580f7f137a - <unknown>
  19:     0x7f580f7f1108 - <unknown>
  20:     0x7f580f7edab5 - <unknown>
Aborted

I pasted little more data for context :)

**Comment by epi052** [comment]
was the state file created with the same version of ferox as the one you're using when trying to resume?

**Comment by sectroyer** [comment]
Yeah and I have this issue with multiple state files.  Just encountered another one. Also is it normal (not sure if I should report it?) that state file is not created when I use --stdin flag ?

**Comment by epi052** [comment]
for the stdin thing, i'm not sure tbh, we can open an issue so i remember to look at it.

for the state file:
- what version of ferox?
- what was the exact command used when starting the initial scan (i can derive this from the state file if unknown)
- what was the exact command used when resuming
- can you provide one of the state files with redacted urls?
- are you using a different wordlist than the one you used in the initial scan?

**Comment by epi052** [comment]
if you used the same ferox versions for starting/resuming, my next guess is that you're trying to use a different wordlist than the one you started with

**Comment by sectroyer** [comment]
Nope it was exactly the same wordlist. I assumed there would be some issues with reproducing so I tried to anonymise everything and prepared a sample file. That confirmed still crashes feroxbuster using this cmd:
`feroxbuster -L 3 -A -B -w ~/hack/tools/SecLists/Discovery/Web-Content/raft-large-words-lowercase.txt --rate-limit 200 -x .htm,.html,.js,.xml,.json,.txt,.php,.jsp,.asp,.aspx,.conf,.config,.inc,.cfg -o  ../logs/test.txt -C 403,404 --resume-from ./test.state`

[test.state.zip](https://github.com/epi052/feroxbuster/files/10948470/test.state.zip)

**Comment by sectroyer** [comment]
> for the stdin thing, i'm not sure tbh, we can open an issue so i remember to look at it.

My bad there was a state file just with fferox-stdin name :) Tough I got same error with it:

thread 'tokio-runtime-worker' panicked at 'range start index 174546 out of range for slice of length 107983', src/event_handlers/scans.rs:302:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

**Comment by epi052** [comment]
awesome! appreciate the zip file. I'll take a look

**Comment by epi052** [comment]
ahhhhh, i think i understand what's going on now that i look at your state file.

I try to resume from roughly the same offset within the wordlist when resuming.

with the use of extensions et al, the number of requests per scan went way beyond any valid offset into the wordlist. 

I need to go back and account for extensions and things that allow that type of behavior. Thanks for reporting this!

once i get a solid handle on the formula, you should be able to run a search and replace on the `num_requests` field in your state file with new values to arrive at a proper state file

**Comment by epi052** [comment]
also, if you're ok with the old resume behavior where dir scans that weren't complete just start from the beginning, you could downgrade to 2.7.x; i think it would just ignore the new field in the state file used for the wordlist offset

**Comment by sectroyer** [comment]
Okay I will leave the sate file as it is. Let me know once you figure it out. I will try if formula fix helps. 😄 I am not in a hurry ant simple text replace is good enough fix for me 👍

**Comment by epi052** [comment]
ok, for your config, you should be able to do the following:

- for each scan entry in the `scans` array
- get the value for `num_requests` (i.e. 1619745 for the first one)
- perform the following adjustment on `num_requests`
```python
num_requests = 1_619_745
num_extensions = 14
wordlist_len = 107_982
adjusted = (num_requests // (num_extensions + 1) - 1)
assert adjusted <= wordlist_len
```
- save the new value to the state file

I'm still looking at things, but this is roughly what I'll be doing internally. For you, we may need to do something similar with `requests_made_so_far`, but i'm not sure yet

**Comment by epi052** [comment]
- yea, just for running scans.
- for requests_made_so_far, i THINK you should leave it as-is, but not 100% yet

**Comment by sectroyer** [comment]
I just replaced all occurrences of :1619745 with :107982 (your math was correct) and it looks to be working fine. I have one more question does feroxbuster retry requests to which it receives 429 status code ?

**Comment by epi052** [comment]
no, the only time it tries to be clever about 429s is when you use `--auto-tune` or `--auto-bail`

https://epi052.github.io/feroxbuster-docs/docs/examples/auto-tune/

**Comment by sectroyer** [comment]
Hmm yeah but auto-tune just slows down but does it retry? All there is no way to use `--auto-tune` with `--rate` but I don't want to start with full-power just maxmimum rate and go down in case of errors. Also I would really like 429 request to be retried 😄

**Comment by epi052** [comment]
nope, no retries at the moment. Also, there's no way to set a max rate limit with auto tune. both of those would be new features

**Comment by sectroyer** [comment]
Okay just to confirm with other project I had to also adjust `requests_made_so_far` as it was complaining that:
` thread 'tokio-runtime-worker' panicked at 'range start index 1132857 out of range for slice of length 107983', src/event_handlers/scans.rs:302:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted`

**Comment by sectroyer** [comment]
One more small issue (kinda "visual glitch" 😄 ) after resuming with those changes status is "broken":
`[####################] - 38m   220894/107982  96/s    https://example.com/0/ `

requests made I s higher the total and I think ETA calculation also isn't correct. Anyway it looks it does do correct number of requests themselves 👍

**Comment by epi052** [comment]
is that when the scan ends? locally mine looks good when i resume it

**Comment by sectroyer** [comment]
Okay looks it was showing "funny" numbers for scans that it had to finish, however for new ones it shows 1619749 which looks to be correct:
`[####################] - 2h    780109/107982  78/s    https://example.com/article/1/ 
[####################] - 4h   1515199/107982  86/s    https://example.com/article/2/ 
[####################] - 5h   1619749/107982  87/s    https://example.com/0/01/ 
[####################] - 4h   1619749/107982  97/s    https://example.com/0/02/ `

**Comment by epi052** [comment]
pretty sure i got the overage thing worked out

**Comment by sectroyer** [comment]
Does it work with old state files or should I start from scratch?

**Comment by epi052** [comment]
I think you should be able to use your original state file (without our adjustments)

**Comment by sectroyer** [comment]
Looks to be working correctly, thanks :)

**Comment by sectroyer** [comment]
I think I've noticed an issue. A lot of scans simply do not end. Just when they "end" they hung like this one:
`[####################] - 13h  1619745/1619745 33/s    https://exampple.com/forms/ 
[####################] - 13h  1619745/1619745 33/s    https://exapmple.com/promotions/ 
[####################] - 13h  1619745/1619745 33/s    https://exampple.com/test/ 
[####################] - 2h   1619745/1619745 150/s   https://exampple.com/promotions/test/`
And I have to ctrl-c it. Tested wity 2.9.1 and I think it also affects new scans.

**Comment by epi052** [comment]
so, start scan, ctrl+c, resume -> hang?

**Comment by epi052** [comment]
tried with
- GET, no extensions
- GET, POST, no extensions
- GET, POST, php, js

can't reproduce given what I assume the steps are. can you post your command and steps taken?

**Comment by sectroyer** [comment]
Okay it sometimes finishes sometimes doesn't. I have some suspicion tough. I run classically:
feroxbuster -L  1 -B -w ~/work/tools/SecLists/Discovery/Web-Content/raft-large-words-lowercase.txt -x  .htm,.html,.js,.xml,.json,.txt,.php,.jsp,.asp,.aspx,.conf,.config,.inc,.cfg  -C 403,404,405,500  -o ../logs/ferox_root_example_log.txt --proxy  socks5://127.0.0.1:40180 --rate-limit 290 -u http://example.com/

In this one I am using socks proxy but I think it was hanging even without it. One thin that I did is that I multiple times ctrl+c the app and resumed from state file after that in the end it hang with:
`###################>] - 14h  11330201/11338242 37s     found:13      errors:877    `
`[###################>] - 1h   1612159/1619745 241/s   https://example.com/ `
`[####################] - 1h   1619745/1619745 238/s   https://example.com/admin/` 
`[####################] - 1h   1619745/1619745 241/s   https://example.com/templates/` 
`[####################] - 1h   1619745/1619745 232/s   https://example.com/templates_c/` 
`[####################] - 2h   1619745/1619745 179/s   https://example.com/demo/ `
`[####################] - 2h   1619745/1619745 193/s   https://example.com/control/` 
`[--------------------] - 15s        0/1619745 0/s     / `
`[####################] - 1h   1619745/1619745 246/s   https://example.com/smarty/     `    

Slash was an error so I cancelled it in menu

**Comment by sectroyer** [comment]
I think I have encountered this bug once again. I run this command:
`feroxbuster -A -B -E -e -g -x .htm,.html,.js,.xml,.json,.txt,.php,.jsp,.asp,.aspx,.conf,.config,.inc,.cfg -w raft-large-words.txt -u https://example.com/ -L 1 --rate-limit 50 -k -C 404`

I waited for req counter to reach 750 and did ctrl+c:
```
>-------------------] - 17s      877/3588036 19h     found:2       errors:0                                                                                                     
🚨 Caught ctrl+c 🚨 saving scan state to ferox-https_example_com_-1688453072.state ...                                                                                   
[>-------------------] - 17s      877/3588036 19h     found:2       errors:0                                                                                                     
[>-------------------] - 16s      750/1794015 47/s    https://example.com/   
```

I manually edited the state file and repalced:
`"num_requests":1794015,"requests_made_so_far":750}`
to
`"num_requests":1794015,"requests_made_so_far":1700494}`
In order to reconstruct issue I have encounter during real scan.

And when I tried to resume I got this:
```
[####################] - 0s   1700494/0       0s      
[##################>-] - 0s   1700494/1794015 -       https://example.com/                                                                                               thread 'tokio-runtime-worker' panicked at 'range start index 121463 out of range for slice of length 119601', src/event_handlers/scans.rs:297:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

This error has same numbers I have encountered during real scan I was doing.
