### ISSUE TITLE
[FEATURE REQUEST] - Load wordlist from a url 

### ISSUE THREAD

**Issue by xaeroborg** [epi052/feroxbuster#827]
**Loading WordList from a url**
I have always wanted to run directory bruteforce or its likes with a wordlist that hasnt been downloaded to my local machine, instead it resides on a different server where I can include it from; for example: `feroxbuster -u https://target.com -rw https://myremoteserver.com/remote_located_wordlist.txt` whereas rw - remotely located wordlist

**Comment by epi052** [comment]
thanks for putting this in! this is a cool idea, and i don't think it would even need a second flag. we should be able to determine local vs. remote at runtime and either read from disk or network. 

pinning it for now, until i do some more ferox dev. I'd happily accept a PR in the interim tho!  thank again :pray:

**Comment by epi052** [comment]
ended up needing to do a bugfix, so knocked this out as well. it'll be live in 2.9.2. 

the logic is pretty simple
```
if wordlist.startswith('http') {
   get wordlist
} else {
   read wordlist from disk
}
```

![image](https://user-images.githubusercontent.com/43392618/226105070-c5624bc7-3d9c-40f9-bc58-b3841417aefd.png)

**Comment by xaeroborg** [comment]
Its great to see this idea has been successfully implemented, thanks a ton Epi
