### ISSUE TITLE
[BUG] thread 'tokio-runtime-worker' panicked at 'attempt to divide by zero', src/event_handlers/scans.rs:270:46

### ISSUE THREAD

**Issue by imBigo** [epi052/feroxbuster#832]
**Describe the bug**
Tried to run in WSL Ubuntu 20.04 and crashed.

**To Reproduce**
1. `./feroxbuster -u [URL] -w /usr/share/seclists/Discovery/Web-Content/raft-large-directories-lowercase.txt --thorough -A -r -t 2` in my machine

**Expected behavior**
Not crash, also I seem to always need to limit threads otherwise I keep getting errors.

**Traceback / Error Output**
```
thread 'tokio-runtime-worker' panicked at 'attempt to divide by zero', src/event_handlers/scans.rs:270:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    381 abort      ./feroxbuster -u [URL] -w  --thorough -A -r -t 2
```

**Environment (please complete the following information):**
 - feroxbuster version: v2.9.1
 - Ubuntu 20.04 on WSL in Windows 10

**Comment by epi052** [comment]
Thanks for this! I just pushed a fix to main. I'll push out a new version in the next few days.

**Comment by epi052** [comment]
@all-contributors add @imBigo for bugs
