### ISSUE TITLE
[FEATURE REQUEST] Force recursion when directory listing is detected

### ISSUE THREAD

**Issue by acut3** [epi052/feroxbuster#835]
**Is your feature request related to a problem? Please describe.**

As far as I can tell, there is no way to bruteforce under a certain path when a Directory Listing has been detected for that path. This is problematic because a reverse proxy could very well route a path to a backend server that does directory listing, but route another path under that path to a completely different backend that does something else. Feroxbuster will never find that route.

For example, I'm looking at a server right now that returns an empty directory listing for `/`. As a result feroxbuster will just stop there and don't do any bruteforcing at all, even when `--force-recursion` is set. There could be an `/api` route for example leading to a different backend, but feroxbuster would never find it.

**Describe the solution you'd like**

There should be a way to either disable detection of directory listings, or still allow normal bruteforcing when a directory listing has been detected. I feel like this is what `--force-recursion` should do, but maybe another flag could be added.

**Comment by epi052** [comment]
Howdy!

It sounds like you have `--extract-links` or `--smart` or `--thorough` turned on. If you remove those flags (most specifically `--extract-links`), things should behave the way you're describing.

**Comment by acut3** [comment]
I don't have any other flags, just `-w` and `-u`. Using feroxbuster 2.9.1.

**Comment by epi052** [comment]
any chance it's a public target that i can take a look at? 

If not, can you show me the response for the directory in burp or similar (can redact host etc)

**Comment by epi052** [comment]
it sounds like it's just simply not meeting criteria for recursion. in which case --force-recursion should work, but seeing the response would be helpful

**Comment by epi052** [comment]
also, to rule it out, you don't have a ferox-config.toml lying around (silently setting options), right?

**Comment by acut3** [comment]
I don't have any options set through config files.

I can't share this particular target, but the problem can be seen on any server with directory listing. For example, this empty directory on mirrors.edge.kernel.org:

```sh
echo -e 'aaa\nbbb' | feroxbuster --force-recursion -w /dev/stdin -u 'http://mirrors.edge.kernel.org/alpine/latest-stable/releases/x86_64/netboot/dtbs-lts'
```

**Comment by epi052** [comment]
pushed a fix to main; if you want to try it out, just make sure to build with `--release`.

i tested it briefly, but may have missed something somewhere. will put a few checks in place before pushing a new release, but it should work for you as-is right now

**Comment by epi052** [comment]
`--force-recursion` wasn't overriding the directory listing test; nice catch!

**Comment by epi052** [comment]
@all-contributors add @acut3 for bugs
