### ISSUE TITLE
[FEATURE REQUEST] custom location feature

### ISSUE THREAD

**Issue by duokebei** [epi052/feroxbuster#840]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

The author is very big, I don’t know how to add a function to find content in a custom location, for example: h5-moible, h5-app, h5-login, among them, moible, app, and login need to scan in a custom location.

**Comment by epi052** [comment]
Good morning! 

could you provide an example of your custom location?

I'm not entirely sure what you're asking for

**Comment by duokebei** [comment]
> Good morning!
> 
> could you provide an example of your custom location?
> 
> I'm not entirely sure what you're asking for

Similar to fuff, the location to be scanned is replaced by the fuzz keyword

**Comment by epi052** [comment]
ahh, gotcha. That's not currently supported. Also, we're already tracking that feature in #242. Closing this as a duplicate. 

Thank you for taking the time to put this in!
