### ISSUE TITLE
Could not connect to any target provided

### ISSUE THREAD

**Issue by vishrut66** [epi052/feroxbuster#848]
anyone facing  the same issue??
![2023-03-23 (1)](https://user-images.githubusercontent.com/108527286/227228854-07d7dd0a-4014-4732-beac-72c7565df036.png)

**Comment by epi052** [comment]
appears to be an issue in your local environment

![image](https://user-images.githubusercontent.com/43392618/227230795-0c8fde85-356a-4685-ac0c-9bb2f9a1a5e9.png)
