### ISSUE TITLE
[BUG] FeroxBuster does not exit after auto-bail

### ISSUE THREAD

**Issue by Nagaev** [epi052/feroxbuster#860]
**Describe the bug**
When the auto-bail mechanism is configured (it might be the case for other cases), FeroxBuster (at least sometimes) does not exit properly and the process hangs

**To Reproduce**
1. Use FeroxBuster on a target with --auto-bail
2. Trigger the auto-bail mechanism
3. (Possibly retest)

**Expected behavior**
The process exits correctly and does not hang

**Environment (please complete the following information):**
 - feroxbuster version 2.9.2
 - Ubuntu 22.04
 
![image](https://user-images.githubusercontent.com/12009364/228592172-03bb6fce-f45c-4a60-8958-8eaaa1c9bb75.png)

**Comment by epi052** [comment]
Morning! Thanks for reporting this. I'll take a look over the weekend and lyk what I find

**Comment by epi052** [comment]
Hey, took longer than i thought to get to this. I'm looking at it now and haven't been able to reproduce the bug yet. Not done looking at it, just wanted to give you an update.

**Comment by epi052** [comment]
i found a bud while testing that may have been responsible for this. there was a possibility that subtraction of an unsigned value when calculating progress bar stuff may have attempted to go below 0.

I fixed that particular bug in 2.9.4, but will leave this open to see if you or others see it happen again.

**Comment by NoPurposeInLife** [comment]
heyah! This is still occurring for me at the moment
