### ISSUE TITLE
[FEATURE REQUEST] Inter-Url Content Discovery

### ISSUE THREAD

**Issue by Zamanry** [epi052/feroxbuster#864]
**Is your feature request related to a problem? Please describe.**
I have read through the documentation, community examples, and the open/closed issues (best I can). I am trying to find a method using this tool to search within a URL. I am working on the OSCP and they give an example about searching for:
```
http://domain.tld/FUZZ/v1
```
...where we are trying to find what `FUZZ` is (such as trying to find v1 of an API). Is the possible with the tool as written?

**Describe the solution you'd like**
I'd like to be able to perform an inter-URL brute force as can be performed with at least `ffuf` and `gobuster`.

**Describe alternatives you've considered**
Although I wish not, my alternative is to use another tool only as this feature is required in the OSCP.

**Additional context**
N/A

**Comment by epi052** [comment]
There's no built-in way to do what you're asking. `ffuf` is (imo) still the best for an off-the-shelf solution for what you're trying to do.

If you want a workaround, and you know you have a static suffix (like your `/v1`) you can manipulate the wordlist, adding the static suffix to each line. A small example is shown below.
 
```
cat << EOF > wordlist
stuff
things
EOF
```

```
sed 's#$#/v1#g' wordlist > wordlist-with-suffix
```

```
cat wordlist-with-suffix
stuff/v1
things/v1
```

```
feroxbuster -u http://domain.tld/ -w wordlist-with-suffix
```

**Comment by epi052** [comment]
Another option, if you want a fully custom solution and don't mind writing a little rust, [feroxfuzz](https://github.com/epi052/feroxfuzz) has a bunch of examples and is well commented / documented.

**Comment by epi052** [comment]
hopefully one of the workarounds helped, or you found your way to ffuf for this particular use. feel free to reopen if more discussion is needed
