### ISSUE TITLE
[FEATURE REQUEST] Install feroxbuster to common directory when using install-nix.sh

### ISSUE THREAD

**Issue by aancw** [epi052/feroxbuster#867]
**Is your feature request related to a problem? Please describe.**
In the current version, when installing feroxbuster with install-nix.sh it will only unzip the binary. Better to place the binary in the common folder like `$HOME/.local/bin` for Linux and macos

**Describe the solution you'd like**
Feroxbuster installed on `$HOME/.local/bin`. So it can be called everywhere on the system.

**Describe alternatives you've considered**
Add the copy method in install-nix.sh

**Comment by epi052** [comment]
howdy! this is a pretty simple fix, i was thinking of just accepting an arg to install-nix.sh and then plopping it in the cwd if no arg is given. What do you think?

**Comment by epi052** [comment]
local testing

```
❯ cat install-nix.sh| bash -s /tmp
[+] Installing feroxbuster to /tmp!
[+] unzip found
[=] Found 64-bit Linux, downloading from https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip
[=] Found Noto Emoji Font, skipping install
[+] Installed feroxbuster
  [-] path: /tmp/feroxbuster
  [-] version: 2.9.3
❯ cat install-nix.sh| bash
[+] Installing feroxbuster to /home/epi/PycharmProjects/feroxbuster!
[+] unzip found
[=] Found 64-bit Linux, downloading from https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip
[=] Found Noto Emoji Font, skipping install
[+] Installed feroxbuster
  [-] path: /home/epi/PycharmProjects/feroxbuster/feroxbuster
  [-] version: 2.9.3
```

**Comment by epi052** [comment]
k, updated the script and the README to reflect both ways of using the script.

@all-contributors add @aancw for ideas

**Comment by epi052** [comment]
k, script and readme are updated :grin:

**Comment by aancw** [comment]
> local testing
> 
> ```
> ❯ cat install-nix.sh| bash -s /tmp
> [+] Installing feroxbuster to /tmp!
> [+] unzip found
> [=] Found 64-bit Linux, downloading from https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip
> [=] Found Noto Emoji Font, skipping install
> [+] Installed feroxbuster
>   [-] path: /tmp/feroxbuster
>   [-] version: 2.9.3
> ```
> ```
> ❯ cat install-nix.sh| bash
> [+] Installing feroxbuster to /home/epi/feroxbuster!
> [+] unzip found
> [=] Found 64-bit Linux, downloading from https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip
> [=] Found Noto Emoji Font, skipping install
> [+] Installed feroxbuster
>   [-] path: /home/epi/feroxbuster/feroxbuster
>   [-] version: 2.9.3
> ```

Nice 👍👍
