### ISSUE TITLE
[FEATURE REQUEST]  Add support for Client SSL certificate

### ISSUE THREAD

**Issue by AkechiShiro** [epi052/feroxbuster#870]
**Is your feature request related to a problem? Please describe.**
Feroxbuster should be able to take as an option a custom TLS client certificate, there might be instances where this is needed to connect to a server. 
Similar to ffuf's feature request : https://github.com/ffuf/ffuf/issues/477

**Describe the solution you'd like**
A new flag `--cert` in Client settings, allowing to pass a certificate in PEM/DER format.

**Describe alternatives you've considered**
I've tried to see if it was possible to add/trust the certificate system wide but it is really not simple, see https://superuser.com/questions/1690574/is-it-possible-to-add-system-wide-client-certificates-on-linux-openssl

**Comment by epi052** [comment]
This is a really interesting feature, thanks for submitting it!

I don't have the time right now to implement this, but will pin it for now. If someone else feels like taking it up, I'd happily accept a PR in the interim.

**Comment by AkechiShiro** [comment]
Thanks for accepting this feature request, would you be able to describe the modification needed or some of the steps needed to take in order to implement this feature ? I might want to try and take a look but I'm not sure if I'll be able to implement the feature.

**Comment by epi052** [comment]
If you decide to give it a shot, let me know here and we'll assign the feature to you. I'll be happy to answer questions as you go.

**Comment by aancw** [comment]
After reading the reqwest documentation, you can implement the feature using `add_root_certificate` to connect to server using self sign certificate
https://docs.rs/reqwest/latest/reqwest/struct.ClientBuilder.html#method.add_root_certificate

**Comment by aancw** [comment]
I'm still trying to figure out the cert implementation for feroxbuster and working in progress. For the local webserver, I use go-httpbin because it support many additional feature like gzip, self sign cert and more.


https://github.com/mccutchen/go-httpbin

**Comment by epi052** [comment]
@aancw my understanding is that the request is to support passing a client certificate.

This would be useful when the server expects [mutual authentication](https://techdocs.akamai.com/iot-ota-updates/docs/mutual-auth#:~:text=Mutual%20authentication%2C%20also%20known%20as,certificates%20to%20prove%20their%20identities)

only adding a root certificate on the client side would not fulfill requirements for when a client must authenticate itself to a server (again, i believe this is what the request as for)

@AkechiShiro was the feature request was for the client side of a mutual auth connection or am i confused?

**Comment by lavafroth** [comment]
Hey everyone. I drafted a PR to add the `--certificate` flag to pass a file to be added as a root certificate. I'd appreciate it if any of you took a look at the changes and make sure it looks good.

**Comment by AkechiShiro** [comment]
@epi052 you are correct, my feature request was about client certificats authentification and not about using a custom CA certificate.

**Comment by aancw** [comment]
Well done @lavafroth for fast implementation of the feature 👍🏻

**Comment by epi052** [comment]
@all-contributors add @AkechiShiro for ideas

**Comment by epi052** [comment]
@all-contributors add @lavafroth for code

**Comment by epi052** [comment]
good bot
