### ISSUE TITLE
[BUG] Using --update flag not working for aarch64-linux

### ISSUE THREAD

**Issue by DrorDvash** [epi052/feroxbuster#876]
When trying to update feroxbuster via `-U/--update` flag, the update fails as you can see below:
```Bash
└─# feroxbuster -U    
Checking target-arch... aarch64-linux
Checking current version... v2.9.2
Checking latest released version... v2.9.3
New release found! v2.9.2 --> v2.9.3
New release is compatible

[ERROR] ReleaseError: No asset found for target: `aarch64-linux`
```

I used to download the zip file `aarch64-feroxbuster.zip` from the Releases page, and it's compatible and working...so why updating via the tool itself it's not working? 

**Environment:**
- System: Kali VM running on MacOS m1
- Current version: Feroxbuster v2.9.2

**Comment by epi052** [comment]
thanks for posting this!

at a glance, i think it's just a naming thing. I just added a zip named `aarch64-linux-feroxbuster.zip` to the 2.9.3 release page. Can you try again (at your convenience) and report back with what happens?

**Comment by DrorDvash** [comment]
Yes, it worked. I also thought the same. maybe you can change in the source code that everything that comes after the dash (-) will be ignored and will download `aarch64-feroxbuster.zip`

anyway, this is the output now :))
```
└─# feroxbuster -U    
Checking target-arch... aarch64-linux
Checking current version... v2.9.2
Checking latest released version... v2.9.3
New release found! v2.9.2 --> v2.9.3
New release is compatible

feroxbuster release status:
  * Current exe: "/usr/bin/feroxbuster"
  * New exe release: "aarch64-linux-feroxbuster.zip"
  * New exe download url: "https://api.github.com/repos/epi052/feroxbuster/releases/assets/104362686"

The new release will be downloaded/extracted and the existing binary will be replaced.
Do you want to continue? [Y/n] 
Downloading...
[00:00:00] [========================================] 3.22 MiB/3.22 MiB (0s) Done                                                                                                                                                                                  Extracting archive... Done
Replacing binary file... Done

Feroxbuster updated to 2.9.3 version
```

**Comment by epi052** [comment]
awesome! yea, this is an easy one. thanks again!

**Comment by epi052** [comment]
@all-contributors add DrorDvash for bugs
