### ISSUE TITLE
[FEATURE REQUEST] Response code blacklist, improved white/blacklisting abilities

### ISSUE THREAD

**Issue by LMAY75** [epi052/feroxbuster#88]
Ferox should support the ability to blacklist certain response codes, similar to the --hc flag in wfuzz. This would make it drastically easier to hide just one or two codes, versus the current alternative of having to whitelist all the codes you want to see.

**Comment by epi052** [comment]
@LMAY75 

Thanks for the request!  I'm on board with the blacklist.  

The word count / line count option is a little different.  Currently, we don't read the body of the response at all.  Reading the body of each response isn't out of the question, but I don't plan to append it on to this ticket.  I'm going to split out your second request and leave it as a separate feature. 

Thanks again!
