### ISSUE TITLE
[BUG] thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ktecv2000** [epi052/feroxbuster#905]
I think it's similar to issue #563, and I've encountered this issue on version `2.10.0` and `2.9.1`

I try to remove other unrelated argument as much as possible and this is the shortest command I could possibly reproduce this issue

```
feroxbuster -u "<myurl>" -w raft-medium-files-lowercase.txt --collect-words
```

Error:
**thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/nlp/document.rs:51:14**

It might be related to `--collect-words` option

**Comment by epi052** [comment]
it's just a place where i used unwrap, thinking it would always be valid, but it isnt 🙃 

a quick look at the code in question makes me think the page you're requesting doesn't have a `<body>` tag

**Comment by ktecv2000** [comment]
There's a `<body>` tag within the request page

**Comment by ktecv2000** [comment]
After debugging my ass hell out I found the which page is blamed for

 ```html
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Export to PDF</title>
<script type="text/javascript">
window.status='Export to PDF';
</script>
</head>

<frameset rows="0,*"" frameborder="NO" border="0" framespacing="0">
  <frame src="" name="topFrame" id="topFrame" title="topFrame" />
  <frame src="http://redacted.com/capture/pdf.php?url=" name="mainFrame" id="mainFrame" title="mainFrame" />
</frameset>
<noframes><body>
</body>
</noframes></html>
 ```
 
 looks like there's indeed a `<body>` , I'm not sure why this broke the fuzzer

**Comment by epi052** [comment]
@all-contributors add @ktecv2000 for bugs
