### ISSUE TITLE
[BUG] FeroxBuster does not exit after auto-bail 

### ISSUE THREAD

**Issue by NoPurposeInLife** [epi052/feroxbuster#906]
**Describe the bug**
When the auto-bail mechanism is configured (it might be the case for other cases), FeroxBuster (at least sometimes) does not exit properly and the process hangs

**To Reproduce**

1. Use FeroxBuster on a target with --auto-bail
2. Trigger the auto-bail mechanism
3. (Possibly retest)

**Expected behavior**
The process exits correctly and does not hang

**Environment (please complete the following information):**
- feroxbuster version 2.10.0
- Ubuntu 22.04

**Additional context**
![image](https://github.com/epi052/feroxbuster/assets/30126475/314fdc7e-21f7-4bf4-a651-faf8a0576566)

![image](https://github.com/epi052/feroxbuster/assets/30126475/5d94e774-a4c9-4948-91c4-5e637e85fb22)

**Comment by NoPurposeInLife** [comment]
Linked #860

**Comment by epi052** [comment]
hey there, sorry for the late reply.

to clarify, auto bail triggers and then ultimately, the overall process doesn't exit cleanly?

**Comment by epi052** [comment]
following up: i ran a scan with `--auto-bail` against a target that randomly generates different status codes (auto-bail gets triggered regularly). I ran this scan in a while loop and left it for a few hours (the scan takes ~5 secs to complete without auto-bail, faster if the primary scan dir bails). When I came back, the while loop was still looping, meaning none of the scans hung.

going to close this for now. if you see it again on the most current ferox version, please reopen the issue. Thank you!

**Comment by epi052** [comment]
following up: i ran a scan with `--auto-bail` against a target that randomly generates different status codes (auto-bail gets triggered regularly). I ran this scan in a while loop and left it for a few hours (the scan takes ~5 secs to complete without auto-bail, faster if the primary scan dir bails). When I came back, the while loop was still looping, meaning none of the scans hung.

going to close this for now. if you see it again on the most current ferox version, please reopen the issue. Thank you!
