### ISSUE TITLE
[FEATURE REQUEST] Support reading extension list from a file

### ISSUE THREAD

**Issue by sectroyer** [epi052/feroxbuster#925]
Currently -x accepts extensions list only as a string. Therefore I have to do something like this:
`-x $(cat ext.txt)`
to avoid retyping my extension list every time. It would be convenient to read them from file directly. If user specified valid file path as -x parameter value 😄

**Comment by epi052** [comment]
we have similar behavior in other places, -x could have that support as well

**Comment by sectroyer** [comment]
Currently it is necessary to use @ at the beginning of file path. As a result it's not possible to use bash autocompletion or path's like ~/extensions.txt. I think it would be best to avoid @ requirement and instead check if file path exists
