### ISSUE TITLE
[FEATURE REQUEST] Remove canceled directories from active scans screen

### ISSUE THREAD

**Issue by sectroyer** [epi052/feroxbuster#926]
Currently when I remove folder from a scan queue using "cancel" option they still stay on list and are refreshed every second. When this lists gets longer than single screen it gets very unreadable. It would be nice to have them removed from this list once they are cancelled. Currently only way to achieve that is to Ctrl+c the app and restart from restore point.

**Comment by epi052** [comment]
howdy! that seems reasonable. The underlying data structure is tied to how scans are saved/resumed, so i don't think the implementation should remove them, however, it should be simple enough to alter the behavior to either not show them at all, or not show them once the number of scans reaches a certain threshold

**Comment by sectroyer** [comment]
Yeah something like this would also work. What I noticed is that every second ferox tries to refresh whole list of scans (even finished one). When the number of scans exceeds a single screen it has strange effects. For example in tmux It causes kind of flickering. Keeping the number to single screen seems to solve all the issues I have encountered.

**Comment by epi052** [comment]
@all-contributors add @sectroyer for bugs and ideas
