### ISSUE TITLE
[BUG] Scan Management Menu Ranges

### ISSUE THREAD

**Issue by godylockz** [epi052/feroxbuster#935]
**Describe the bug**
When pausing a scan, the user is prompted for the Scan Management Menu.
If the user wanted to cancel all recursive results other than id 0, it is not possible to do so in one range. For instance, selecting 1-100 would prompt to cancel each and every scan.  either remove the confirmation or remove the scan results from the selection of the IDs unless they are directories.

**Environment (please complete the following information):**
 - feroxbuster version: 2.10.0
 - OS Kali

**Example**
─────────────────────────────────────────────────────────────────────────
                       💀 Scan Management Menu 💀                        
─────────────────────────────────────────────────────────────────────────
Scans:
  0: running      http://example.com/
  3: running      http://example.com/img/
  4: running      http://example.com/fontawesome/
  5: running      http://example.com/js/parallax/
  6: running      http://example.com/img/gallery/tn/
  9: running      http://example.com/fontawesome/css/
 12: running      http://example.com/css/
 14: running      http://example.com/img/gallery/
 17: running      http://example.com/js/
 18: running      http://example.com/slick/
104: running      http://example.com/slick/fonts/
─────────────────────────────────────────────────────────────────────────
Filters:
  1: GET requests with 404 responses containing 564 bytes, 84 words, and 13 lines
  2: Pages similar to: http://example.com/1be610d04532497a96725b82d7ede1b6
─────────────────────────────────────────────────────────────────────────
Commands:
  a[dd] NEW_URL (ex: add http://localhost)
  c[ancel] [-f] SCAN_ID[-SCAN_ID[,...]] (ex: cancel 1-4,8,9-13 or c -f 3)
  n[ew-filter] FILTER_TYPE FILTER_VALUE (ex: n lines 40)
    FILTER_TYPEs: status, lines, size, words, regex, similarity
  r[m-filter] FILTER_ID[-FILTER_ID[,...]] (ex: rm-filter 1-4,8,9-13 or r 3)
─────────────────────────────────────────────────────────────────────────
c 3-104
You sure you wanna cancel this scan: http://example.com/img/? [Y/n]
Stopping http://example.com/img/...

You sure you wanna cancel this scan: http://example.com/fontawesome/? [Y/n]
Stopping http://example.com/fontawesome/...
yYou sure you wanna cancel this scan: http://example.com/js/parallax/? [Y/n]
Stopping http://example.com/js/parallax/...
yYou sure you wanna cancel this scan: http://example.com/img/gallery/tn/? [Y/n]
Stopping http://example.com/img/gallery/tn/...
yYou sure you wanna cancel this scan: http://example.com/slick/slick.min.css? [Y/n]
Stopping http://example.com/slick/slick.min.css...
yyYou sure you wanna cancel this scan: http://example.com/js/jquery.singlePageNav.min.js? [Y/n]
Stopping http://example.com/js/jquery.singlePageNav.min.js...
yyYou sure you wanna cancel this scan: http://example.com/fontawesome/css/? [Y/n]

**Comment by godylockz** [comment]
It works when i do `c -f 1-100`. Only thing is it stops files too and the counter gets all messed up. 
[>-------------------] - 64s     6793/18446744073700371814 247565060y found:101     errors:3204

**Comment by epi052** [comment]
ahh, ok, i see
