### ISSUE TITLE
[BUG]  too many Errors 

### ISSUE THREAD

**Issue by weujieytt** [epi052/feroxbuster#960]
feroxbuster  --insecure --auto-bail   --collect-backups   --collect-words  --random-agent --scan-limit 2 --dont-scan '/(css|images|img)' -r  -S 0  -C 404,400,500 -x js,html,json,jsp --depth 3 -u http://www.baidu.com  

When everything is too many Errors, wait for work.
![image](https://github.com/epi052/feroxbuster/assets/70327097/2e2a49b9-1048-4e02-a372-13709a6803eb)

**Comment by epi052** [comment]
it sounds like you may want `--auto-tune` instead of `--auto-bail`
