### ISSUE TITLE
Links don't show up at the top like in the example[BUG] 

### ISSUE THREAD

**Issue by ryanrohypnol** [epi052/feroxbuster#98]
When I run FeroxBuster with default settings, my output is full of status bars instead of all of the directories listed at the bottom. Is there a setting that I'm missing? I'm on Kali 2020, with the latest release 1.2.0 

See Below:
![image](https://user-images.githubusercontent.com/44453666/97110742-49e99780-16b1-11eb-98e4-68d0b4033503.png)

Thank you

**Comment by epi052** [comment]
Hi Ryan, thanks for the report!  

Are you able to make your terminal window wider?  If so, make it wider and rerun then let me know if you see the same behavior.

**Comment by epi052** [comment]
Also, can you run `stty size` and let me know the results ?

**Comment by epi052** [comment]
It looks like a terminal width of less than 85 will cause this behavior.  Can you confirm that sizing your terminal at least 85 wide fixes the issue?

**Comment by ryanrohypnol** [comment]
That fixed it! My stty size is 30, 72. 

Thank you.

**Comment by epi052** [comment]
Anytime!  Glad it was an easy one :smile: Closing.
