### ISSUE TITLE
[FEATURE REQUEST] Add Multiple Wordlists rather than only one

### ISSUE THREAD

**Issue by sawmj** [epi052/feroxbuster#985]
Hey I love your tool man! well done!
I've started using feroxbuster for sometime now.

And I feel like we really need to be able to use multiple wordlists in the same scan rather than waiting till the scan finish and start a new one with the other wordlist

Something like 
feroxbuster -u http://site -w wordlist_1.txt, wordlist_2.txt, wordlist_3.txt

Where the scan uses the first wordlist and when it finishes it continue the scan with using the next wordlist

**Comment by epi052** [comment]
tyvm! always like hearing that folks find it useful :pray: 

how is what you propose different from something like what's below? 

```
feroxbuster -u http://site/ -w <(cat wordlist_1.txt, wordlist_2.txt, wordlist_3.txt)
```

**Comment by sawmj** [comment]
oh no it's exactly what I needed to do!
And it works!
Just without the coma 
`feroxbuster -u http://site/ -w <(cat wordlist_1.txt wordlist_2.txt wordlist_3.txt)`

**Comment by epi052** [comment]
haha, good catch. I just C&P'd yours and added the `<()`, glad it worked!

**Comment by epi052** [comment]
looks like this is handled; closing this one, feel free to reopen if necessary.
