### ISSUE TITLE
[BUG] - Can't "CTRL +C" To Cancel, When Working Dir is  Non-Writable Folder. 

### ISSUE THREAD

**Issue by N0ur5** [epi052/feroxbuster#996]
**Describe the bug**
If I run Ferox from a directory that I do not have permissions to write to, when trying to use "ctrl+c" to cancel a running job, the job refuses to cancel. 

**To Reproduce**
1. Run a job from a directory you do not have permissions to write to
2. Try to cancel the job with crtl+c - note it says canceling but doesn't cancel. 
3. Run the job again with sudo or from a directory you can write to - note you can now cancel the job.

**Expected behavior**
ctrl+c should cancel the job even if I ran it from a non-writeable directory. This means the .state file cannot be written, but that is the lesser of two issues in situations where the web server being targeted starts to have degraded performance or is overwhelmed from a feroxbuster job. 

**Environment (please complete the following information):**
 - feroxbuster version: 2.10.0
 - OS: Debian 5.18.5-1kali6

**Additional context**
The user should be warned their state file won't be saved if ran from a non-writeable directory or the state file should be saved to some "fail-safe" or commonly world-writable directory. Alternatively, the jobs cancellation can be made independent of the state file write job so that the inability for the state file to be written does not prevent the job from canceling.

**Comment by epi052** [comment]
hey there, thanks for submitting this! I'll get this tested/confirmed and add a patch to just dump state into tmp or similar. Pretty easy fix, just never considered the possibility 🙃

**Comment by epi052** [comment]
the change was pretty minimal, so just yeeted it into main

first, if the current directory fails, we try /tmp [os specific](https://doc.rust-lang.org/nightly/std/env/fn.temp_dir.html#)

![image](https://github.com/epi052/feroxbuster/assets/43392618/d7ab0587-c743-4fcf-8e46-e574813f3675)

if the temp directory also fails, we just exit

![image](https://github.com/epi052/feroxbuster/assets/43392618/c37268ce-c3ad-42df-8b04-3326d150ae50)

**Comment by epi052** [comment]
gonna close this one for now, feel free to reopen if anything i missed something

**Comment by epi052** [comment]
@all-contributors add @N0ur5 for bug

**Comment by N0ur5** [comment]
> the change was pretty minimal, so just yeeted it into main

+1 for quick fix
+1 for use of "yeeted"
+1 for being awesome
